### ISSUE TITLE
Feature Request: Umbrel Build

### ISSUE THREAD

**Issue by awholegnuworld** [ArchiveBox/ArchiveBox#1001]
I have tried building this project for Umbrel, but I failed. https://github.com/getumbrel/umbrel-apps

## Type 

 - [x] General question or discussion
 - [ ] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves
Being able to install ArchiveBox as an app on Umbrel Nodes.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
I was wondering if anyone could point me towards what I have done wrong in compiling this?

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [x] It would be nice to have eventually

---

 - [x] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
duplicate: https://github.com/ArchiveBox/ArchiveBox/issues/986
