### ISSUE TITLE
Bug: CHROME_BINARY config ignored by Docker container

### ISSUE THREAD

**Issue by agnosticlines** [ArchiveBox/ArchiveBox#1003]
#### Describe the bug

If you set the chrome binary in the `ArchiveBox.conf` file, the changes are ignored when running with Docker

#### Steps to reproduce

1. Add the following to `ArchiveBox.conf`:

```
[SERVER_CONFIG]
SECRET_KEY = SECRET_KEY_HERE

[DEPENDENCY_CONFIG]
CHROME_BINARY = chromium2
```

2. Run ArchiveBox with docker-compose
3. Add a new URL for archive using the SingleFIle module
4. View the admin logs for that archive
5. See the output

```
Run to see full output: cd /data/archive/1658662117.468753; /node/node_modules/single-file/cli/single-file --browser-executable-path=chromium
```

The code does take the config into account (from ArchiveBox/extractors/singlefile.py:47)

```py
    # SingleFile CLI Docs: https://github.com/gildas-lormeau/SingleFile/tree/master/cli
    browser_args = '--browser-args={}'.format(json.dumps(browser_args[1:]))
    cmd = [
        DEPENDENCIES['SINGLEFILE_BINARY']['path'],
        '--browser-executable-path={}'.format(CHROME_BINARY),
        browser_args,
        link.url,
        output,
    ]
```

But I guess the Dockerfile overwrites that, so you have to set it in the dockerfile or docker compose environment variables, this isn't super clear and may confuse new users

**Comment by pirate** [comment]
How exactly are you running a non-standard chromium binary in the Docker image? Are you using a custom Dockerfile or loading a custom executable via a volume?

**Comment by agnosticlines** [comment]
I'm not, I was trying to find a workaround for the `/usr/bin/chromium` link that you added to the dockerfile, when I was doing it though I noticed this option wasn't respected, it may not be important and looking back on it this option probably only makes sense on a normal install not a dockerized one.
My bad!
