### ISSUE TITLE
Feature Request: How to change db engine to mysql or mangodb 

### ISSUE THREAD

**Issue by thinker007** [ArchiveBox/ArchiveBox#1005]
## Type 

 - [ x] General question or discussion
 - [x ] Request modification of existing behavior or design

## What is the problem that your feature request solves
I need to archive large scale web page, need a better db solution.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
change db from sqlite3 to mysql or mangodb for better archive performance and large scale web page archieve

## What hacks or alternative solutions have you tried to solve the problem?
move data from sqlite3 to mysql manually.

## How badly do you want this new feature?

 - [x ] It's an urgent deal-breaker, I can't live without it

---

 - [x] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
Not supported currently and not going to support this within the next few years, sorry. SQLite is a much more durable data format than Mysql or Postgresql, and it's easier on many levels because of the lack of need to run a dedicated server process.

**Comment by thinker007** [comment]
when I try to archive 1 million urls, then the db became a bottle neck ! the db lock problem pops up frequently

**Comment by pirate** [comment]
Are you archiving with multiple parallel processes? With a single process there is no db lock contention. It's more likely the parallel processes that are causing lock contention, not the size of the archive.,
