### ISSUE TITLE
Question: binary path in config

### ISSUE THREAD

**Issue by Dontkickmi22** [ArchiveBox/ArchiveBox#1009]
Hi, first post (this is how much I want it back)

Short version:
Can anyone please give me a pointer about where exactly is `./node_modules/single-file/cli/single-file` ?
I need to specify them in my conf file.
Thank you

Long version:
Pi 4, docker installaion, ran fine for the past weeks, just broke on me out of the blue. 
Snapshot quickly stopped at 6MB (that particular page from my experience should be way less than 6MB). 
Error log says unable to install chromium thru playwright.
I decided to skip docker and install on host (not gonna T-shoot that).
Did init, updated node.js, setup. Output of archivebox version below looks fine. 
But when trying to snapshot again, I got chromium `Errno 2, singlefile Errno 2, and readability Errno 2 , and mercury Errno 2.`

```logs
           ...
            Extractor failed:                                                                                                   
            FileNotFoundError [Errno 2] No such file or directory: 'single-file': 'single-file'
            Extractor failed:                                                                                                   
            FileNotFoundError [Errno 2] No such file or directory: 'readability-extractor': 'readability-extractor'
           ...
```
So I looked up the chromium binary location from archivebox version output and added below in ArchiveBox.conf 
`CHROME_BINARY = /usr/bin/chromium-browser`
That fixed the chromium Errno 2. That was easy.

So I go ahead and did the same to singlefile, readability, and mercury in ArchiveBox.conf
```ini
SINGLEFILE_BINARY = ./node_modules/single-file/cli/single-file
READABILITY_BINARY =  ./node_modules/readability-extractor/readability-extractor
MERCURY_BINARY = ./node_modules/@postlight/mercury-parser/cli.js
```
Error stays. Pointer please~!

Thank you

```bash
$ archivebox version
ArchiveBox v0.6.2
Cpython Linux Linux-5.10.103-v8+-aarch64-with-debian-10.12 aarch64
IN_DOCKER=False DEBUG=False IS_TTY=True TZ=UTC SEARCH_BACKEND_ENGINE=ripgrep

[i] Dependency versions:
 √  ARCHIVEBOX_BINARY                 v0.6.2          valid     /usr/bin/archivebox                                                         
 √  PYTHON_BINARY                         v3.7.3          valid     /usr/bin/python3.7                                                          
 √  DJANGO_BINARY                       v3.1.14          valid     /usr/local/lib/python3.7/dist-packages/django/bin/django-admin.py           
 √  CURL_BINARY                           v7.64.0          valid     /usr/bin/curl                                                               
 √  WGET_BINARY                           v1.20.1          valid     /usr/bin/wget                                                               
 √  NODE_BINARY                         v16.16.0         valid     /usr/bin/node                                                               
 √  SINGLEFILE_BINARY                  v1.0.11          valid     ./node_modules/single-file/cli/single-file                                  
 √  READABILITY_BINARY                v0.0.4          valid     ./node_modules/readability-extractor/readability-extractor                  
 √  MERCURY_BINARY                      v1.0.0          valid     ./node_modules/@postlight/mercury-parser/cli.js                             
 √  GIT_BINARY                               v2.20.1          valid     /usr/bin/git                                                                
 √  YOUTUBEDL_BINARY        v2021.12.17          valid     /usr/local/bin/youtube-dl                                                   
 √  CHROME_BINARY         v92.0.4515.98          valid     /usr/bin/chromium-browser                                                   
 √  RIPGREP_BINARY                      v0.10.0         valid     /usr/bin/rg                                                                 

[i] Source-code locations:
 √  PACKAGE_DIR           23 files        valid     /usr/lib/python3/dist-packages/archivebox                                   
 √  TEMPLATES_DIR         3 files         valid     /usr/lib/python3/dist-packages/archivebox/templates                         
 -  CUSTOM_TEMPLATES_DIR  -               disabled                                                                              

[i] Secrets locations:
 -  CHROME_USER_DATA_DIR  -               disabled                                                                              
 -  COOKIES_FILE          -               disabled                                                                              

[i] Data locations:
 √  OUTPUT_DIR            7 files         valid     /media/archive                                                              
 √  SOURCES_DIR           0 files         valid     ./sources                                                                   
 √  LOGS_DIR              1 files         valid     ./logs                                                                      
 √  ARCHIVE_DIR           0 files         valid     ./archive                                                                   
 √  CONFIG_FILE           81.0 Bytes      valid     ./ArchiveBox.conf                                                           
 √  SQL_INDEX             204.0 KB        valid     ./index.sqlite3                                                             
```

**Comment by pirate** [comment]
Set it to the absolute path of `./node_modules/@postlight/mercury-parser/cli.js` not the relative one, e.g. `/Users/yourusername/archivebox/node_modules/@postlight/mercury-parser/cli.js`

**Comment by Dontkickmi22** [comment]
Hi pirate,

Appreciate your input.

Short version, how can I reinstall those three programs? I mean uninstall, and reinstall? 

Long version, 
a quick find returns those directories are only installed deep beneath under /var/lib/docker/overlay/... 

sudo find / -type d -name 'single-file' -print
/var/lib/docker/overlay2/2890280801cbc09c113a55412143e8cfa33ca15482844ed75edbf8a3eceaad49/diff/node/node_modules/single-file
/var/lib/docker/overlay2/2890280801cbc09c113a55412143e8cfa33ca15482844ed75edbf8a3eceaad49/diff/node/node_modules/single-file/lib/single-file
/var/lib/docker/overlay2/2890280801cbc09c113a55412143e8cfa33ca15482844ed75edbf8a3eceaad49/diff/node/node_modules/single-file/extension/lib/single-file
/var/lib/docker/overlay2/1337d919d623720d99fd9abbbc5a4ddcd5514395a3a1e305701eab29d4954b77/diff/app/node_modules/single-file
/var/lib/docker/overlay2/1337d919d623720d99fd9abbbc5a4ddcd5514395a3a1e305701eab29d4954b77/diff/app/node_modules/single-file/lib/single-file
/var/lib/docker/overlay2/1337d919d623720d99fd9abbbc5a4ddcd5514395a3a1e305701eab29d4954b77/diff/app/node_modules/single-file/extension/lib/single-file

However, I did the current installation under user pi with apt install archivebox. 
To reinstall, I ran :

npm install --no-audit --no-fund 'git+https://github.com/gildas-lormeau/SingleFile.git'

Returns:
...
npm ERR! Tracker "idealTree" already exists
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-08-05T00_20_56_807Z-debug-0.log
...

Above mentioned log:
verbose stack Error: Tracker "idealTree" already exists
43 verbose stack     at Arborist.[_onError] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/tracker.js:100:11)
43 verbose stack     at Arborist.addTracker (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/tracker.js:27:21)
43 verbose stack     at Arborist.[buildDeps] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:823:10)
43 verbose stack     at Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:29)
43 verbose stack     at async Promise.all (index 1)
43 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
43 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:156:5)
43 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:78:5)

**Comment by pirate** [comment]
if you're running in docker you shouldnt need to mess with or install those 3 manually, but outside of docker to fix it you should just need to run `archivebox init --setup` and it will do the `npm install` for you.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/511499/183137838-865f9aa4-1dfb-45c7-b4e1-40cc3bd5d616.png">

**Comment by Dontkickmi22** [comment]
thank you, your command did it.

**Comment by Dontkickmi22** [comment]
By the way, deleting some of the snapshots gives me server error 500. Have you encounter these before?

**Comment by pirate** [comment]
Please screenshot your extension configuration. I suspect you did not enter the archivebox host correctly / at all as it's empty according to the outputed error above.

**Comment by Dontkickmi22** [comment]
![Screen Shot 2022-08-09 at 6 24 33 PM](https://user-images.githubusercontent.com/110583321/183626038-613af905-2fbc-4ae0-9a8f-ca06f71e1c50.png)

Here's the shot
