### ISSUE TITLE
Question: Can I disable all JS without breaking the UI?

### ISSUE THREAD

**Issue by kotovalexarian** [ArchiveBox/ArchiveBox#1011]
Hello. I don't want any untrusted JS to run on my subdomain. I know that JS stripping (#237) is not yet implemented. I know that you recommend (#239) to disable some extractors, but I don't want to do this because I want to save as much information about webpages as possiblle (except JS). So I'm going to do the following:

* Drop (HTTP 404) any file with `application/javascript` MIME type using Nginx
* Use Content Security Policy with `script-src 'none'`

This will disable all JS, even that is included with ArchiveBox if such exists. My question: **is any JS included with ArchiveBox and is it essential?**

**Comment by kotovalexarian** [comment]
I've found that ArchiveBox is somewhat broken if JS is disabled. At least the appearance. It requires at least JS files and `'unsafe-inline'` CSP permission.

**Comment by kotovalexarian** [comment]
Actually the minimal CSP is the following:
```
default-src https://example.com:443;
script-src https://example.com:443 'unsafe-inline';
style-src https://example.com:443 'unsafe-inline';
```

**Comment by pirate** [comment]
Yeah we don't support no-js mode for the UI. I don't have time to implement that.

**Comment by satoshinotdead** [comment]
That should be appreciated by a vast number of privacy advocates and data hoarders alike (!)
