### ISSUE TITLE
Question: Small backup just of URLs / Index

### ISSUE THREAD

**Issue by turian** [ArchiveBox/ArchiveBox#1013]
I want to create a small backup *just* of URLs, time added, and maybe other index / metadata.

I don't want to backup the whole media archives + HTML etc.

What file(s) should I backup? 

```
ArchiveBox.conf
index.sqlite3
index.sqlite3-shm
index.sqlite3-wal
```

Is that correct?

**Comment by pirate** [comment]
Yes those alone are fine. If you want you can also save more detailed per-snapshot metadata by backing up `archive/*/index.json`.
