### ISSUE TITLE
Installed using Docker-compose.yml file with STACK deployment, no able to configure users

### ISSUE THREAD

**Issue by tessierp** [ArchiveBox/ArchiveBox#1015]
Hi,

So I can't find the default admin password in the documentation and tried to login to the archivebox container and every time I tried to run "archivebox manage createuser xxxxx" I get a message saying "Cannot run as root". How am I supposed to login as admin? How can I create a user if it doesn't exist? Any solution using the environment variables perhaps?

**Comment by tessierp** [comment]
Actually managed to login as Archivebox user and was able to run the createsuperuser command.

**Comment by pirate** [comment]
Also see https://github.com/ArchiveBox/ArchiveBox/issues/734

**Comment by 0xspeedrunner** [comment]
I'm running into the same issue using docker compose and before I go down the temp fix provided by pirate, @tessierp could you share how you managed to do it?

**Comment by tessierp** [comment]
@0xspeedrunner It has been a while since I have done this barely had the chance to work on archivebox since August. If I have time I'll look into this. I looked at issue #734 mentioned by @pirate where someone has a procedure to insert a user in the DB. Hopefully that helps you.

**Comment by pirate** [comment]
The procedure is fully documented in the wiki now @0xspeedrunner @tessierp https://github.com/ArchiveBox/ArchiveBox/wiki/Upgrading-or-Merging-Archives#modify-the-archivebox-sqlite3-db-directly
