### ISSUE TITLE
Limit wiki edit permissions

### ISSUE THREAD

**Issue by antiops** [ArchiveBox/ArchiveBox#1038]
Noticed some sus links in the wiki while going through the history, an IP logger and some zip files that probably got removed by GitHub. I reverted the edits that I found to whatever they used to be, they only started to pop up a couple months ago on those 2 pages.

Restricting editing to collaborators should probably be enabled so the pages cant be edited/created/deleted by anyone.

![1](https://user-images.githubusercontent.com/22041463/196993530-cc760542-55d8-45fa-95db-d5595b8137d3.png)
![2](https://user-images.githubusercontent.com/22041463/196993520-196ddfd5-a98b-405c-becf-855ae44dc31d.png)
![3](https://user-images.githubusercontent.com/22041463/196993533-2103abff-85f1-4746-87ed-d3551e0efb4b.png)

**Comment by pirate** [comment]
Thank you so much for alerting me of this! I just changed the edit permissions.

Sad to see they were being abuse for malware links, it makes sense but didn't think to check for this myself.

I'd like to send you a $50 bounty for discovering this. Whats your preferred method? I can send with Venmo/Zelle/ETH/BTC/XMR/USDC

**Comment by antiops** [comment]
I'd love it if you could donate it to Archive.org, it'd be put to much better use than in my pocket :bowtie:
