### ISSUE TITLE
ARCHIVE_DIR and SOURCES_DIR

### ISSUE THREAD

**Issue by lx30011** [ArchiveBox/ArchiveBox#1039]
Hello, I would like to use archivebox and store all the data to a network share.
I thought about running archivebox directly on the network share mount but this isn't a good idea because of the sqlite database. So I want to store everything apart from the sqlite database on the network share. The sqlite database I'm going to fetch periodically from my network share.
Is there any way to edit ARCHIVE_DIR and SOURCES_DIR to point to my mounted network share?
Also do these two folders cover all the important data apart apart from the sqlite database or is there anything else I missed?
Sorry if my question is stupid. I find it difficult to make sense of archivebox.

**Comment by lx30011** [comment]
I forgot about symlinks. That works for me.

**Comment by Dontkickmi22** [comment]
> I forgot about symlinks. That works for me.

Well, I got a really stupid question for ya, hope you don't mind.
Same boat here, but no luck with symlink. Care to share how you did it?

Below is what I got, gives me FileExistsError: [Errno 17] File exists: '/data/archive'

/media/archivebox $ ls -al
..
lrwxrwxrwx   1 root   root       27 Mar 22 18:44 archive -> /mnt/nas/archivebox/archive
..


Really appreciated any help

**Comment by Dontkickmi22** [comment]
Really appreciated.  
...
ls -lah /mnt/nas/archivebox/archive
total 0
drwxrwxrwx 1 pihole spi 31K Mar 22 16:02 .
drwxrwxrwx 1 pihole spi 130 Mar 22 16:26 ..
drwxrwxrwx 1 pihole spi 222 Mar 10 00:57 1660999365.529939
drwxrwxrwx 1 pihole spi 222 Mar 10 00:58 1660999611.146419
drwxrwxrwx 1 pihole spi 222 Mar 10 00:56 1660999991.738821
drwxrwxrwx 1 pihole spi 336 Mar 10 00:58 1661000584.276981
drwxrwxrwx 1 pihole spi 264 Mar 10 00:58 1661000606.944824
drwxrwxrwx 1 pihole spi 210 Mar 21 03:41 1679341232.699986
drwxrwxrwx 1 pihole spi 210 Mar 21 22:49 1679409159.896055
drwxrwxrwx 1 pihole spi 210 Mar 21 23:10 1679410992.427023
drwxrwxrwx 1 pihole spi 210 Mar 22 01:12 1679417269.721868
drwxrwxrwx 1 pihole spi 210 Mar 22 02:19 1679421325.23538
drwxrwxrwx 1 pihole spi 210 Mar 22 11:47 1679456478.232173
drwxrwxrwx 1 pihole spi 210 Mar 22 12:04 1679457288.47401
drwxrwxrwx 1 pihole spi 216 Mar 22 15:51 1679471441.249936
drwxrwxrwx 1 pihole spi 210 Mar 22 16:22 1679472167.168776
drwxrwxrwx 1 pihole spi 18K Mar 10 00:50 @eaDir
...
