### ISSUE TITLE
How to resolve "extractor timed out  after 60s" error, if possible?

### ISSUE THREAD

**Issue by j-ar7** [ArchiveBox/ArchiveBox#1045]
OS is MacOS, archivebox installed using pip, `archivebox setup` has been done on this particular archivebox instance. 
Getting "Extractor timed out after 60s." on some urls' pdf, single-file, screenshot or readibility extraction. 

![example](https://user-images.githubusercontent.com/112698622/202532011-1b9fc32b-f1dc-4c3a-bd6a-027aff47995b.png)

![info](https://user-images.githubusercontent.com/112698622/202532257-6effe2d4-c386-4b6a-9002-0aa516df3b2d.png)

So how do I resolve this extractor error, if its something thats not dependent on the site itself?

**Comment by pirate** [comment]
Sorry for the late reply, was just reminded by your twitter DM.

Can you try with the latest dev branch: 

```bash
# docker:
docker build -t archivebox:dev https://github.com/ArchiveBox/ArchiveBox.git#dev
docker run -it -v $PWD:/data archivebox:dev init --setup

# bare metal:
pip install 'git+https://github.com/pirate/ArchiveBox@dev'
npm install 'git+https://github.com/ArchiveBox/ArchiveBox.git#dev'
archivebox init --setup
```

https://github.com/ArchiveBox/ArchiveBox#install-and-run-a-specific-github-branch

Extractor timeouts can happen for a variety of reasons, it's hard to diagnose, but the first step is running the command it says under `Runt to see full output:` and read the error messages.

**Comment by pirate** [comment]
Please try on the latest v0.7.2 build, as there are many improvements to extractors and core code that should resolve this.

**Comment by THeK3nger** [comment]
Hello! I stumbled into the same issue on macOS. Running the command for the full log, I get this:

```
[28463:34307:0227/140145.400081:ERROR:trust_store_mac.cc(752)] Error parsing certificate:
ERROR: Failed parsing extensions

[28463:259:0227/140145.422227:ERROR:policy_logger.cc(156)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(161) Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.
247207 bytes written to file output.pdf
```

The two errors (`ERROR:trust_store_mac.cc(752)` and `ERROR:policy_logger.cc(156)`) don't seem to be related to the problem (I have them for every Chromium browser I have installed, and they are not causing problems, I think).

As you can see the PDF is saved correctly. But the headless Chromium never returns, so Archivebox identifies them as an error even if everything is fine.

**Comment by pirate** [comment]
this is unfortunately an upstream bug with Chrome :'(

You can confirm it by running the command manually, and you'll see that it still hangs. Occasionally it's fixed by rebooting, or clearing the chrome data dir (destructive). Uninstalling and re-installing chrome also often fixes it.


All are annoying solutions, I know, but I don't want to implement brittle workaround code just yet because I'm hoping they'll fix it soon on their side.

**Comment by THeK3nger** [comment]
That's what I thought as well (it happens also with other Chromium browsers I have installed). Don't worry. :) I just wanted to notify other people with the same problem. 

(and let's hope it will be fixed upstream!)

**Comment by pirate** [comment]
I confirmed that is indeed an upstream issue an opened a bug report on the Chromium bug tracker: [issues.chromium.org/issues/327583144](https://issues.chromium.org/issues/327583144)

<img width="1410" alt="Screenshot 2024-02-29 at 5 30 24 PM" src="https://github.com/ArchiveBox/ArchiveBox/assets/511499/6c33c2df-c44c-493b-a15c-c8e38b2599b4">

**Comment by pirate** [comment]
This is the existing long-running issue for this Chromium bug: https://github.com/ArchiveBox/ArchiveBox/issues/746

Subscribe to that one instead ^

**Comment by philippludwig** [comment]
I see archiving jobs being aborted at 99.8% because of this. Can't the timeout be increased? 

This is the first and only search result for this error message.
