### ISSUE TITLE
Question: How to access archived pages from Archive.org ?

### ISSUE THREAD

**Issue by nonjenec** [ArchiveBox/ArchiveBox#1049]
currently I have a very complex issues which makes me unable to access my archived pages. this is not an archivebox issue at all.
with that said, I remember i had options set to archive pages to archive.org, How can I access the archived pages from archive.org site? 

edit : one more thing, so the host device had cron job to run a script exactly at midnight to archive pages. this is still going, and likely going until the host device dies or takes all the space left. webpage url is the same so I have to use the hash # workaround.

edit edit : host device are very very far, I use ssh to access archived pages

**Comment by pirate** [comment]
There is no central index off all the pages you've submitted to archive.org other than your archivebox index. But in general you can just search any URL in archive.org and if it's been submitted by yourself or anyone else it should show up.

You can also visit https://web.archive.org/web/https://example.com directly to see if archive.org has snapshots.
