### ISSUE TITLE
Install instruction for GNU Guix

### ISSUE THREAD

**Issue by rakino** [ArchiveBox/ArchiveBox#1050]
[GNU Guix](https://guix.gnu.org/) is GNU's advanced distro and transactional package manager, which is based on Nix's libstore, while written in [GNU Guile](https://www.gnu.org/software/guile/) (GNU's implementation of the Scheme programming language).

GNU Guix is the default package manager of Guix System.

Installation:
`guix install archivebox`

Link (version specific, sadly there's no reliable link to a package at the moment...):
https://guix.gnu.org/en/packages/archivebox-0.6.2/

Link (source code):
https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/web.scm#n8211

Icons could be found here:
https://git.savannah.gnu.org/cgit/guix/guix-artwork.git/tree/

**Comment by rakino** [comment]
Guix has launched a new version of the packages page recently. (<https://packages.guix.gnu.org>)  It's more reasonable and has all the information included in.

<https://packages.guix.gnu.org/packages/archivebox/>

**Comment by pirate** [comment]
https://github.com/ArchiveBox/ArchiveBox/commit/39e3d03c8208c54f83d8d939b48d5511cbe4673e sorry for the delay!
