### ISSUE TITLE
A server error occurred.  Please contact the administrator

### ISSUE THREAD

**Issue by justarmadillo** [ArchiveBox/ArchiveBox#1051]
**Describe the bug**
after inserting url and leave everything in default and click on   Add URLs and archive  button it loads for a few moments then it shows me the message : **A server error occurred.  Please contact the administrator.**
using docker on Windows 11
python 3.11

**Steps to reproduce**
1.add any url
2. start task
3. shows loading for 7-8 seconds

![image](https://user-images.githubusercontent.com/10810222/203142512-a3fe11f0-d469-4396-b867-13a95b12824a.png)

5. black page with text: A server error occurred.  Please contact the administrator.
6. even when I select wget in archive method the same error.

**Screenshots or log output**

![image](https://user-images.githubusercontent.com/10810222/203141905-bb2c520d-81d7-4edf-871c-30cb3c213c67.png)

**ArchiveBox version**
ArchiveBox v0.6.2
Cpython Windows Windows-10-10.0.22000-SP0 AMD64
IN_DOCKER=False DEBUG=False IS_TTY=True TZ=UTC SEARCH_BACKEND_ENGINE=ripgrep

←[01;37m[i] Dependency versions:←[00;00m
←[01;32m √ ←[00;00m ARCHIVEBOX_BINARY     v0.6.2         ←[01;32m valid    ←[00;00m C:\Python\Python38\Scripts\archivebox.exe
←[01;32m √ ←[00;00m PYTHON_BINARY         v3.11.0        ←[01;32m valid    ←[00;00m C:\Python\Python38\python.exe       
←[01;32m √ ←[00;00m DJANGO_BINARY         v3.1.14        ←[01;32m valid    ←[00;00m C:\Python\Python38\Lib\site-packages\django\bin\django-admin.py
←[01;32m √ ←[00;00m CURL_BINARY           v7.83.1        ←[01;32m valid    ←[00;00m C:\Windows\system32\curl.EXE        
←[01;32m √ ←[00;00m WGET_BINARY           v1.21.3        ←[01;32m valid    ←[00;00m C:\Windows\system32\wget.EXE        
←[01;32m √ ←[00;00m NODE_BINARY           v18.12.1       ←[01;32m valid    ←[00;00m D:\Downloads\Programs\nodejs\node.EXE
←[01;31m X ←[00;00m SINGLEFILE_BINARY     ?              ←[01;31m invalid  ←[00;00m single-file                         
←[01;31m X ←[00;00m READABILITY_BINARY    ?              ←[01;31m invalid  ←[00;00m readability-extractor               
←[01;31m X ←[00;00m MERCURY_BINARY        ?              ←[01;31m invalid  ←[00;00m mercury-parser                      
←[01;31m X ←[00;00m GIT_BINARY            ?              ←[01;31m invalid  ←[00;00m git                                 
←[01;32m √ ←[00;00m YOUTUBEDL_BINARY      v2021.12.17    ←[01;32m valid    ←[00;00m C:\Python\Python38\Scripts\youtube-dl.EXE
←[01;33m - ←[00;00m CHROME_BINARY         -              ←[01;33m disabled ←[00;00m                                     
←[01;31m X ←[00;00m RIPGREP_BINARY        ?              ←[01;31m invalid  ←[00;00m rg                                  

←[01;37m[i] Source-code locations:←[00;00m
←[01;32m √ ←[00;00m PACKAGE_DIR           23 files       ←[01;32m valid    ←[00;00m C:\Python\Python38\Lib\site-packages\archivebox
←[01;32m √ ←[00;00m TEMPLATES_DIR         3 files        ←[01;32m valid    ←[00;00m C:\Python\Python38\Lib\site-packages\archivebox\templates
←[01;33m - ←[00;00m CUSTOM_TEMPLATES_DIR  -              ←[01;33m disabled ←[00;00m                                     

←[01;37m[i] Secrets locations:←[00;00m
←[01;33m - ←[00;00m CHROME_USER_DATA_DIR  -              ←[01;33m disabled ←[00;00m                                     
←[01;33m - ←[00;00m COOKIES_FILE          -              ←[01;33m disabled ←[00;00m                                     

←[01;37m[i] Data locations:←[00;00m

←[01;33m[!] Warning: Missing 5 recommended dependencies←[00;00m
    ! SINGLEFILE_BINARY: single-file (unable to detect version)
      ←[01;35mHint:←[00;00m To install all packages automatically run: archivebox setup
            or to disable it and silence this warning: archivebox config --set SAVE_SINGLEFILE=False

    ! READABILITY_BINARY: readability-extractor (unable to detect version)
      ←[01;35mHint:←[00;00m To install all packages automatically run: archivebox setup
            or to disable it and silence this warning: archivebox config --set SAVE_READABILITY=False

    ! MERCURY_BINARY: mercury-parser (unable to detect version)
      ←[01;35mHint:←[00;00m To install all packages automatically run: archivebox setup
            or to disable it and silence this warning: archivebox config --set SAVE_MERCURY=False

    ! GIT_BINARY: git (unable to detect version)
    ! RIPGREP_BINARY: rg (unable to detect version)

**Comment by pirate** [comment]
Im sorry I can't provide support for CyPython/windows environments. There are too many edge cases and unsupported dependencies on windows and I don't have a windows machine myself so it's a lot of work to try to reproduce.

I'll leave the ticket open for a little bit in case anyone else has suggestions, on the meantime I recommend Docker/a Linux VM instead.
