### ISSUE TITLE
Support Request: Failed to installed npm packages

### ISSUE THREAD

**Issue by ghost** [ArchiveBox/ArchiveBox#1057]
I keep getting this error every time I run `archivebox setup` 

 `Installing SINGLEFILE_BINARY, READABILITY_BINARY, MERCURY_BINARY automatically using npm...
←[01;31m[X] Failed to install npm packages: [WinError 2] The system cannot find the file specified←[00;00m
    ←[01;35mHint:←[00;00m Try deleting C:\Users\admin\Downloads\archivebox/node_modules and running it again`

There's no node_modules in the archivebox folder to delete. I've already tried `remove-node-modules` still getting the error.

**Comment by pirate** [comment]
Sorry I don't have the capacity to officially support windows, I'll leave this open for a bit to see if others have any suggestions, but I can only officially recommend using docker or a VM if you run into problems on Windows.

**Comment by hexahigh** [comment]
I got the same error but i got it to work by running "npm install" after i had gotten the error.
