### ISSUE TITLE
Feature Request: Sort the snapshot into categories

### ISSUE THREAD

**Issue by gitwittidbit** [ArchiveBox/ArchiveBox#1061]
- [ ] General question or discussion
 - [x] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves

I think that with a number of snapshots, it will become difficult to find things again. I know one can add tags to snapshots but it is my understanding that snapshots would still all sit on one big heap. So I would love to be able to sort them into different categories.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

Ideally, there would be a folder hierarchy and I would be able to drag and drop snapshots in these folders.

## What hacks or alternative solutions have you tried to solve the problem?

Tags are the closest but for me they are not a good substitute.

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [x] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [x] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue -> not a programmer myself, but I would be happy to help test
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up -> no, with docker compose it was pretty straight forward

**Comment by pirate** [comment]
We may add nested tags in the future but I don't plan on adding folders separately from tags. There is already another issue open for nested tags, I'll link it to this one later.
