### ISSUE TITLE
Add Diskernet to Web-Archiving-Community wiki page

### ISSUE THREAD

**Issue by stevemoser** [ArchiveBox/ArchiveBox#1062]
## Wiki Page URL
https://github.com/ArchiveBox/ArchiveBox/wiki/Web-Archiving-Community

## Suggested Edit
Add https://github.com/crisdosyago/Diskernet

**Comment by pirate** [comment]
Dikernet is actually just 22120 renamed, which was already in the list. I updated the name in the Wiki and the URL to point to the new location.

Side note: I keep his project listed in the interest of fairness but honestly that maintainer was kind of an asshole to me and a few others in the internet archiving community, I'm not a huge fan of them.

He's been unnecessarily antagonistic, vindictive, and petty in every interaction I've had with him. I was originally down to cross-promote 22120/Diskernet more heavily (like I do Archivy/Browsertrix/Webrecorder/SavePage.now) but now I just keep my distance and try to interact with them as little as possible 😿 .
