### ISSUE TITLE
FreeBSD install instructions need a bit of TLC

### ISSUE THREAD

**Issue by mwestza** [ArchiveBox/ArchiveBox#1069]
## Wiki Page URL

https://github.com/ArchiveBox/ArchiveBox/wiki/Install

## Suggested Edit

FreeBSD install instructions need a bit of TLC:

```
pkg install python git wget curl youtube_dl ripgrep py39-pip py39-sqlite3 npm ffmpeg
pkg install chromium
```

**Comment by pirate** [comment]
Done, thanks!

https://github.com/ArchiveBox/ArchiveBox/wiki/Install#freebsd
