### ISSUE TITLE
URL Length seems to be limited to 200 characters

### ISSUE THREAD

**Issue by prgarnett** [ArchiveBox/ArchiveBox#1072]
#### Describe the bug
If you try to edit a snapshot (e.g. if it failed to process fully or needs a title etc) where the original URL is longer than 200 chars the edits are not saved as there is an error saying that the URL is too long.

#### Steps to reproduce
Save a snapshot of a URL of greater than 200 chars, then try to edit it and save the edits. Save will fail with the error.

#### Screenshots or log output

Can do if needed but its fairly easy to reproduce.

#### ArchiveBox version

v0.6.3

**Comment by pirate** [comment]
Merging this issue with: https://github.com/ArchiveBox/ArchiveBox/issues/1107

Subscribe to that one for updates :)
