### ISSUE TITLE
[Multi-arch Request] Docker i386/archivebox

### ISSUE THREAD

**Issue by jnolan7599** [ArchiveBox/ArchiveBox#1078]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves
I would like to ask for a i386 Docker image of ArchiveBox to pull from Docker Hub. More specifically, I'd like to ensure official images as to not fall behind on security updates, refinements, etc. My skill with Docker is near non-existent, however I can handle editing & launching from a docker-compose file. For example I do have i386/postgres:15.1-alpine3.17 up & running although SQLite strikes me as a far more 'portable' solution, especially for backup datasets.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
**Additional context**
The goal of this is to re-purpose a Intel Pentium M that, while quite old, now successfully runs Docker & has 680MB RAM being unused awaiting this web application.

## What hacks or alternative solutions have you tried to solve the problem?
This is beyond my current skill set.

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [x] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [ ] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [ ] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up
 - [x] I'm currently unable to install ArchiveBox

**Comment by pirate** [comment]
Don't have the bandwidth to support it at the moment, sorry. There are a few broken package deps on i386 last time I tried and the release process is already too complicated.

You can always use the manual / package manager installs on i386.
