### ISSUE TITLE
Is there a simple algorithmic way to navigate to a desired web page snapshot located in your archive?

### ISSUE THREAD

**Issue by happening-primal** [ArchiveBox/ArchiveBox#1080]
I've played around with archivebox a few times in the past and I always run into a limitation related to the archive URL.  

As per the documentation, and in reality, the archived URL will look something like this:

   https://archive.example.com/archive/1493350273/en.wikipedia.org/wiki/Dining_philosophers_problem.html

That's great, and you can scroll through your archived web pages and find this, but it not very convenient for actually just browsing through to archived pages.  A method of doing this would be to use the Firefox Add-in Redirector to take all attempts to go to https://en.wikipedia.org/wiki/Dining_philosophers_problem.html and redirect them to https://archive.example.com/archive/1493350273/en.wikipedia.org/wiki/Dining_philosophers_problem.html except....the issue is that you must know the archive number, in above example, 1493350273.

So, to my question as I've done a lot of searching on this topic with no luck.  Is there a 'permalink' to the most recent copy of an archived page such that you can automate the browsing of your archive without needing to know the archive number?

If might look something like these examples below:
    
    https://archive.example.com/archive/mostrecent/en.wikipedia.org/wiki/Dining_philosophers_problem.html
    https://archive.example.com/archive/single/mostrecent/en.wikipedia.org/wiki/Dining_philosophers_problem.html
    https://archive.example.com/pdf/mostrecent/en.wikipedia.org/wiki/Dining_philosophers_problem.html
    https://archive.example.com/readability/mostrecent/en.wikipedia.org/wiki/Dining_philosophers_problem.html

or any other simple algorithmic way to navigate to a desired web page snapshot located in your archive?  Any help much appreciated.

**Comment by pirate** [comment]
ArchiveBox doesn't offer proxy-replaying (aka seamless browsing with automatic redirecting to archived versions for every URL).

pywb's proxy-archiving feature would be a better fit for you than ArchiveBox: https://pywb.readthedocs.io/en/develop/manual/configuring.html#http-s-proxy-mode
