### ISSUE TITLE
Attention: We intend to remove the `archivebox oneshot`  command from ArchiveBox in the next 0.7 release

### ISSUE THREAD

**Issue by pirate** [ArchiveBox/ArchiveBox#1082]
<img width="1748" alt="image" src="https://user-images.githubusercontent.com/511499/211794758-4bfc9ed5-6aa3-409c-b48d-e0e3d8fe13ab.png">

Long long ago before `archivebox` was a Django app, it used to be a one-shot bash script called `archive-pocket-stream.sh`. When we moved to the Django system `archivebox oneshot` was provided as an escape hatch for users that did not like being forced to create collections and manage data directories all of a sudden. It allows the new fancy django archivebox to run in "oneshot" mode without creating a main index file, data dir, etc. and only outputting the results of one snapshot into PWD.

As you might imagine, it required tremendous haxx to run the new Django archivebox without a db file in this way, including instantiating a fake sqlite3 db in memory, filesystem write filtering, etc. and it's imposing a large maintenance burden by making it hard to refactor other subsystems.

Now that we have solidly been on Django for several major versions, I think we can safely retire `archivebox oneshot` ?

Iif anyone is using it, speak up now and make a case for keeping it 😅 🤠👋

**Comment by ianrobertsFF** [comment]
This is my entire use case, I need to be able to do single page snapshots on a daily basis, and have no need for any of the other functionality of ArchiveBox, I'll be running it CLI only, and using another tool to trigger the daily snapshots of the pages, and piping them into specific directories.

Without the ability to create multiple snapshots of the same URL in your normal use cases, this is the only way I can achieve it.

**Comment by pirate** [comment]
Good to know! Would your needs be satisfied if we add better native support for multiple snapshots in archivebox instead of keeping this older feature? @ianrobertsFF

**Comment by jvican** [comment]
I'm also using this. I think it makes a lot of sense to keep a command like oneshot around because it's fairly self-contained, and it aligns well with the UNIX philosophy. It does one thing and it does it well, without the need for `archive init` and the use of the rest of the software. Please don't take it away.

**Comment by ianrobertsFF** [comment]
My needs would be satisfied by multiple snapshots, although I still wouldn't be using any of the functionality that oneshot doesn't currently use, so it wouldn't be a better workflow, as oneshot does exactly what I need. 

However assuming I can continue to take on-demand snapshots with the native support for multiple snapshots, this would be acceptable to me.

**Comment by jwmh** [comment]
Q:
Would it be possible to fork this off into its own separate project/repo?
Would it even be desireable?

**Comment by pirate** [comment]
Ok I've decided to keep `oneshot` because it ties in nicely with a refactor I'm down to breakdown archivebox jobs into individually runnable subcommands.

My plan is to split it into two commands:

#### `archivebox snapshot`

Can be run to snapshot an individual URL into the current directory (runs all extractors by default).

```bash
archivebox snapshot --methods=all 'https://example.com/somepage.html'
```

This works the same way as `oneshot` does now, and I'll alias `oneshot` to the new command so we don't break backwards compatibility.

#### `archivebox extract`

This runs an individual extractor method and outputs into the current directory.

```bash
archivebox extract --method=PDF --method-args-here 'https://example.com/somepage.html'
```

`archivebox snapshot` will work by internally by calling `archivebox extract --method=...` for each method.

---

Please subscribe to this issue for updates: https://github.com/ArchiveBox/ArchiveBox/issues/1289
