### ISSUE TITLE
Feature Request: ArchiveBox on Cloudron - One Click Deployment

### ISSUE THREAD

**Issue by OrcVole** [ArchiveBox/ArchiveBox#1083]
## Type 

 - [ ] General question or discussion
 - [x] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves

Deployment of ArchiveBox is beyond the skills of most people. Making ArchiveBox available as an application on Cloudron would mean greatly more people could become archivers.

More ArchiveBox instances would relieve the server load on those running instances

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

The hard work is largely completed: there is an ArchiveBox Docker image already. There is a live demo on the main Cloudron website where you can see how the application would work: https://cloudron.io
There is also a tutorial on how to properly package the Archive Docker here, and people who value ArchiveBox needs to follow the tutorial and join the ArchiveBox discussion thread here:
Tutorial:
https://forum.cloudron.io/topic/2843/read-first-before-starting-to-package-an-app
ArchiveBox Discussion
https://forum.cloudron.io/topic/1669/archivebox-personal-internet-archive/19

## What hacks or alternative solutions have you tried to solve the problem?
self installing

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [x] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [ ] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [x] I've had a lot of difficulty getting ArchiveBox set up

![brave_dsU6KRAlX6](https://user-images.githubusercontent.com/68787520/212371845-69d04b8b-8850-4aec-bd42-0cd124753692.jpg)

**Comment by pirate** [comment]
I'm not going to write an adapter to a paid platform for free but if they want to sponsor development or submit a PR I can review it.

**Comment by pirate** [comment]
Someone else did it: https://www.cloudron.io/store/io.archivebox.cloudronapp.html
