### ISSUE TITLE
Feature Request: `FOOTER_INFO` mutiline text / arbitrary-html support 

### ISSUE THREAD

**Issue by green1052** [ArchiveBox/ArchiveBox#1088]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [X] Request modification of existing behavior or design

## What is the problem that your feature request solves

FOOTER_INFO  config support muti line

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [X] It would be nice to have eventually

---

 - [ ] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [ ] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
For now I recommend people take advantage of the `CUSTOM_TEMPLATES_DIR` config option. That option allows you to override arbitrary HTML inside the templates, and you can easily add any HTML you need to the footer.

https://github.com/ArchiveBox/ArchiveBox/wiki/Configuration#custom_templates_dir

If you run `archivebox version` you can see the directory containing the default templates:
```bash
[i] Source-code locations:
 √  PACKAGE_DIR           25 files        valid     /Users/squash/Documents/opt/ArchiveBox/archivebox
 √  TEMPLATES_DIR         4 files         valid     /Users/squash/Documents/opt/ArchiveBox/archivebox/templates
 ```
 
 You can create a new dir containing whatever templates you want to override from `TEMPLATES_DIR`, then set `CUSTOM_TEMPLATES_DIR` to point to it and ArchiveBox will load your custom HTML in favor of the defaults.
