### ISSUE TITLE
Question: Help to change output directory

### ISSUE THREAD

**Issue by Jubelsalami** [ArchiveBox/ArchiveBox#1089]
I'm running the docker on Unraid, and I want to move the archive to a different directory. 

I have tried to set the "OUTPUT_DIR=/archive" in the config, but this created a new install in that directory.
Is it possible to have the archive folder on another share or disk? If so, how?

**Comment by pirate** [comment]
This is not currently supported, the archivebox command must be run from inside the archivebox data directory.
