### ISSUE TITLE
Upgrade is spelt wrong on the github readme

### ISSUE THREAD

**Issue by fire** [ArchiveBox/ArchiveBox#1090]
#### Describe the bug

Upgrade is spelt wrong, but you said not to make a pr. Please run a spellchecker over the entire repo.

https://github.com/fire/ArchiveBox/tree/patch-1

#### ArchiveBox version

https://github.com/ArchiveBox/ArchiveBox/commit/5408028265b53e57eb343d309998e2fdf4dca45e 

This is describing the ArchiveBox github page.

**Comment by pirate** [comment]
https://github.com/ArchiveBox/ArchiveBox/commit/992a02f87b30051b8e14c644ac0974db42efd30e
