### ISSUE TITLE
Feature Request: Title customization

### ISSUE THREAD

**Issue by EvacuateJuly** [ArchiveBox/ArchiveBox#1095]
## Type 

 - [ ] General question or discussion
 - [x] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves

Often (17 / most recent 80 of my snapshots) the title ArchiveBox receives is somewhat useless. Sometimes the problem is papers being titled as just the URL, or CloudFlare blocking download titles even though SingleFile still works, or not being able to download the title at all and being stuck with "Pending..." despite Wget working.
## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

I'd like the ability to edit the title of an existing download, including through the web panel, and have an option on the Add page of the web panel and through `archivebox add` to customize the title.

This shouldn't conflict with #963.
## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [x] It would be nice to have eventually

---

 - [ ] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
You already can, just go to the snapshot admin page and change the title field, scroll down and click save.

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/511499/217731642-68491f75-91f0-49f2-9a82-7cbf811b4fc5.png">
