### ISSUE TITLE
How to save Instagram Profiles?

### ISSUE THREAD

**Issue by Niriuqq** [ArchiveBox/ArchiveBox#1098]
Hey 
Can you back up Instagram profiles with ArchiveBox?
When I add them normally there is always a message that I have to accept cookies but I can't click on it.
Thanks for Help.

**Comment by pirate** [comment]
You need to log in to Instagram in a Chrome instance and point ArchiveBox to that chrome profile, instructions here: https://github.com/ArchiveBox/ArchiveBox/wiki/Chromium-Install#setting-up-a-chromium-user-profile
