### ISSUE TITLE
Question: trouble creating admin user via CLI

### ISSUE THREAD

**Issue by p6002** [ArchiveBox/ArchiveBox#1099]
Cannot create admin account, after deploying container through portainer.
Command: `archivebox manage createsuperuser`
Not work, because after loging to container, root commands are blocked by developer for some reason (?)
Any environment need to be added to compose file?

**Comment by pirate** [comment]
Please follow the ticket instructions, they're there for a reason. I need the full verbatim output of `archivebox version` to help, and either a screenshot or verbatim log output from the command you tried to run in order to help.

**Comment by p6002** [comment]
Ok i fix it using this solution:
https://github.com/ArchiveBox/ArchiveBox/issues/734
