### ISSUE TITLE
ArchiveBox Docker image is very out-of-date

### ISSUE THREAD

**Issue by sergeyvolk** [ArchiveBox/ArchiveBox#1109]
I just installed ArchiveBox today. Since https://archivebox.io/#quickstart recommended installing via Docker I went with that.
I've installed Docker on my Ubuntu 22.10 and ran ArchiveBox install script (curl -sSL 'https://get.archivebox.io' | sh). The installation was successful, but then I tried archiving a few URLs and noticed that media downloads failed for all YouTube URLs. I looked a bit into it, and was surprised to see that the Docker image pulled by the installation script is ~2 years old, it has youtube-dl v2021.04.26, which doesn't work anymore.
Is Docker install still the recommended way to set up ArchiveBox? If it is, then perhaps Docker images need to be updated on a regular basis?

**Comment by sergeyvolk** [comment]
Btw, one interesting thing that I've just noticed is that Docker Desktop shows two archivebox images. The first one is ~2 years old, has Tag='master' and hash value a8da1f0258b3f7d8f01948a458ba3f9e8a71a85a8763a2a144413da8e55bb519. The second one was created 10 months ago, has Tag='latest' and hash d74dfbfd46b85f7e1b503606fb30b2c2e7d8093285046b48b602080fc303d276. For some reason the first image (the one that's ~2 years old) is being used by the archivebox instance on my machine. I'm not sure why the installer script set things up like that. But even if I find a way to switch to the docker image marked 'latest' - if it really is 10 months old, I guess things might be a little better, but I think youtube-dl will still be out of date.

**Comment by sergeyvolk** [comment]
One more note: I installed Docker Desktop on my Ubuntu, so I believe the ArchiveBox installation script used the docker-compose path.

**Comment by pirate** [comment]
This is correct, the official stable `master` release has not been updated in a while, however work has continued in the `dev` branch over the last year, I just haven't had a time to fully test everything to roll an official release so I've been pointing users to the unstable branch gradually to make sure it's stable. If you'd like to try the unstable dev branch with the latest `youtube-dl` and `yt-dlp` versions and other fixes, you can set your image to `archivebox/archivebox:dev` https://github.com/ArchiveBox/ArchiveBox#install-and-run-a-specific-github-branch.

**Comment by neingeist** [comment]
I've hit this too, and used `latest` for my first tests (which seems only a few commits ahead of the latest versioned tag).

I've seen the "latest" Docker tag mostly used as the latest stable release, while "edge" or "master"/"main" is common for the dev or "master"/"main" branches.

**Comment by neingeist** [comment]
(`dev` works much better)

**Comment by hbd** [comment]
Same here - ran into an issue with youtube-dl in `master` (default when setting up with the docker-compose or curl methods), realized the image tagged master in Dockerhub is very old, updated to `dev` and it's working beautifully. @pirate how can we help test?

**Comment by madobet** [comment]
Just left some comments: not only the docker version, but also the bare metal version. I've checked the "auto" install script and PPA user repo, which was still using Ubuntu 20.04 and the other one updated at 2021, makes the script neither "auto" nor "easy" :P

**Comment by pirate** [comment]
PPA was discontinued a while ago. Most recent version is on pip or via github dev branch for the last beta.

**Comment by madobet** [comment]
> PPA was discontinued a while ago. Most recent version is on pip or via github dev branch for the last beta.

Thanks, I will try it :-)

**Comment by pirate** [comment]
Also try Browsertrix-crawler, it's a good alternative
