### ISSUE TITLE
Question: Does ArchiveBox still crash if alot of stuff is saved? Saw video form 3 years ago.

### ISSUE THREAD

**Issue by yellowbikewithbluehandles** [ArchiveBox/ArchiveBox#1113]
Hello I was looking up more info on ArchiveBox as a alternative to wallabag because I cannot get it working but the only video I could find was from 3 years ago and in one part of the video Nick says that ArchiveBox could crash the computer because I guess there was alot of stuff saved? Has that been fixed yet? 

If there is a certain amount of saved data that crashes the computer still? Is this a resource heavy program?

**Comment by pirate** [comment]
What video? url plz

**Comment by yellowbikewithbluehandles** [comment]
https://youtu.be/7eoz_EU6-wQ?t=1243
Sorry I forgot to add that to the post and I love your hair.

**Comment by pirate** [comment]
oh yeah that's ancient, I fixed that problem long ago. that was before we even used a database, it was just text files. It can handle 100k+ URLs now but haven't tested too much higher than that yet.

and thanks!
