### ISSUE TITLE
Question: Multiple questions, I cannot type a password in to set up archivebox in the setup for one and general questions about the program itself.

### ISSUE THREAD

**Issue by yellowbikewithbluehandles** [ArchiveBox/ArchiveBox#1116]
Hello pirate, I am writing to you today with some questions and concerns regarding ArchiveBox. I want to start by apologizing for my lack of computer literacy. I have been trying to set up ArchiveBox on my Windows PC for many days now, and despite my best efforts, I have been struggling with the process.

I followed the instructions on the website and downloaded Docker Desktop. However, I encountered some difficulty when trying to create a directory using the command "mkdir ~/archivebox" and changing the directory using "cd ~/archivebox". I later found out that these commands are typically used in Linux and MacOS systems. As a result, I used "mkdir archivebox" and "cd archivebox" separately instead.

After creating the directory, I ran the command "curl -O 'https://raw.githubusercontent.com/ArchiveBox/ArchiveBox/master/docker-compose.yml'" as instructed on the website. Following this, I ran the "initial setup" command, and the message “creating new admin user for the Web UI” came up.

I am confused about two things. Firstly, I left the username empty, but when I got to the “password” part, I cannot type anything to set up any password, it physically won't let me type into the command prompt. I even tried to keep it empty by just pressing enter, but it would not allow a blank password either, so I cannot put in a password and cannot have no password. Secondly, why are these username, password, and email needed if this program will be entirely local?

My specific use case is that my internet constantly goes out so when I need to read something that I use to reference to write I cannot reach the site or a news article gets removed eventually making it inaccessible. Also this is more of sentimental one where there were articles about my brothers achievements that I no longer can reach because the websites went down and that felt like losing a piece of me and that's why even if this is so hard for me to understand I want to do everything I can to get it working because I never want to lose something like that again and just believe a website will stay up forever or that a article will stay up forever.

Another thing I am concerned about is whether I can still use ArchiveBox if you stop maintaining it in a decade from now for example. All this command prompt stuff is so complicated for me, and I am willing to try to understand, but I have already spent a couple of weeks even before finding Archivebox trying to understand this stuff and doing nothing else after work. I feel like every time I look something up, I am at a dead end, and I am scared that if it stops being maintained, I wouldn’t be able to keep using it or export the archives. If this program is stopped being maintained, will I still be able to use it offline forever, or can I transfer all the web pages to something else? How could this be done?

Last but not least I am worried about whether others can connect to my computer and cause vulnerabilities or security issues through this. I am just confused by the fact that there is an ID and password, along with a public server option. So, I am not sure how to make sure I am not causing vulnerabilities or security issues and just keep purely local.

I apologize if these questions seem basic or repetitive, but I have tried my best to understand and research before asking you for help. I would appreciate any guidance or assistance you can provide.

Thank you for your time and assistance.

**Comment by pirate** [comment]
> My specific use case is that my internet constantly goes out so when I need to read something that I use to reference to write I cannot reach the site or a news article gets removed eventually making it inaccessible.

Given this need and the difficulty of running Dockerized archivebox on Windows, I honestly think it's going to me more trouble than it's worth for you. We really only officially support Linux and macOS, Windows is a whole different beast that requires a lot more manual intervention / specialized knowledge.

Instead I recommend [Singlefile](https://chrome.google.com/webstore/detail/singlefile/mpiodijhokgodhhofbcjdecpffjipkle?hl=en), which produces pure html files as output that you can download and manage using your filesystem and normal Windows file explorer search, folders, etc.

I'll still come back to this when I have more time this week and answer all these questions thoroughly though. They're good questions and it's worth answering them for posterity even if you end up using a different solution.

**Comment by yellowbikewithbluehandles** [comment]
Hey Pirate, I thank you for kindness and empathy of new users and everyone else here for even making this amazing tool. I just recently got Archivebox up and running and am slowly learning more about it.

**Comment by pirate** [comment]
clsoing for now, let me know if you need any further help :)
