### ISSUE TITLE
Publish Docker images elsewhere than Docker Hub

### ISSUE THREAD

**Issue by laurentlbm** [ArchiveBox/ArchiveBox#1121]
It seems that [organisations will be removed from Docker Hub unless they have a paid plan](https://news.ycombinator.com/item?id=35166317). If ArchiveBox is impacted, then all the Docker images will be deleted and a lot of us will be affected. 

Can you publish the images elsewhere? Popular options are GitHub's repository ([ghcr.io](https://www.ghcr.io)) and [quay.io](https://www.quay.io).

**Comment by pirate** [comment]
ArchiveBox got immediately accepted into their Sponsored OSS program, so we are not impacted.
