### ISSUE TITLE
Feature Request: Explicitly specify --headless=new

### ISSUE THREAD

**Issue by fa0311** [ArchiveBox/ArchiveBox#1122]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves

Resolve the problem of unstable headless mode in the current chromium v111.
For example, it can solve the problem of `RESOLUTION` (`--window-size`) not working.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

Change the argument given to chromium to `--headless=new`

## Note
```sh
$ /usr/bin/chromium-browser --version
Chromium 111.0.5563.64 snap
```

| Command | Img |
| --- | --- |
| `/usr/bin/chromium-browser --headless --timeout=2000 --screenshot --window-size=1440,2000 https://github.com/ArchiveBox/` | ![screenshot1](https://user-images.githubusercontent.com/34892635/225538544-40403f7f-216e-4fd4-9ddd-fa2c60d384a6.png) |
| `/usr/bin/chromium-browser --headless=new --timeout=2000 --screenshot --window-size=1440,2000 https://github.com/ArchiveBox/` | ![screenshot](https://user-images.githubusercontent.com/34892635/225538553-6f8607cf-cd9a-408d-9efa-75022462fff9.png) |

---

 - [x] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) to fix this issue

**Comment by pirate** [comment]
Want to open a PR so you get the credit 😉 ?  I'm also happy to do it
