### ISSUE TITLE
Is archiving sites behind a login working or not ?

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [ArchiveBox/ArchiveBox#1127]
Hi,

I'm needing to archive a site behind Oauth2 authentication - https://learningspace.falmouth.ac.uk/course/view.php?id=6885

I have followed the guides in great detail using a local copy of Google Chrome (I'm not using docker) on MacOS. I also tried Chromium. Archivebox shows the correct setup with correct Chrome user directory. However the links above always shows the login page.

I suspect what is happening is that Chrome/Chromium is always revealing itself as a bot/headless and Oauth2 and goodness knows what other security measures on that site detects that and treats the connection as a new unlogged in client EVEN if the login credentials are valid and available.

Would really like to get to the bottom of this.

**Comment by pirate** [comment]
can you try running `chromium --headless=new ... user data dir args ... --screenshot 'https://learningspace.falmouth.ac.uk/course/view.php?id=6885'` directly in CLI, the latest chromium release has a new headless mode that supposedly hides from bot detection better.

**Comment by pirate** [comment]
closing for now but comment back if you still need help
