### ISSUE TITLE
ArchiveBox bumps the filesystem creation/modification timestamps of archive folders unnecessarily on every run

### ISSUE THREAD

**Issue by H6pOJTyp** [ArchiveBox/ArchiveBox#1130]
Hi,
my backup scripts re-scan every file under archive/ every time.
It seems that archivebox somehow changes the ctime recursively on every
archived piece when it adds a new one. I haven't spotted where
in the code this happens, and it's not a big issue, but it would
be nice if the timestamps reflected the actual creation/modification 
(of filesystem metadata in that case).

**Comment by pirate** [comment]
Can you post the full output of `archivebox version` and `archivebox config --get OUTPUT_PERMISSIONS`. Docker chown/chmod's the `archive/` folder on startup if it detects unexpected permissions because macOS and Linux Docker often bodge the permissions of docker volume mounts in weird ways.

**Comment by H6pOJTyp** [comment]
The output

    ArchiveBox v0.6.2
    Cpython OpenBSD OpenBSD-7.2-amd64-64bit-ELF amd64
    IN_DOCKER=False DEBUG=False IS_TTY=False TZ=UTC SEARCH_BACKEND_ENGINE=ripgrep
            
    [i] Dependency versions:
     √  ARCHIVEBOX_BINARY     v0.6.2          valid     bin/archivebox                                                              
     √  PYTHON_BINARY         v3.9.16         valid     /home/_archivebox/bin/python3.9                                             
     √  DJANGO_BINARY         v3.1.14         valid     /home/_archivebox/lib/python3.9/site-packages/django/bin/django-admin.py    
     √  CURL_BINARY           v7.86.0         valid     /usr/local/bin/curl                                                         
     √  WGET_BINARY           v1.21.3         valid     /usr/local/bin/wget                                                         
     -  NODE_BINARY           -               disabled  node                                                                        
     -  SINGLEFILE_BINARY     -               disabled  single-file                                                                 
     -  READABILITY_BINARY    -               disabled  readability-extractor                                                       
     -  MERCURY_BINARY        -               disabled  mercury-parser                                                              
     √  GIT_BINARY            v2.37.3         valid     /usr/local/bin/git                                                          
     -  YOUTUBEDL_BINARY      -               disabled  /home/_archivebox/bin/youtube-dl                                            
     √  CHROME_BINARY         v2022.04        valid     /usr/local/bin/iridium                                                      
     -  RIPGREP_BINARY        -               disabled  /usr/local/bin/rg 
     [i] Source-code locations:
     √  PACKAGE_DIR           23 files        valid     /home/_archivebox/lib/python3.9/site-packages/archivebox                    
     √  TEMPLATES_DIR         3 files         valid     /home/_archivebox/lib/python3.9/site-packages/archivebox/templates          
     -  CUSTOM_TEMPLATES_DIR  -               disabled                                                                              
    
    [i] Secrets locations:
     -  CHROME_USER_DATA_DIR  -               disabled                                                                              
     -  COOKIES_FILE          -               disabled                                                                              
    
    [i] Data locations:
     √  OUTPUT_DIR            5 files         valid     /home/_archivebox/archive                                                   
     √  SOURCES_DIR           527 files       valid     ./sources                                                                   
     √  LOGS_DIR              1 files         valid     ./logs                                                                      
     √  ARCHIVE_DIR           466 files       valid     ./archive                                                                   
     √  CONFIG_FILE           563.0 Bytes     valid     ./ArchiveBox.conf                                                           
     √  SQL_INDEX             3.8 MB          valid     ./index.sqlite3     
  
    OUTPUT_PERMISSIONS=755

**Comment by pirate** [comment]
I removed the recursive chown on startup and replaced it with a warning, so this should be fixed: https://github.com/ArchiveBox/ArchiveBox/commit/4f655fc4a1fc21759fe21f13b354d940ca53b4a2
