### ISSUE TITLE
pypi version bump

### ISSUE THREAD

**Issue by turian** [ArchiveBox/ArchiveBox#1132]
Given recent update and merges, could you push a new pypi version?
Even if it's marked as beta, it would be useful to collect feedback

**Comment by pirate** [comment]
Closing this for now as I'm doing a github issue cleanup pass, trust that I'm well aware of the pressure to roll a new PyPI release ;)

The main blocker for pypi is the django version upgrade here: https://github.com/ArchiveBox/ArchiveBox/issues/988

Subscribe to that issue for more granular updates for now
