### ISSUE TITLE
Feature Request: SVG version of ArchiveBox icon?

### ISSUE THREAD

**Issue by loganmarchione** [ArchiveBox/ArchiveBox#1137]
## Type 

 - [x] General question or discussion
 - [ ] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves
Hello there! 👋

I'm the maintainer of [homelab-svg-assets](https://github.com/loganmarchione/homelab-svg-assets) and would like to add the [ArchiveBox icon](https://github.com/ArchiveBox/ArchiveBox/blob/dev/archivebox/templates/static/archive.png) to my project. However, I didn't see any brand guidelines or a vector (SVG) version of the icon. Could you please provide one or both of these?

Thanks, and keep up the good work!

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
N/A

## What hacks or alternative solutions have you tried to solve the problem?
N/A

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [X] It would be nice to have eventually

---

 - [ ] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
Unfortunately I don't have an SVG original, I lost the vector file a long time ago.

Maybe you can use an online PNG -> SVG conversion tool? The SVG may not be as clean as a handmade one but it's better than nothing.

**Comment by loganmarchione** [comment]
Will do, thanks!
