### ISSUE TITLE
Question: How can I archive full-resolution linked PNGs, JPGs, etc. within a page to the same snapshot?

### ISSUE THREAD

**Issue by hadecake** [ArchiveBox/ArchiveBox#1156]
A site I am trying to snapshot has a lot of direct links to image media I am trying to also capture in full size (not just the thumbnail).
If I add an additional capture layer, it  then grabs the entire page for every page linked at the top. Way too much data. 
Ideally I would like to add more file formats to the "media" capture so that in addition to getting the full images, it stores them all in one snapshot.

Example link: https://boards.4chan.org/out/thread/2577670

Thank you for your assistance

**Comment by pirate** [comment]
You can set the URL_WHITELIST for a single add command so that it only matches image extension URLs on the same domain, and then run it with depth=1. 


```bash
env URL_WHITELIST='https://example.com/.*\.{png,jpg,gif}' archivebox add --depth=1 https://example.com/some/page.html
```
 Something like that should work

**Comment by pirate** [comment]
Archivebox now has a new `gallery-dl` plugin that should automatically download image galleries in full high resolution. Try it out and let me know what you think:

https://archivebox.github.io/abx-plugins/#gallerydl
