### ISSUE TITLE
Bug: ...AttributeError: module 'archivebox' has no attribute 'ArchiveBox'

### ISSUE THREAD

**Issue by me-suzy** [ArchiveBox/ArchiveBox#1163]
I get this error: 

```
Traceback (most recent call last):
  File "D:\archivebox.io 2.py", line 7, in <module>
    archivebox = archivebox.ArchiveBox()
AttributeError: module 'archivebox' has no attribute 'ArchiveBox'
```

after I run thins CODE:

```
import archivebox

# Get the URL of the website page that you want to index.
url = "https://neculaifantanaru.com"

# Create an ArchiveBox object.
archivebox = archivebox.ArchiveBox()

# Index the website page.
archivebox.add(url)

# Save the index.
archivebox.save()
```

**Comment by pirate** [comment]
There is no archivebox.ArchiveBox object, we don't have anything like that in the codebase. where did you find this code snippet?

**Comment by me-suzy** [comment]
I did it myself, but I don't know Python at all. That's why I think it gives an error.

Can you write me the code to help me index the blog?

**Comment by pirate** [comment]
If you enter the `archivebox shell` it'll show you how to use the API. There are also docs on https://docs.ArchiveBox.io

**Comment by pirate** [comment]
Closing as stale
