### ISSUE TITLE
Feature Request: Add ability to choose config options e.g. `YOUTUBEDL_ARGS` for a specific `add` command

### ISSUE THREAD

**Issue by melyux** [ArchiveBox/ArchiveBox#1190]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves

Some feeds, I may only care about archiving with the smallest media sizes. Other ones, I'd want to archive at maximum quality. Currently there's no way to choose different options for different things I add. This is especially important for scheduled pulls, where I can't go in and change the setting before each import and then change it back

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

A new flag for the `add` command (`--config`) that would take a JSON list. These options would be set before this job and then set back to the old ones after the job.

(Would only be a problem if multiple jobs are running at the same time... not sure if that's a possible scenario.)

## What hacks or alternative solutions have you tried to solve the problem?

For manual adding, I can set and unset the config options manually before and after the job, respectively, but with scheduled jobs this is not possible as far as I know (and even if it were, I'd have to by hand keep track of the default options and any options I set in the ENV when unsetting).

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [x] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [x] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [ ] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by melyux** [comment]
I was able to get this working, even in the scheduler crontab! Like this:

```bash
@daily cd /data && YOUTUBEDL_ARGS='["--write-description","--write-info-json","--write-annotations","--write-thumbnail","--no-call-home","--write-sub","--all-subs","--convert-subs=srt","--yes-playlist","--continue","--no-abort-on-error","--ignore-errors","--geo-bypass","--add-metadata","-S","res:480","--write-comments"]' /usr/local/bin/archivebox add --parser json "$(/data/feedparse.py 'https://www.youtube.com/feeds/videos.xml?channel_id=ALSJFDLAFASDFASDF')" >> /data/logs/schedule.log 2>&1 # archivebox_schedule
```

So you just put your configuration variables right after the `&&` and right before the `/usr/local/bin/archivebox` in the command. Another example:

```
@daily cd /data && SAVE_PDF=True SAVE_SCREENSHOT=False /usr/local/bin/archivebox add --parser json "$(/data/feedparse.py 'https://dustinspecker.com/rss.xml')" >> /data/logs/schedule.log 2>&1 # archivebox_schedule
```

Can confirm that the env variables set in one line don't affect the other lines; they only apply to the single `add` command on the line.

Would be nice to have an option for this on the web UI too.

**Comment by pirate** [comment]
This is equivalent to doing `env SOME_VAR="some temp value" archivebox ...` which is documented in a few places, including the wiki Configuration and CLI Usage pages.
