### ISSUE TITLE
Is it possible to add a dark mode

### ISSUE THREAD

**Issue by microdockman** [ArchiveBox/ArchiveBox#1192]
Although the dark reader plugin has been installed, it does not work with ArchiveBox, 

Is there another way to turn down the brightness of the web page

**Comment by microdockman** [comment]
https://github.com/Midnight-Lizard/Midnight-Lizard
I can use this plugin to suit my needs and attach my color Settings
[ArchiveBox.zip](https://github.com/ArchiveBox/ArchiveBox/files/12158394/ArchiveBox.zip)

**Comment by pirate** [comment]
Not you can also customize the CSS and HTML by configuring CUSTOM_TEMPLATES_DIR in archivebox and overriding the default templates and static files.

**Comment by microdockman** [comment]
> Note you can also customize the CSS and HTML by configuring CUSTOM_TEMPLATES_DIR in archivebox and overriding the default templates and static files.

Perhaps there will be more intuitive buttons in the future，

Thank you for your outstanding work  ！！
