### ISSUE TITLE
🗺 Roadmap

### ISSUE THREAD

**Issue by pirate** [ArchiveBox/ArchiveBox#120]
The plans for the next versions ahead can be seen here:

_**[`The Roadmap`](https://github.com/ArchiveBox/ArchiveBox/wiki/Roadmap)**_

Discuss your questions, comments, and concerns about *upcoming* changes and general design direction in this thread.

---

To see how the roadmap has been executed on so far, read these pull requests:

 - ✅ [v0.2.x](https://github.com/ArchiveBox/ArchiveBox/tree/483a3bef9e2b1a7b80611947a3be99b0cf4f9959) 
 - ✅ [v0.3.x](https://github.com/ArchiveBox/ArchiveBox/pull/197)
 - ✅ [v0.4.x](https://github.com/ArchiveBox/ArchiveBox/pull/207)
 - 🛠 [v0.5.x](https://github.com/ArchiveBox/ArchiveBox/pull/552)

*[See all releases...](https://github.com/pirate/archivebox/releases)*

---

**IMPORTANT:** *Please don't work on implementing any of the things in the roadmap without opening an issue to discuss it first, work is already in progress for big parts of these designs, and I may have to reject your PR if it doesn't align with the existing work!*

**Comment by pigmonkey** [comment]
I think it's important to maintain the simplicity of being able to use ArchiveBox as a simple command line tool, which makes me shy away from something like redis. I don't want to have to spin that up on my laptop just to archive my bookmarks. I also wonder if it might be worth considering making dramatiq an optional dependency.

The `depth` flag for crawling will be neat. Further down the line it might be useful if there was a way to store whitelisted domains for each entry to pass to the crawler, similar to wget's `--domain`.

**Comment by pirate** [comment]
Redis, dramatiq, etc could all be optional dependencies used only for the web GUI.

**Comment by mbreedlove** [comment]
@pirate do you have any high-level goals for `archivebox server`? I am interested in helping to define requirements for the front-end web app.

Also, can you document the differences between the `add` and `crawl` commands? It seems like `crawl` operates on a list, while `add` operated on a single URL. If so, I think crawl would be better named `add-list`, or something else that indicates that it behaves like `add` but on a list.

**Comment by pirate** [comment]
@mbreedlove I haven't gotten around to fully spec'ing out a frontend yet, but as inspiration you can look at https://github.com/kanishka-linux/reminiscence which is very similar to what I want ArchiveBox to end up as (with the addition of some federated archive features so people can share resources with eachother).

**Comment by JoshuaMorris** [comment]
It would be awesome to have the option to install from git/select from contributed themes for the frontend. I'm interested in contributing

**Comment by pirate** [comment]
Sure! If you want to contribute some themes right now you're welcome to pr some new files into an `archivebox/templates/<theme-name>` directory.  Then users can select them using the `TEMPLATES_DIR` config option.

**Comment by anarcat** [comment]
it would be really nice if archivebox was a more "normal" python program that is shipped on pypi.org and can be installed with pip or at least `setup.py install`. it would make debian packaging easier (if not just "possible" at all). as things stand now, i'd really like to start using this but i'm hesitant because of the lack of standard installation procedures and maintenance burden...

should i file that as a separate feature request? :)

**Comment by pirate** [comment]
@anarcat this is high on our priority list already, if you notice I mention the pip package in a few places in the roadmap comment at the top.  The planned api is to allow users to simply `pip install archivebox` to get the entire program working right out of the box.

**Comment by anarcat** [comment]
On 2019-03-08 10:25:31, Nick Sweeting wrote:
> @anarcat this is high on our priority list already, if you notice I mention the pip package in a few places in the roadmap comment at the top.  The planned api is to allow users to simply `pip install archivebox` to get the entire program working right out of the box.

Speaking from a Debian packaging perspective, that would make my life
much easier. Do let me know when that's done and I'll see what I can do
about shipping this in Debian. It's too late for the next stable release
but I'm sure it will be trivial to backport...

Packaging progress in Debian is being tracked here:

https://bugs.debian.org/924040

**Comment by pirate** [comment]
WOAH, life-goal of mine to have a package in Debian! Thanks for starting that process, I'm of course happy to help maintain the debian port once the pip package is out.  I'll be sure to keep you posted on the pip packaging process, although it won't be super soon since that new backend has a lot of complexity (expect somewhere in the 4-6 month range).

**Comment by 007** [comment]
Feature request for roadmap: Docker nativity

Please make sure that whatever requirements this project has can be packaged into a container, and that one or two mounts can be provided as a durable backing store.

I regularly break things on my server(s) and need to reinstall either a full OS or some subset. Sometimes it's a bad driver, sometimes I end up with a Python package installed globally because I forgot a `venv`. I've started moving my own works to docker image + data directory to prevent lots of trouble like this. It also helps with multiple versions when I'm developing, since I know with certainty that exactly what is committed is what I'm building - no extra / missing `requirements.txt` or `apt-get install` packages.

**Comment by pirate** [comment]
We don't intend to break docker support by any means, what you described is exactly how I do things on my servers too.  Also in case you're not aware, we already have an existing Docker + ArchiveBox setup documented, you can check it out here: https://github.com/pirate/ArchiveBox/wiki/Docker

**Comment by pirate** [comment]
For everyone who's interested, we're starting the pip packaging process now, and you can follow progress here: https://github.com/pirate/ArchiveBox/issues/177

The good news is that dependencies will be entirely handled with python/pip going forwards. We'll no longer ask users to `apt`/`brew` install anything before runing ArchiveBox, just   
`pip install ArchiveBox` or   
`docker run -d -p 8089:80 archivebox`   
and it's ready to go.

**Comment by anarcat** [comment]
that's awesome @pirate! 

the Docker setup looks pretty good already, but something that might make it better is if automated builds would be enabled in an officially-sanctioned repo on hub.docker.com. Right now, if we [search for archivebox](https://hub.docker.com/search?q=archivebox&type=image) there we find only two unrelated images.

people have a tendency to use those sometimes, maybe even blindly, so it's a good idea to claim a space there when you can.

**Comment by pirate** [comment]
@anarcat done: https://hub.docker.com/r/nikisweeting/archivebox

I'll also go through the process to get it listed on: https://github.com/docker-library/official-images and https://github.com/docker-library/docs with a proper icon and verification of project ownership.

**Comment by anarcat** [comment]
awesome, you're on fire! :)

**Comment by sbrl** [comment]
That's cool, @pirate! How will that work with Chromium though? Won't you have to apt install that?

**Comment by pirate** [comment]
@sbrl `pyppeteer` handles the Chromium bundling automatically, so we won't have to `apt` install it.

<img width="880" alt="image" src="https://user-images.githubusercontent.com/511499/54464738-40b2ed80-474e-11e9-9c71-f5d6955b9a2e.png">

**Comment by sbrl** [comment]
@pirate Wow. Can't wait! :D

**Comment by Marthisdil** [comment]
You may wish to add an option when --depth is used

If I wanted to make an archive of a whole website (for example), including all sub links, etc, and I set depth to either infinite (or some arbitrarily high number like 9999), an option to keep archivebox on the main site's URL only would be awesome (like --stayonsite).

That way, if it comes across a link that takes you off of the site, it doesn't go down that rabbit hole.

Example: echo 'https://www.site.com' | ./archive --depth 9999 --stayonsite      - will archive down to a depth of 9999 on site.com *only* and won't leave the hierarchy.

**Comment by pirate** [comment]
I think we can add that behind a `--mirror` flag, like wget has @Marthisdil.

**Comment by Marthisdil** [comment]
@pirate sounds good!  Thanks for the hard work!  Looking forward to it!

**Comment by pirate** [comment]
FYI for everyone following this issue, I've put some major work in over the last week, and the new Django release is almost done:

 - Final stable pre-django release: https://github.com/pirate/ArchiveBox/pull/197
 - First unstable beta django release: https://github.com/pirate/ArchiveBox/pull/207

The final pre-django release (v0.3.0) is mostly a stability/integrity release that makes sure corrupted indexes are never written to disk, and that the indexes are in the correct format for Django to import.  It has a bunch of bugfixes as well, but no major API/internal schema changes other than the switch from untyped dicts storage to mypy-enforced typed dataclasses.

The Django release (v0.4.0) is the big one that ya'll have been waiting for, it includes an entirely new CLI UX where you `cd` into the data directory and run `archivebox init` to create/import an archive (sort of like `npm init`), instead of using `env OUTPUT_DIR` or defaulting to `./output`.  This release is the one that finally cleans up a lot of the rough edges in the ArchiveBox experience, and moves us over from a brittle, untyped json data storage system to SQLite + optional json/csv exports.

Here's a sneak-peek of some of the new v0.4.0 CLI (this is [already working](https://github.com/pirate/ArchiveBox/pull/207), check out the `django` branch to test it, see [documentation here](https://github.com/pirate/ArchiveBox/wiki/Roadmap)!):
```bash
$ archivebox init
$ archivebox add https://example.com/some/page/to/archive
$ archivebox list --sort=timestamp --filter='.*github.com.*' --csv=timestamp,base_url,is_archived
$ archivebox update --resume=1554263415
```

I encourage you to check out both PRs linked above and leave your feedback as comments.  I'll be pushing the final round of commits and testing both releases over the next 1-2 weeks.

**Comment by sbrl** [comment]
So the upgrade path will be v0.3.0 -> v0.4.0?

**Comment by pirate** [comment]
Yup, you can also just go straight to v0.4.0 from v0.2.4. The middle release is just so I have a nice stable version that’s before the huge Django refactor in case people don’t like Django or we have to go back for some reason.  It’s not a required step for users to install it before the Django release.

**Comment by sbrl** [comment]
Ah, I see! Thanks for the clarification.

I'll test them both out as they are released :-)

**Comment by datakid** [comment]
Checked out the django branch, but I've obv done something wrong - I'm not getting much love:

```
ubuntu@archive-box:~ $ pip3 install archivebox
Collecting archivebox
  Could not find a version that satisfies the requirement archivebox (from versions: )
No matching distribution found for archivebox
ubuntu@archive-box:~ $cd /opt/ArchiveBox_django 
ubuntu@archive-box:/opt/ArchiveBox_django$ bin/archivebox init
Traceback (most recent call last):
  File "bin/archivebox", line 5, in <module>
    from .cli.archivebox import main
ModuleNotFoundError: No module named 'archivebox'
```

Any hints? This is a fresh ubuntu 18.04 installation with nothing else installed.

**Comment by pirate** [comment]
`pip3 install -e .` (it’s not on pypi until it’s released so you have to install from the local for instead of pypi.

**Comment by datakid** [comment]
dataclasses are python 3.7? For ubuntu users with python 3.6, `pip3 install dataclasses`

**Comment by datakid** [comment]
```
    ! Failed to archive link: ValueError: Tried to parse invalid date! 2019-04-07T05:44:39.227520                                       
....
  File "/opt/ArchiveBox_django/archivebox/legacy/util.py", line 152, in typechecked_function
    return func(*args, **kwargs)
  File "/opt/ArchiveBox_django/archivebox/legacy/util.py", line 404, in parse_date
    raise ValueError('Tried to parse invalid date! {}'.format(date))
ValueError: Tried to parse invalid date! 2019-04-07T05:44:39.227520
```

**Comment by pirate** [comment]
Thanks @datakid I added dataclasses as a dependency in `setup.py`, will also investigate fixing that dateparse issue.

**Comment by Marthisdil** [comment]
I like the --depth modifier.  However, how would you use this to mirror a whole site (without the spider moving OFF the site if the site had a link to another site)?

**Comment by pirate** [comment]
@Marthisdil the --mirror option will handle archiving a site without leaving the domain (same as wget's behavior): https://github.com/pirate/ArchiveBox/wiki/Roadmap#--mirror

For everyone else, please read this issue, there are some issues with the ArchiveBox security model around how we deal with executing JS in archived content without allowing it to XSS the entire archive.  This is a pretty major blocker as I'm not comfortable pushing a new version until it's "secure by default" and doesn't risk exposing people's feeds.  I will try to put some time in, but this month is going to be very busy for me so PRs helping with the JS security would be very appreciated! 

For more details on the security and JS issues, see this PR comment: https://github.com/pirate/ArchiveBox/pull/207#issuecomment-494107553
I'll also be updating the readme soon to responsibly disclose the current attack vectors and outline our approach to fixing it (stripping and preventing any JS execution via static archive html and titles and only allowing JS execution via WARC replay).

**Comment by pirate** [comment]
**2019/07 Update:** I haven't forgotten about this, ArchiveBox is still my heart and soul and will remain my primary side-project for the long-term future. I'm just still swamped by my day job and a little daunted by the scope of the security fixes needed to get the next version ready. All JS-stripping / security PRs are extremely welcome in the meantime!  

I'll keep posting updates regularly on status, if you don't want the email notifications you're welcome to mute this issue and check back in a couple months.

**Comment by sbrl** [comment]
I wonder if it's possible to set `Content-Security-Policy` via a HTML `<meta />` tag? If so, then in theory you could disable JS execution by just artificially inserting into the head of scraped pages :thinking:

**Comment by cbcaron15** [comment]
Feature suggestion: a browser extension similar to Archiveror whereby anytime someone visits a page archived by ArchiveBox, links to the archives associated with that URL are fetched and displayed within the extension.

**Comment by sbrl** [comment]
@cbcaron15 sounds like that would do well as a separate issue.

**Comment by kingsleytorlowei** [comment]
any update?

**Comment by pirate** [comment]
Hey all, v0.4 is officially released, check it out:

https://github.com/pirate/ArchiveBox/releases/tag/v0.4.9

We've closed over 30 tickets in this sprint, and made a bunch of major improvements to the CLI experience, data integrity, and web UI!

```bash
pip install archivebox

cd path/to/your/archive/folder

archivebox init
archviebox add 'https://example.com'
archviebox add 'https://getpocket.com/users/USERNAME/feed/all' --depth=1
archivebox status
archivebox server
archivebox help
```

```bash
docker run -v $PWD:/data archivebox init
docker run -v $PWD:/data archivebox add 'https://example.com'
docker run -v $PWD:/data -p 8000 archivebox server
```
