### ISSUE TITLE
Support password protected Pocket feeds

### ISSUE THREAD

**Issue by ghost** [ArchiveBox/ArchiveBox#121]
I would love to have the option to pass my authorization data to Pocket in order to get links from private and password protected feed.
Here is the setting: https://getpocket.com/privacy_controls/
If option is on - Pocket requires authorization, but Bookmark Archiver appears doesn`t support that.

**Comment by pirate** [comment]
You can get pocket links from a private account using their export feature here: https://getpocket.com/export

We wont be able to get the live feed unless we do a full on API integration with Pocket API keys and a backend running somewhere, so I cant promise we'll get around to that anytime soon.

**Comment by mAAdhaTTah** [comment]
Related to #528.

**Comment by pirate** [comment]
This should work now in >=v0.5.4 thanks to @mAAdhaTTah, give it a try @ghost and comment back here if you have any troubles.
