### ISSUE TITLE
Question: ... Is it possible put archivebox in background and close terminal ?

### ISSUE THREAD

**Issue by DaniilKap** [ArchiveBox/ArchiveBox#1217]
im tring to launch  archivebox in background on my server usinge this commands : 
sudo -u archivebox archivebox server 0.0.0.0:8000 & 
disown {{job_id}}

still see output of web server in console like "GET /admin/core/snapshot/ HTTP/1.1" 200 105763"
And if i try to close terminal webserver close as well.

**Comment by pirate** [comment]
You should use an init system like systemd or supervisord to start it. Another alternative is to use a terminal session manager like tmux or screen. As a last resort, if you really must background it (which I don't recommend as it's generally harder to manage long-term), you can use `nohup archivebox ... &`.

**Comment by DaniilKap** [comment]
thx, already solved problem with screen.

**Comment by DaniilKap** [comment]
I ran into 1 more problem, the app will consume all available RAM (6 GB) and slow down to 1-2 links per hour. basically all the memory is occupied by chromium instances. Is it possible to solve this somehow ?

**Comment by pirate** [comment]
That issue should be solved soon, plz follow this or for updates https://github.com/ArchiveBox/ArchiveBox/pull/1219

**Comment by sasasqt** [comment]
add this service to systemd service, and 
```
sudo sytemctl enable archivebox-server.service
```

archivebox-server.service:
```
[Unit]
Description=Archivebox
#After=

[Service]
WorkingDirectory=/**path to where archivebox is init-ed**
ExecStart=/**path to archive box binary**/archivebox server
User=<**username**>

WatchdogSec=4000s
WatchdogSignal=SIGKILL

Restart=always
RestartSec=5

NoNewPrivileges=yes

PrivateDevices=yes

ProtectControlGroups=yes

ProtectKernelModules=yes

ProtectKernelTunables=yes

ProtectHostname=yes

RestrictRealtime=yes

ProtectKernelLogs=yes

ProtectClock=yes

SystemCallArchitectures=native

LockPersonality=yes

[Install]
WantedBy=multi-user.target

```
