### ISSUE TITLE
Feature Request: Update singlefile to latest version (PR available)

### ISSUE THREAD

**Issue by spresse1** [ArchiveBox/ArchiveBox#1220]
## Type 

 - [x] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves
The version of SingleFile currently pulled into ArchiveBox is from 2021 and pinned to a specific git commit. SingleFile has since split into the [SingleFile browser plugin](https://github.com/gildas-lormeau/SingleFile) and [single-file-cli](https://github.com/gildas-lormeau/single-file-cli) and gone to version 1.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

I've prepared a patch which updates NPM dependencies to pull in `single-file-cli` with the latest release. In testing using my own docker container, this was a drop-in replacement. I've used it to archive just under 500 pages at this point (importing from pinboard).

I'll open a PR with the patch just as soon as I'm done with this bug report. It's unfortunately a rewrite of the NPM dependency files, but brings many things more up to date.

## What hacks or alternative solutions have you tried to solve the problem?

None, wrote the fix.

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [x] It would be nice to have eventually

---

 - [x] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by spresse1** [comment]
One question: I don't see an automated way of getting the latest NPM updates into package-lock.json (but do not regularly develop using NPM). Is the intent that this is done manually?

**Comment by pirate** [comment]
Yes, because archival software has slightly different design goals than most software, I don't want to bump dependencies too frequently, lest we create a giant file of archivebox versions that need to be stored for future replaying.
