### ISSUE TITLE
Bug:     for line in hints[:5] if line.strip() TypeError: 'generator' object is not subscriptable

### ISSUE THREAD

**Issue by sasasqt** [ArchiveBox/ArchiveBox#1223]
#### Describe the bug

when error is shorter than 5 lines, [:5] is not well defined
https://github.com/ArchiveBox/ArchiveBox/blob/a837f870af34943ef47cae41c64e241244d701a5/archivebox/logging_util.py#L444
#### ArchiveBox version

```logs
replace this line with the *full*, unshortened output of running `archivebox version`
```

**Comment by pirate** [comment]
fixed, thanks https://github.com/ArchiveBox/ArchiveBox/commit/86366d56402d1b9d79ab400d006b5cdb41ce43dc
