### ISSUE TITLE
Feature Request: change the default YOUTUBEDL_ARGS

### ISSUE THREAD

**Issue by sasasqt** [ArchiveBox/ArchiveBox#1224]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves

1. --max-filesize **aborts** the download after exceeding the size limit, should use  "--format=(bv*+ba/b)[filesize<=800m][filesize_approx<=?800m]/(bv*+ba/b)" instead

2. instead of '--write-sub', '--all-subs', #'--write-auto-subs', use "--write-sub", "--write-auto-sub" instead (remove  '--all-subs'), yt-dlp will only download the sub in default/original language
## How badly do you want this new feature?

 - [x] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [ ] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [ ] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
fixed, thanks https://github.com/ArchiveBox/ArchiveBox/commit/73a5f74d3840284bceaabced9cf99575b8c15d54

**Comment by sasasqt** [comment]
sry, the command i mentioned above works with websites that provide media size in the metadata (e.g. youtube). 
the part
```
(bv*+ba/b)[filesize<=800m][filesize_approx<=?800m]
```
 tries to download the best format less than  (exact/approx.) x MB 

the part
```
/(bv*+ba/b)
```
will download the best format regardless of size if no size information is present.

so _--max-filesize_ arg can be used in conjunction with the _--format_ in case there is no size information is present.

since some media may only provide approximate size in the rare case, sizelimit in _--max-filesize_ needs to be like 1.25x greater than sizelimit in the _--format_

**Comment by pirate** [comment]
I want it to basically download the best available format available that's under ~800mb in size. E.g. if the video is 8k 120fps but only 4 seconds long, download it in original quality, but if it's 360p you can download hours of footage. Each page has an 800mb storage budget and should try to fill it with the highest quality version that fits.
