### ISSUE TITLE
Bug: inconsistent file naming

### ISSUE THREAD

**Issue by sasasqt** [ArchiveBox/ArchiveBox#1227]
#### Describe the bug

https://github.com/ArchiveBox/ArchiveBox/blob/73a5f74d3840284bceaabced9cf99575b8c15d54/archivebox/extractors/dom.py#L40
https://github.com/ArchiveBox/ArchiveBox/blob/73a5f74d3840284bceaabced9cf99575b8c15d54/archivebox/extractors/readability.py#L102
dom.html should be renamed to output.html, or another way around
#### ArchiveBox version

```logs
replace this line with the *full*, unshortened output of running `archivebox version`
```

**Comment by pirate** [comment]
These are different extractor outputs, they must have separate filenames. These names are here for legacy reasons, and may be changed in future versions.
