### ISSUE TITLE
Discussion: django development server in production

### ISSUE THREAD

**Issue by pe1uca** [ArchiveBox/ArchiveBox#1230]
Currently the `archivebox server` command uses django server  
https://github.com/ArchiveBox/ArchiveBox/blob/4950cee3b6a285b54e6b0155f12a4c51de80d10a/archivebox/main.py#L1317  

According to [the documentation](https://docs.djangoproject.com/en/4.2/ref/django-admin/#runserver)  
> DO NOT USE THIS SERVER IN A PRODUCTION SETTING. It has not gone through security audits or performance tests. (And that’s how it’s gonna stay. We’re in the business of making web frameworks, not web servers, so improving this server to be able to handle a production environment is outside the scope of Django.)  

Should archivebox be updated to use a production server?  

Seems gunicorn can directly server django https://docs.gunicorn.org/en/stable/run.html#django

**Comment by pirate** [comment]
I'm closing this for now as there is already an in-progress migration to django channels w/ daphne as the ASGI server, so this issue will be fixed no matter what in upcoming releases as a side effect of that migration.

**Comment by pe1uca** [comment]
Oh, I wasn't able to find it, can you link me the issue/PR so I can see if I can help?

**Comment by fictitious-mario** [comment]
> I'm closing this for now as there is already an in-progress migration to django channels w/ daphne as the ASGI server, so this issue will be fixed no matter what in upcoming releases as a side effect of that migration.





https://tristan-cadre.github.io/marching/
