### ISSUE TITLE
Feature Request: add tags via CLI when adding a URL

### ISSUE THREAD

**Issue by vasilisvg** [ArchiveBox/ArchiveBox#1233]
## Type 

 - [ ] General question or discussion
 - [x] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves

I add URLs via the command line and I would love to add tags at the same time. It could very well be that this option already exists, I just can’t find it. 

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

It could work something like this:

````
archivebox add https://example.com -t tag1,tag2,tag4,tag3
````

## What hacks or alternative solutions have you tried to solve the problem?

I log into the web interface to add tags after the fact.

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [x] It would be nice to have eventually

---

 - [x] I'm willing to contribute a bit of [money](https://github.com/sponsors/pirate) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
Already exists 😁 
<img width="1412" alt="image" src="https://github.com/ArchiveBox/ArchiveBox/assets/511499/74badeda-e7ba-4424-93eb-9df79ea0c207">
