### ISSUE TITLE
Update docker Scheduled Archiving

### ISSUE THREAD

**Issue by cutterkom** [ArchiveBox/ArchiveBox#1236]
## Wiki Page URL

https://github.com/ArchiveBox/ArchiveBox/wiki/Scheduled-Archiving#docker-usage

## Suggested Edit
Add the suggested workflow from https://github.com/ArchiveBox/ArchiveBox/issues/1155#issuecomment-1590146616 to the offical wiki.

**Comment by pirate** [comment]
Done, thanks! https://github.com/ArchiveBox/ArchiveBox/wiki/Scheduled-Archiving#docker-usage
