### ISSUE TITLE
Bug: Error while loading configuration value: CHROME_VERSION UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by allen7u** [ArchiveBox/ArchiveBox#1239]
My environment was Win10, Python 3.10, Node 18.17.1, archivebox-0.6.2, Google Chrome 117.0.5938.149 (正式版本) （64 位） (cohort: M117 Rollout) (as I'm in China)
1, create and activate a virtual environment
2, pip3 install archivebox
So far so good, but when I ran
```python
archivebox add 'https://example.com'
```
or
```python
archivebox init --setup
```
or
```python
archivebox version
```

my Chrome 117.0.5938.149 was launched, then I got an error:

[X] Error while loading configuration value: CHROME_VERSION
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte
    Check your config for mistakes and try again (your archive data is unaffected).
        
PS:
I also downloaded chromium and set CHROME_BINARY env variable, but then I got:

archivebox version

[X] Error while loading configuration value: DEPENDENCIES
    PermissionError: [Errno 13] Permission denied: 'F:\\ArchiveBox\\chrome-win'

and I also encountered PermissionError when trying to use Archivebox with docker run or docker-compose under WSL2

PPS:
PermissonError disappeared after I move CHROME_BINARY to 'F:\\chrome-win
But when I run archivebox init --setup, I got 
[+] Installing enabled ArchiveBox dependencies automatically...
[X] Failed to install chromium using playwright: AttributeError module 'os' has no attribute 'getpgid'

It seems that archievebox was not quite native to windows after all?

**Comment by pirate** [comment]
ArchiveBox does not support Windows officially other than in Docker. Some people  have gotten it working but I cant provide official Windows support because I don't own a windows machine and don't really know anything about Windows.

Docker-compose should work but dont set a custom chrome version, as it definitely cannot use the Windows version of chrome inside a linux container.
