### ISSUE TITLE
Description on archived Javascript

### ISSUE THREAD

**Issue by p0n1** [ArchiveBox/ArchiveBox#1261]
I noticed the following descriptions on executing archived JS.

> Note: Only the wget extractor method executes archived JS when viewing snapshots, all other archive methods produce static output that does not execute JS on viewing. If you are worried about these issues ^ you should disable the wget extractor method using archivebox config --set SAVE_WGET=False.

Source: https://github.com/ArchiveBox/ArchiveBox#security-risks-of-viewing-archived-js

> Workarounds
Disable the wget extractor by setting [archivebox config --set SAVE_WGET=False](https://github.com/ArchiveBox/ArchiveBox/wiki/Configuration#save_wget), ensure you are always logged out, or serve only a [static HTML version](https://github.com/ArchiveBox/ArchiveBox/wiki/Publishing-Your-Archive#2-export-and-host-it-as-static-html) of your archive.

Source: https://github.com/ArchiveBox/ArchiveBox/security/advisories/GHSA-cr45-98w9-gwqx

I think the the [`SAVE_DOM`](https://github.com/ArchiveBox/ArchiveBox/wiki/Configuration#save_dom) archive method could also lead to the similar issue. When viewing `Chrome > HTML ./output.html`, any remote javascript will be loaded and executed.

Is that right? If so, we should also document this and remind users to disable this option if they should worry about the [XSS/CSRF issue](https://github.com/ArchiveBox/ArchiveBox/issues/239).

**Comment by pirate** [comment]
You're right, it used to be stripped before we expanded it to be the full outerHTML with `<head>`, but it it's included now. Thanks!

I'll update the CVE and notices.
