### ISSUE TITLE
Arquivo.pt service and tools

### ISSUE THREAD

**Issue by dcgomes** [ArchiveBox/ArchiveBox#1264]
## Wiki Page URL
https://github.com/ArchiveBox/ArchiveBox/wiki/Web-Archiving-Community#other-public-archiving-services

## Suggested Edit
Add to list:
https://github.com/arquivo
https://arquivo.pt
https://arquivo.pt/catalog

**Comment by pirate** [comment]
✅ added `https://arquivo.pt`
