### ISSUE TITLE
Fix broken link to article "On the Importance of Web Archiving"

### ISSUE THREAD

**Issue by dcgomes** [ArchiveBox/ArchiveBox#1265]
## Wiki Page URL
https://github.com/ArchiveBox/ArchiveBox/wiki/Web-Archiving-Community#from-the-archiveorg--archive-it-teams

## Suggested Edit
This link is broken:
"Check out this article: [On the Importance of Web Archiving](https://parameters.ssrc.org/2018/09/on-the-importance-of-web-archiving/)."

I suggest the link is replaced to reference the we-archived version of the article:
https://arquivo.pt/wayback/20220601063551/https://items.ssrc.org/parameters/on-the-importance-of-web-archiving/
:-)

**Comment by pirate** [comment]
They just moved it to https://items.ssrc.org/parameters/on-the-importance-of-web-archiving/ ;)
