### ISSUE TITLE
Plan for migration to Django 4

### ISSUE THREAD

**Issue by siraben** [ArchiveBox/ArchiveBox#1268]
Django 3.2.x is running out of support after 2024-04-01. I am the maintainer of archivebox in Nixpkgs (relevant issue https://github.com/NixOS/nixpkgs/issues/262907 ), and we are discussing on how to handle packages that are still using Django 3. Are there any plans to migrate archivebox to Django 4? Thanks!

**Comment by pirate** [comment]
Please follow progress here: https://github.com/ArchiveBox/ArchiveBox/issues/988
