### ISSUE TITLE
support: mounting docker data directory

### ISSUE THREAD

**Issue by shazgames1** [ArchiveBox/ArchiveBox#1277]
#### Describe the bug
Running ArchiveBox init inside Docker completely breaks Linux permissions. I can't even open new terminal session because of Permission denied

#### Steps to reproduce
1. docker run -v $PWD:/data -it archivebox/archivebox init --setup

#### Screenshots or log output

Status: Downloaded newer image for archivebox/archivebox:latest
chown: cannot access '/browsers/*': No such file or directory
[i] [2023-11-27 16:27:40] ArchiveBox v0.7.1+editable: archivebox init --setup
    > /data

[X] This folder appears to already have files in it, but no index.sqlite3 present.

  You must run init in a completely empty directory, or an existing data folder.

  Hint: To import an existing data folder make sure to cd into the folder first, 
  then run and run 'archivebox init' to pick up where you left off.

  (Always make sure your data folder is backed up first before updating ArchiveBox)

#### ArchiveBox version

Latest from DockerHub

**Comment by shazgames1** [comment]
I run in user's home directory (/home/$USER)

**Comment by shazgames1** [comment]
I installed docker on clean ubuntu using [official docker instruction](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository) with [Linux post-installation steps](https://docs.docker.com/engine/install/linux-postinstall/)

**Comment by shazgames1** [comment]
It would be useful to add this clarification to the [documentation in a block using Docker](https://docs.archivebox.io/en/latest/Docker.html) to avoid problems

**Comment by shazgames1** [comment]
I'm still wondering how the container was able to access the host's system directories

**Comment by pirate** [comment]
The docs are pretty clear about the requirements of the data folder ![image](https://github.com/ArchiveBox/ArchiveBox/assets/511499/caa61e03-161b-4cec-b749-5b1eee3d87b2)

**Comment by shazgames1** [comment]
I mean Usage instruction instruction in the [Overview](https://docs.archivebox.io/en/latest/Docker.html#overview). There is no information about  necessity of running command in new empty directory. Why not add a `mkdir archivebox && cd archivebox` instruction to the section as is done in [Docker Compose Setup section](https://docs.archivebox.io/en/latest/Docker.html#setup) ?
<img width="803" alt="Screenshot 2023-11-29 at 13 58 39" src="https://github.com/ArchiveBox/ArchiveBox/assets/33340446/38895983-869d-406d-93f9-7c56c4c8cc2a">

**Comment by hafx** [comment]
Hi, 

I'm using the last image version and I still have the same issue as you. 

The error is : 
`chown: cannot access '/browsers/*': No such file or directory`

The volume used for my case is : `/SSD1/archivebox/data:/data`
I changed the permission on this folder : `chmod 777 -R /SSD1/archivebox/data` but nothing change. 

I followed the step on this page : https://archivebox.io/

Thanks for your help.

**Comment by pirate** [comment]
The browsers folder should not require binding and has no relation to the /data folder, it's entirely internal to the container.  do you mind posting the full output of `archivebox version`?

**Comment by hafx** [comment]
> Do you mind opening a new issue @hafx and posting the full output of `archivebox version`?

@Gobbless beat me to it.
