### ISSUE TITLE
AUTH_LDAP_USER_FLAGS_BY_GROUP implementation

### ISSUE THREAD

**Issue by vladimirdulov** [ArchiveBox/ArchiveBox#1279]
Please add AUTH_LDAP_USER_FLAGS_BY_GROUP settings implementation to set values of "is_staff" and "is_superuser" for Django LDAP authenticated users.

https://django-auth-ldap.readthedocs.io/en/latest/reference.html#auth-ldap-user-flags-by-group

https://django-auth-ldap.readthedocs.io/en/latest/example.html

e.g.
```
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_active": "cn=active,ou=django,ou=groups,dc=example,dc=com",
    "is_staff": "cn=staff,ou=django,ou=groups,dc=example,dc=com",
    "is_superuser": "cn=superuser,ou=django,ou=groups,dc=example,dc=com",
}
```

**Comment by pirate** [comment]
This sounds reasonable to add but I don't have any experience with LDAP myself, would you be willing to submit a PR for this change?

**Comment by vladimirdulov** [comment]
Sure, I'll try to get a time for it.

Currently LDAP users cannot login at all as `is_staff` is False, at the same time the local user auth doesn't work either as it's replaced with LDAP auth (when LDAP env var is True).
As a workaround we are updating `is_staff` and `is_superuser ` flags for every LDAP user using DJANGO console.
Apparently it's not convenient.
```
$ archivebox manage shell <<EOF
from django.contrib.auth.models import User
User.objects.filter(username='USERNAME').update(is_superuser=True, is_staff=True)
EOF
```

**Comment by pirate** [comment]
I believe this is fixed now that https://github.com/ArchiveBox/ArchiveBox/pull/1281 is merged, post back here if you're still having problems and I can reopen the issue.
