### ISSUE TITLE
Change --setup flag to --install to clarify what the flag is for

### ISSUE THREAD

**Issue by pirate** [ArchiveBox/ArchiveBox#1288]
ArchiveBox init --setup is confusing as init and setup mean the same thing. We should rename the flag to make this clearer somehow.

**Comment by mamema** [comment]
as you have also problems with the web extension, are you using the devversion?

**Comment by pirate** [comment]
I'm the creator of ArchiveBox ;)  I recommend using the `dev` version for now (0.7.1)

**Comment by pirate** [comment]
Whoops created this twice https://github.com/ArchiveBox/ArchiveBox/issues/1348
