### ISSUE TITLE
Feature Request: export cookies with chromium to help archiving CloudFlare based sites

### ISSUE THREAD

**Issue by jhall39** [ArchiveBox/ArchiveBox#1293]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves
CloudFlare has some anti-bot protection that sets a cookie with a 1 hour timeout and looks for it to make sure you're using a browser instead of tool like wget. Wget will work if you give it the cookies, but that takes special effort if you're doing it by hand. It'd be helpful if ArchiveBox could be configured to get the cookies with Chromium and export them to a cookies.txt type of file for use in wget, yt-dlp, etc. I have at least one site where trying to archive it results in wget and yt-dlp failing to grab anything, but everything that uses Chromium works.

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [x] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

**Comment by pirate** [comment]
For now you can use a browser extension or CLI tool like https://github.com/barnardb/cookies to export the chromium cookies to a `cookies.txt` file, then point archivebox to it using https://github.com/ArchiveBox/ArchiveBox/wiki/Configuration#cookies_file
