### ISSUE TITLE
Question: How to run archivebox command from outside collection directory

### ISSUE THREAD

**Issue by h4rk8s** [ArchiveBox/ArchiveBox#1299]
I want to have a parameter that can run anywhere, I'm using this method right now, is there a better way?

```bash
which archivebox
archivebox () {
	local prev_dir=$(pwd)
	cd "$HOME/Workspace/Archive"
	command archivebox "$@"
	cd "$prev_dir"
}
```

**Comment by pirate** [comment]
That works, but I think slightly simpler is to use the `env` command to wrap it: https://www.gnu.org/software/coreutils/manual/html_node/env-invocation.html

```bash
env --chdir="$HOME/Workspace/Archive" archivebox ...
# aka
env -C "$HOME/Workspace/Archive" archivebox ...
```

To make an alias in bash:
```bash
alias archivebox='env --chdir="$HOME/Workspace/Archive" archivebox'
```
