### ISSUE TITLE
Question: BASE URL environment variable on docker image

### ISSUE THREAD

**Issue by tomasvanagas** [ArchiveBox/ArchiveBox#1326]
Hello, I am trying to run archivebox docker container with the base url (For example "domain.com/archivebox") but I can't find how.

Does archivebox have this functionality? If not perhaps you have any experience on how this could be achieved?

Thank you

**Comment by pirate** [comment]
It's not allowed for security reasons: https://github.com/ArchiveBox/ArchiveBox/issues/724#issuecomment-1448573113

Archived JS can access your cookies from anything else hosted on the same domain, so to limit the potential impact it should always be hosted on a separate subdomain or port. You can then serve a redirect from `302 domain.com/archivebox -> archivebox.domain.com` .

**Comment by tomasvanagas** [comment]
Thank you for a quick reply, haven't thought about this
