### ISSUE TITLE
Documentation: Default value for PUBLIC_* keys incorrect

### ISSUE THREAD

**Issue by sclu1034** [ArchiveBox/ArchiveBox#1352]
## Wiki Page URL
https://github.com/ArchiveBox/ArchiveBox/wiki/Configuration#public_index--public_snapshots--public_add_view

## Suggested Edit
The listed default value is `False`, but unless I explicitly set that value in the config or via the CLI, the snapshopts and index _are_ accessible without login.
Therefore, the actual default is effectively `True`.

This may also be a bug in the application instead, if `False` is supposed to be the default as documented.

**Comment by pirate** [comment]
Thanks for the the heads up, I fixed the defaults shown in the docs:

https://github.com/ArchiveBox/ArchiveBox/wiki/Configuration#public_index--public_snapshots--public_add_view

```python
# these are the defaults that ship with ArchiveBox
'PUBLIC_INDEX':              {'type': bool,  'default': True},
'PUBLIC_SNAPSHOTS':          {'type': bool,  'default': True},
'PUBLIC_ADD_VIEW':           {'type': bool,  'default': False},
```
