### ISSUE TITLE
Ability to disable archiving if not logged in

### ISSUE THREAD

**Issue by sdb2754** [ArchiveBox/ArchiveBox#1381]
## Type 

 - [ ] Request modification of existing behavior or design

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

Admin page option: Disable/enable guests from making a snapshot

## What hacks or alternative solutions have you tried to solve the problem?

I haven't found any. I thought about trying to modify the code, but it seems risky, as I'm not an expert.

## How badly do you want this new feature?

 - [x] It's an urgent deal-breaker, I can't live without it
I think this is a security risk.

---

 - [x] I like ArchiveBox so far / would recommend it to a friend
I like this tool, and its very impressive. I'm not sure that I have the skill to help with this feature, but I think its very important.

**Comment by pirate** [comment]
```bash
archivebox config --set PUBLIC_ADD_VIEW=False
```

https://github.com/ArchiveBox/ArchiveBox/wiki/Configuration#public_index--public_snapshots--public_add_view

**Comment by sdb2754** [comment]
> ```shell
> archivebox config --set PUBLIC_ADD_VIEW=False
> ```
> 
> * https://github.com/ArchiveBox/ArchiveBox/wiki/Usage#ui-usage
> * https://github.com/ArchiveBox/ArchiveBox/wiki/Configuration#public_index--public_snapshots--public_add_view

Thank you. I apologize. I looked around for this, but must have not had the right search terms.

**Comment by pirate** [comment]
All good 👍
