### ISSUE TITLE
Question: How to recursively archive directories containing many PDF download links

### ISSUE THREAD

**Issue by JKL213** [ArchiveBox/ArchiveBox#1423]
Title as is. I want to archive an Apache2 file server page (download.eversberg.eu) that has a ton of PDF files. Any convenient way to achieve this? I tried depth=1 and it does not really work. The PDF links still redirect to the original page.

**Comment by pirate** [comment]
Need more info to help diagnose.

Can you provide a screenshot of the failing output, example of a URL you're trying to archive, or at least the log output that it shows while it's archiving?

Also need the full output of `archivebox version` if there are any errors you're encountering or if you think theres a bug in the `---depth=1` behavior.

**Comment by JKL213** [comment]
I'm sorry, my request was terribly worded. I'm looking to archive the site "download.eversberg.eu" which is essentially just a file host running on Apache2. I managed to solve my issue by just running individual archive tasks for every folder and using depth setting 1. I'm essentially just using for a convenient way to archive below depth 1.
