### ISSUE TITLE
Bug: container-image on github is wrongly named archivebox/archivebox/archivebox

### ISSUE THREAD

**Issue by davralin** [ArchiveBox/ArchiveBox#1437]
#### Describe the bug
https://github.com/orgs/ArchiveBox/packages
lists the packages for this organisation, but the package is named `archivebox/archivebox`, which is added to the organization - making the final package URL to be `ArchiveBox/archivebox/archivebox:tag`

#### Steps to reproduce
https://github.com/orgs/ArchiveBox/packages

#### Screenshots or log output
N/A

#### ArchiveBox version

N/A

**Comment by pirate** [comment]
We don't really use ghcr, I don't think I put it in the docs anywhere (correct me if I'm wrong).  The canonical docker image is https://hub.docker.com/r/archivebox/archivebox aka `archivebox/archivebox:latest` or `archivebox/archivebox:stable`

**Comment by davralin** [comment]
I prefer ghcr-repos since they don't have rate limits, so I always check there first.

Does that mean you will delete them from ghcr, and update the build job to not push to ghcr?

**Comment by pirate** [comment]
fixed ba14ee0e

**Comment by davralin** [comment]
I can't seem to find `ghcr.io/archivebox/archivebox`-images anywhere, are they public?

**Comment by pirate** [comment]
ah strange it defaulted to private even though the repo is public? fixed
