### ISSUE TITLE
Question: How can I archive a page with expandable comments? 

### ISSUE THREAD

**Issue by iluvatyr** [ArchiveBox/ArchiveBox#1442]
There are a lot of pages that have comments that can be expanded (reddit, youtube, 9gag....)

https://9gag.com/gag/a0eLXwZ

Trying to archive this results in the expandable comments not being able to be expanded. Is there any possibility to be able to do so?

**Comment by pirate** [comment]
This is not currently supported in open-source ArchiveBox but I do offer this functionality to clients that [hire me for consulting](https://docs.monadical.com/s/archivebox-consulting-services) (along with a lot of other custom browser-automation stuff to work around bot blocking, captchas, rate-limits, login pages, etc.).

Those are very labor intensive features to maintain and charging a few clients pays me just barely enough to work on archivebox full time and keep the rest of it open source.

I may open source those parts in the future once the [new plugin system](https://github.com/ArchiveBox/ArchiveBox/pull/1432/files) is released and stable for a few months, but that's definitely 6mo+ away.

**Comment by pirate** [comment]
comment auto-expanding is now implemted on dev, check out `archivebox/plugins/infiniscroll` and set  `INFINISCROLL_EXPAND_DETAILS=True`
