### ISSUE TITLE
can't install on ubuntu 24

### ISSUE THREAD

**Issue by 0sm1les** [ArchiveBox/ArchiveBox#1459]
The installation instructions in the documents will not work for ubuntu 24 LTS. Here is my output:
```bash
echo "deb http://ppa.launchpad.net/archivebox/archivebox/ubuntu focal main" | sudo tee /etc/apt/sources.list.d/archivebox.list

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C258F79DCC02E369

sudo apt install archivebox
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 archivebox : Depends: youtube-dl but it is not installable
              Depends: python3-django-jsonfield but it is not installable
E: Unable to correct problems, you have held broken packages.
```
looks like the packages are not in the official repos:
https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=python3-django-jsonfield&searchon=names

https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=youtube-dl&searchon=names

my system information 
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble
```

**Comment by pirate** [comment]
Sorry for the trouble, I'm slowly deprecating the apt PPA that we used to offer as it's led to many difficult packaging situations like this.

Please follow our new, updated bare-metal install docs instead: https://github.com/ArchiveBox/ArchiveBox/wiki/Install#ubuntudebian-based-systems

**Comment by 0sm1les** [comment]
> Sorry for the trouble, I'm slowly deprecating the apt PPA that we used to offer as it's led to many difficult packaging situations like this (Ubuntu/Debian pin many old packages that conflict with the newer ones ArchiveBox depends on).
> 
> Please follow our new, updated bare-metal install docs instead: https://github.com/ArchiveBox/ArchiveBox/wiki/Install#ubuntudebian-based-systems
> 
> Comment back if you still have issues with the new install guide and I can re-open the issue.

Hi thanks for the reply, I just ended up using the docker install.
