### ISSUE TITLE
Feature Request: Update Django dependency

### ISSUE THREAD

**Issue by xeyler** [ArchiveBox/ArchiveBox#1460]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves
Django 3.1 no longer works with the latest version of Python 3.12 because it uses `distutils`, which Python 3.12 removed. Django 3.1 hasn't been supported for over three years now. It's time to update the dependency.

It's unclear to me why ArchiveBox uses Django < 3.2 specifically and how much effort it would require to update, but I'm willing to contribute.

## How badly do you want this new feature?
Personally, I'm fine using pyenv to run ArchiveBox using Python 3.11, but this will very quickly become an issue for many users of ArchiveBox.

---

 - [x] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend

**Comment by pirate** [comment]
This is already done, `dev` is on 5.0.

**Comment by xeyler** [comment]
> This is already done, `dev` is on 5.0.

Shoot. I don't know why I didn't think to check... :sweat_smile:
