### ISSUE TITLE
Documentation: Remove/replace TrueNAS install instructions, as the linked guide is outdated.

### ISSUE THREAD

**Issue by Ysujy** [ArchiveBox/ArchiveBox#1486]
## Wiki Page URL
https://github.com/ArchiveBox/ArchiveBox/blob/6a33de671524e9b721b05c8107b7c6206ecf4c15/README.md#-other-options

## Suggested Edit
Both the linked documentation and article use the Truecharts repository, which has been [deprecated](https://truecharts.org/deprecated/scale/) for TrueNAS Scale. Users can no longer add the Truecharts repository to their systems. Therefore, the linked instructions should either be removed or updated.

**Comment by pirate** [comment]
damn, I just made that chart.

oh well, I think the new Electric Eel system will be better when it comes out...

https://github.com/ArchiveBox/ArchiveBox/commit/ff992a3edb6fe42f10a7b32d807ed74e3a6ee8f2
