### ISSUE TITLE
Question: ... How to uninstall (fully)

### ISSUE THREAD

**Issue by TheKingKerellos** [ArchiveBox/ArchiveBox#1492]
Question in the title.
Ubuntu 22.04.3 LTS
Used the automatic install script

**Comment by pirate** [comment]
Did you choose docker or apt when prompted by the auto script?

**Comment by TheKingKerellos** [comment]
> Did you choose docker or apt when prompted by the auto script?

I used apt

**Comment by pirate** [comment]
Ok, run this to fully uninstall:

```bash
pip uninstall archivebox
apt purge -y archivebox
apt autoremove -y
rm /etc/apt/sources.list.d/archivebox.list
```
