### ISSUE TITLE
Feature Request: For REST API, ability to turn off CSRF.

### ISSUE THREAD

**Issue by spott** [ArchiveBox/ArchiveBox#1503]
When trying to use archive box as a separate docker container, when I try and use any of the endpoints that require auth, I get:

```
"POST /api/v1/cli/add HTTP/1.1" 403 31
Forbidden (CSRF cookie not set.): /api/v1/cli/add
Forbidden: /api/v1/cli/add
```

because CSRF is required.  There should be a setting to remove this requirement so that the API can be used from other domains without issue.

## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [x] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [x] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
This should be fixed in the latest pre-release: https://github.com/ArchiveBox/ArchiveBox/releases/tag/v0.8.3-rc

Comment back if you're still having trouble!
