### ISSUE TITLE
Feature Request/Bug: Remove external CDN requests jquery/jsdelivr

### ISSUE THREAD

**Issue by jessienab** [ArchiveBox/ArchiveBox#1508]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves
[ArchiveBox 0.8.3-rc](https://github.com/ArchiveBox/ArchiveBox/releases/tag/v0.8.3-rc) is making request to two external resources, from the admin panel. 

https://code.jquery.com/jquery-3.7.1.slim.min.js
https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js

Denying access to these resources cause a mild UI rendering issue, see below:
![Screenshot from 2024-09-06 10-27-30](https://github.com/user-attachments/assets/d6286ecc-733c-4620-9c85-af34fc697344)
![Screenshot from 2024-09-06 10-31-19](https://github.com/user-attachments/assets/ed76b8a4-8609-4147-af9b-87af683f613f)

Allowing the resources renders the UI properly:
![Screenshot from 2024-09-06 10-33-34](https://github.com/user-attachments/assets/005a1d47-5d7a-485c-80ad-de7a216695ff)

Possibly related to https://github.com/ArchiveBox/ArchiveBox/issues/644

It would be better to have these files served locally, to both limit external requests, and to provide faster performance. It would also be recommended given that in theory, some users are running ArchiveBox within intranet/local setups.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

Serve the two files locally to reduce external requests and satisfy localhost/intranet/offline users.

## What hacks or alternative solutions have you tried to solve the problem?
None, other than blocking the resources with uMatrix.

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [x] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [x] I like ArchiveBox so far / would recommend it to a friend

Thank you very much! :)

**Comment by pirate** [comment]
Sure no problem, I usually remove all external resources I just missed these by accident.

**Comment by pirate** [comment]
Fixed f5c878b2. Thanks!
