### ISSUE TITLE
Question: Importing Data?

### ISSUE THREAD

**Issue by Godly-Avenger** [ArchiveBox/ArchiveBox#1556]
If I already have archived data from another source (in the form of WACZ or WARC files), is it possible to import it _into_ ArchiveBox? If so, how?

**Comment by pirate** [comment]
I recomment adding all the URLs to archivebox with just the `title` and `favicon` methods selected first.

This will create snapshot dirs for each URL.

Then iterate over the output of `archivebox list --csv=timestamp,url` to get snapshot IDs (timestamps) for all the directories it created..

If you match the filesystem structure archivebox expects in each dir, it should show your files in the UI:
```
archive/
    <snapshot ts>/
        index.json
        index.html
        dom.html
        example.com/index.html
        example.com/images/
            icon.png
        media/
            video_files_go_here.mp4
            or_audio_files.mp3
        ...
```
They wont have corresponding `ArchiveResult` entries in the Admin UI (you can manually create those if you need them) but it's not necessary if you only want to see your files on the Snapshot detail view page.

For more see here: https://github.com/ArchiveBox/ArchiveBox#output-formats

**Comment by pirate** [comment]
Lets move ongoing discussion here though in order to keep the convo in one place: https://github.com/ArchiveBox/ArchiveBox/issues/160
