### ISSUE TITLE
Bug: ...geteuid() doesn't work in Windows

### ISSUE THREAD

**Issue by GuyverMack** [ArchiveBox/ArchiveBox#1573]
#### Describe the bug
trying to run:
` archivebox config` in a Windows 11 Powershell terminal. Same goes for cmd.exe and including both as admin.
Solution: [https://stackoverflow.com/questions/75977215/attributeerror-module-os-has-no-attribute-geteuid](https://stackoverflow.com/questions/75977215/attributeerror-module-os-has-no-attribute-geteuid
)
geteuid() is only available on unix-like systems
#### Steps to reproduce
trying to run:
` archivebox config`
in Windows 11 terminal
#### Screenshots or log output

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python312\Scripts\archivebox.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python312\Lib\site-packages\archivebox\cli\__init__.py", line 11, in <module>
    from ..config import OUTPUT_DIR, check_data_folder, check_migrations
  File "C:\Program Files\Python312\Lib\site-packages\archivebox\config.py", line 82, in <module>
    'PUID':                     {'type': int,   'default': os.getuid()},
                                                           ^^^^^^^^^
AttributeError: module 'os' has no attribute 'getuid'. Did you mean: 'getpid'?`

#### ArchiveBox version
0.7.1
I cannot even run `archivebox version` because it causes the same error as above.

**Comment by pirate** [comment]
![Image](https://github.com/user-attachments/assets/1ed6dd75-b81c-4c82-a20d-84bd259edf08)
