### ISSUE TITLE
Feature Request: Modify the Github issue template to a user-friendly form, with input fields and automatic filling of labels and issue type

### ISSUE THREAD

**Issue by ghost5501** [ArchiveBox/ArchiveBox#1574]
## Type 

 - [ ] General question or discussion
 - [x] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves
Better organization of issues in this repository

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
Modify the Github issue template to a user-friendly form, with input fields and automatic filling of labels and issue type.

You can be an example by trying to create an Issue in the repositories:

- https://github.com/microsoft/PowerToys/
- https://github.com/microsoft/terminal/

It is even possible to mark some inputs as required, mandatory to fill in, trying to click on the button to create an Issue will return an error, if the field is empty.

![Image](https://github.com/user-attachments/assets/ef41096a-429a-4aef-85c9-76cc09be84ec)

## What hacks or alternative solutions have you tried to solve the problem?
_Not applicable_

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [x] It would be nice to have eventually

---

 - [x] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
Done, thanks, good idea.

https://github.com/ArchiveBox/ArchiveBox/issues/new?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen&template=bug_report.yml
