### ISSUE TITLE
Bug: setup.sh continues even if creating ~/archivebox/data fails, causing chown of contents of dir the script is run from

### ISSUE THREAD

**Issue by 1over137** [ArchiveBox/ArchiveBox#1584]
Not a security vulnerability (at least in a way I can think of)
I assume I'm just very unlucky today and I triggered a somewhat dangerous bug in https://github.com/ArchiveBox/ArchiveBox/blob/dev/bin/setup.sh.
## Preconditions
- No docker-compose binary (N.B. I don't think this binary is shipped anymore, so that detection will never pass, you might want to consider changing this)
- Having already previously manually ran a command like this, which initializes a archivebox data folder:

`docker run -v ~/archivebox:/data -it -d -p 8000:8000 --name=archivebox archivebox/archivebox:latest init --setup`

Notice that this chown's ~/archivebox, resulting in permission denied if you try to cd in it. This sets the stage for the bug.

## Bug
Going through setup.sh, starting at line 52
https://github.com/ArchiveBox/ArchiveBox/blob/1148cadd7aa6ea902668b1a527aa9cba3060c90e/bin/setup.sh#L53
This fails, but the script continues.
https://github.com/ArchiveBox/ArchiveBox/blob/1148cadd7aa6ea902668b1a527aa9cba3060c90e/bin/setup.sh#L54
This fails, but the script keeps running. **We are still in the user's home!**
https://github.com/ArchiveBox/ArchiveBox/blob/1148cadd7aa6ea902668b1a527aa9cba3060c90e/bin/setup.sh#L58
This fails, but the script keeps running. **We are still in the user's home!**
https://github.com/ArchiveBox/ArchiveBox/blob/1148cadd7aa6ea902668b1a527aa9cba3060c90e/bin/setup.sh#L59
This fails because it will refuse to init if folder is non-empty. **We are still in the user's home!**
https://github.com/ArchiveBox/ArchiveBox/blob/1148cadd7aa6ea902668b1a527aa9cba3060c90e/bin/setup.sh#L62
**This runs in the user's home.** Many files get chown'd to the user ID 911, including the user's home directory itself. This renders the user unable to access his own files, and requires root to recover. 
## Some general advice
In general, any commands that can possibly fail in a shell script, when it fails unexpectedly (like the first mkdir -p command) **should terminate the entire script**. You might want to include a `die` function and use `mkdir -p ~/archivebox/data || die`, then it would have killed the script instead of letting it keep going. 

Reference: https://stackoverflow.com/questions/7868818/in-bash-is-there-an-equivalent-of-die-error-msg

## Questions
What does the program do after that command runs besides chown'ing the files? I'm considering recovering from a backup in case it changed any files.

**Comment by pirate** [comment]
`setup.sh` is completely deprecated as of v0.8.6, I'm about to remove it.

With the new versions you can just do:

```bash
pip install archivebox==0.8.5rc50

archivebox install
```

**Comment by pirate** [comment]
I've updated `setup.sh` in the meantime: https://github.com/ArchiveBox/ArchiveBox/commit/fd89de5b912e2d5c845e6e406e0c364c754fa1f7

To see what else the Docker container does on startup to the data dir you can read this script:
https://github.com/ArchiveBox/ArchiveBox/blob/dev/bin/docker_entrypoint.sh

**Comment by 1over137** [comment]
That's what I figured. The only observable effect seems to be the creation of a logs directory under ~.

**Comment by pirate** [comment]
There just a couple others to check for depending on how far it got:

- `./logs`
- `./crontabs`
- `./archive`

**Comment by 1over137** [comment]
Only logs was created. Also not everything was chown'd, so most likely it got killed in the middle of that `find` command

**Comment by pirate** [comment]
I've added an extra step that prevents this at the docker level even if a user doesn't use `setup.sh`: https://github.com/ArchiveBox/ArchiveBox/commit/99ed97836ff42565a30dcb7ecbf3432778d19d15

**Comment by 1over137** [comment]
I would check for something like .bashrc/.zshrc. Many servers do not have Documents and some do not have a .config
