### ISSUE TITLE
Bug: v0.8.5rc51 dev builds ignore `TIMEOUT` and some other config options

### ISSUE THREAD

**Issue by THonscha** [ArchiveBox/ArchiveBox#1591]
Only WGET sets the correct timeout. Singlefile for example uses the default 60s.

### Steps to reproduce

```markdown
archivebox add https://....
```

### Logs or errors

```shell

```

### ArchiveBox Version

```shell
ArchiveBox v0.8.5rc51
```

### How did you install the version of ArchiveBox you are using?

Docker (or other container system like podman/LXC/Kubernetes or TrueNAS/Cloudron/YunoHost/etc.)

### What operating system are you running on?

Linux (Ubuntu/Debian/Arch/Alpine/etc.)

### What type of drive are you using to store your ArchiveBox data?

- [x] `data/` is on a local SSD or NVMe drive
- [ ] `data/` is on a spinning hard drive or external USB drive
- [ ] `data/` is on a network mount (e.g. NFS/SMB/CIFS/etc.)
- [ ] `data/` is on a FUSE mount (e.g. SSHFS/RClone/S3/B2/OneDrive, etc.)

### Docker Compose Configuration

```shell

```

### ArchiveBox Configuration

```shell

```

**Comment by pirate** [comment]
Yeah config loading isn't finished yet in the rc dev builds, still working on tweaking it because I'm adding a new per-snapshot/per-crawl config override option that has changed how it's handled.

**Comment by pirate** [comment]
Merging this with https://github.com/ArchiveBox/ArchiveBox/issues/1551
