### ISSUE TITLE
Documentation: ...

### ISSUE THREAD

**Issue by Mela** [ArchiveBox/ArchiveBox#1611]
### What is the URL of the page you'd like to see improved?

https://github.com/ArchiveBox/ArchiveBox/wiki/Install#option-c-bare-metal-setup

### What is the title of the relevant section?

Ubuntu/Debian-based Systems

### What is the suggested edit?

> # Install base system dependencies manually (check ArchiveBox/Dockerfile for more if needed)

> sudo apt install python3 python3-pip python3-minimal **python3-distutils** nodejs libatomic1 zlib1g-dev libssl-dev libldap2-dev libsasl2-dev python3-ldap python3-msgpack python3-mutagen python3-regex python3-pycryptodome procps dnsutils wget curl git yt-dlp ffmpeg ripgrep

There is no apt packet named 'python3-distutils'. The instruction thus will not result in a working installation. 

Regards,
Mela

**Comment by pirate** [comment]
There is: https://packages.debian.org/search?keywords=python3-distutils

But it's not available the same way on all debian-based distributions, you can try `pip install distutils`.
