### ISSUE TITLE
Bug: Bare metal install not possible on Ubuntu 24.10 - python3-distutils has been deprecated

### ISSUE THREAD

**Issue by nextgenthemes** [ArchiveBox/ArchiveBox#1616]
### Provide a screenshot and describe the bug

`python3-distutils`  has been deprecated.

Btw, I think the pip install should be done in a python virtualenv. I think new versions of Ubuntu/Python do not even let you do it without one. At least they encourage and complain if you try otherwise, not sure.

Also, you tell people to install 3 packages with pip in the docs
```
`pip install --upgrade --ignore-installed archivebox[ldap,sonic]
```
That is not a valid command. And also ldap and sonic are not valid pip package names. So I guess you want people to have the latest versions of them.

I think I should read like this:

```
# this should be un dependancy install command under 1. in the docs
sudo apt install python3-venv

# Create venv for archivebox and cd into it
python3 -m venv archivebox-venv
cd archivebox-venv

# Install archivebox (still inside archivebox-venv) thease are the actual package names
./bin/pip3 install --upgrade --ignore-installed python-sonic
./bin/pip3 install --upgrade --ignore-installed python3-ldab
./bin/pip3 install --upgrade --ignore-installed archivebox

# symlink the venv version into $PATH
ln -s $(readlink -m "./bin/archivebox") ~/bin/archivebox
```

I have `archivebox` as a command now like this globally, but it's giving errors that end with `ModuleNotFoundError: No module named 'distutils'`. I expected it to fail because the package `python3-distutils` was never installed.

### Steps to reproduce

```markdown
I described that above.
```

### Logs or errors

```shell
archivebox init                                      
Traceback (most recent call last):
  File "/home/user23/bin/archivebox", line 5, in <module>
    from archivebox.cli import main
  File "/home/user23/Progs/archivebox/archivebox-venv/lib/python3.12/site-packages/archivebox/cli/__init__.py", line 11, in <module>
    from ..config import OUTPUT_DIR, check_data_folder, check_migrations
  File "/home/user23/Progs/archivebox/archivebox-venv/lib/python3.12/site-packages/archivebox/config.py", line 33, in <module>
    import django
  File "/home/user23/Progs/archivebox/archivebox-venv/lib/python3.12/site-packages/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "/home/user23/Progs/archivebox/archivebox-venv/lib/python3.12/site-packages/django/utils/version.py", line 6, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
```

### ArchiveBox Version

```shell
Ubuntu 24.10
Python 3.12.7

Well, the version command fails as well. Here is the full output, same as with init.


archivebox version                                      
Traceback (most recent call last):
  File "/home/user23/bin/archivebox", line 5, in <module>
    from archivebox.cli import main
  File "/home/user23/Progs/archivebox/archivebox-venv/lib/python3.12/site-packages/archivebox/cli/__init__.py", line 11, in <module>
    from ..config import OUTPUT_DIR, check_data_folder, check_migrations
  File "/home/user23/Progs/archivebox/archivebox-venv/lib/python3.12/site-packages/archivebox/config.py", line 33, in <module>
    import django
  File "/home/user23/Progs/archivebox/archivebox-venv/lib/python3.12/site-packages/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "/home/user23/Progs/archivebox/archivebox-venv/lib/python3.12/site-packages/django/utils/version.py", line 6, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
```

### How did you install the version of ArchiveBox you are using?

pip

### What operating system are you running on?

Linux (Ubuntu/Debian/Arch/Alpine/etc.)

### What type of drive are you using to store your ArchiveBox data?

- [x] `data/` is on a local SSD or NVMe drive
- [ ] `data/` is on a spinning hard drive or external USB drive
- [ ] `data/` is on a network mount (e.g. NFS/SMB/CIFS/etc.)
- [ ] `data/` is on a FUSE mount (e.g. SSHFS/RClone/S3/B2/OneDrive, etc.)

### Docker Compose Configuration

```shell

```

### ArchiveBox Configuration

```shell
Nothing yet.
```

**Comment by 0duck0** [comment]
sudo apt install python3-distutils
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python3-distutils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-distutils' has no installation candidate

**Comment by pirate** [comment]
> `pip install distutils`

**Comment by Mela** [comment]
```bash
(.venv) archie@Lenticular:~/Archivebox/data$ pip install distutils
ERROR: Could not find a version that satisfies the requirement distutils (from versions: none)
ERROR: No matching distribution found for distutils
```

**Comment by Mela** [comment]
(Temporary?) Solution: 

`pip install setuptools `

**Comment by pirate** [comment]
Ok then you're on one of the really new systems that removed it completely, I thought they were going to offer it as an apt package for a least a couple years but I guess not. In that case you want `pip install setuptools` or `apt install python3-distutils-extra`.

**Comment by Mela** [comment]
What I got from superficial reading while searching for a solution, was: "something, something  Ubuntu pushing hard for user using only secure environments ... something ..."

**Comment by pirate** [comment]
[b3edf1f](https://github.com/ArchiveBox/docs/commit/b3edf1f911c98ad98e06bf0a8ea91da92392e2b4)
