### ISSUE TITLE
Bug: bad `requirements.txt`

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [ArchiveBox/ArchiveBox#1620]
### Provide a screenshot and describe the bug

- This commit (https://github.com/ArchiveBox/ArchiveBox/commit/51447b9d0a5e46ee637eb05939a1753d2b6d4be6#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552) introduced unresolved merge conflicts to `requirements.txt`, making it invalid.

<img width="1536" alt="Image" src="https://github.com/user-attachments/assets/b5b1239a-2943-433b-93b4-4203eda65a74" />

- Additionally, this commit (https://github.com/ArchiveBox/ArchiveBox/commit/30cd48c30dbed4783c08840cfbce3bed23c248b0#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552) added multiple absolute paths to that same file, making it not work unless you have the project cloned to that exact location.

<img width="1536" alt="Image" src="https://github.com/user-attachments/assets/01b11484-9cc6-47be-8e33-43dc7c73c107" />

### Steps to reproduce

```markdown
Take a look at `requirements.txt`.
```

### Logs or errors

```shell

```

### ArchiveBox Version

```shell
https://github.com/ArchiveBox/ArchiveBox/commit/f31adff0ed596aafa8f534b59c74cdb329765c5c
```

### How did you install the version of ArchiveBox you are using?

Other

### What operating system are you running on?

Other

### What type of drive are you using to store your ArchiveBox data?

- [ ] `data/` is on a local SSD or NVMe drive
- [ ] `data/` is on a spinning hard drive or external USB drive
- [ ] `data/` is on a network mount (e.g. NFS/SMB/CIFS/etc.)
- [ ] `data/` is on a FUSE mount (e.g. SSHFS/RClone/S3/B2/OneDrive, etc.)

### Docker Compose Configuration

```shell

```

### ArchiveBox Configuration

```shell

```

**Comment by pirate** [comment]
yeah it's fine `requirements.txt` is only used for the docker build and it's regenerated on every build, it's in git for historical preservation only.

No one else should be depending on it, `pyproject.toml` is the single source of truth.

**Comment by pirate** [comment]
FYI I removed `requirements.txt` completely c54b9446 to prevent confusion.

Everything is basd on `uv` only now, including Docker build.
