### ISSUE TITLE
Feature Request: Verify the global command

### ISSUE THREAD

**Issue by Abhi18022** [ArchiveBox/ArchiveBox#442]
the install script should verify whether the global command was successfully installed and can be run by the current user

**Comment by pirate** [comment]
Which install script are you referring to? `./bin/setup.sh`? I was thinking about removing that entirely. I don't really like bash install scripts for package distribution for the reasons I outline here: https://docs.monadical.com/s/against-curl-sh

**Comment by pirate** [comment]
The install script is no longer a supported install method. You should use the system package manager, docker, or pip to install archivebox.
