### ISSUE TITLE
Bugfix: WGET paths are not working as expected with trailing slashes

### ISSUE THREAD

**Issue by cdvv7788** [ArchiveBox/ArchiveBox#487]
#### Describe the bug
Wget replaces src paths with relative paths. When there is a trailing slash, the relative path fails to point to the correct source.

#### Steps to reproduce

1. Run `archivebox add https://some_url`
2. Start server with `archivebox server`
3. Check the wget output by navigating from the index (https://user-images.githubusercontent.com/3484775/94161808-161e1680-fe54-11ea-8fe2-180aef1bc324.png)
The css, images, etc. will be broken (404). Removing the trailing slash fixes the issue.

#### Screenshots or log output

![image](https://user-images.githubusercontent.com/5531776/94303336-438dc180-ff33-11ea-8c71-53221e43c1be.png)

#### Software versions

 - OS: macOS 10.15.6
 - ArchiveBox version: master branch
 - Python version: 3.8.5

**Comment by poblabs** [comment]
I think I found the issue - at least this helped fix it for me. 

Remove the trailing slash [from this line](https://github.com/pirate/ArchiveBox/blob/master/archivebox/core/utils.py#L17), so it looks like: `<a href="/{}/{}" .... `

**Comment by cdvv7788** [comment]
I applied @poblabs suggestions in here: https://github.com/pirate/ArchiveBox/pull/488
@pirate if you think it is worth pursuing a fix that allows those paths to support both versions (with and without slash) let me know and I will dig deeper. Otherwise, just close this issue.

**Comment by pirate** [comment]
hmm I remember that trailing slash being important for some edge case when opening files from the filesystem before the archiving was finished. It lets you see a directory index rendered by chrome instead of just an error page.

**Comment by pirate** [comment]
This should be fixed in the latest v0.5.4 release. If anyone is still having issues just comment back here with the failing URLs and where they were seen and I'll reopen.
