### ISSUE TITLE
Move ArchiveResults into the SQL db to avoid checking the filesystem for every Snapshot output status

### ISSUE THREAD

**Issue by pirate** [ArchiveBox/ArchiveBox#513]
Right now archivebox.zervice.io is taking 6s+ to load because it has to check the filesystem many times for each row on the page during the template rendering process.

We can load the `ArchiveResult`s entries from the `archive/<timestamp>/index.json` files into the sqlite3 db. This will eliminate checking each output path on the filesystem every time we want to see whether it completed or not.

![Screen Shot 2020-10-24 at 3 17 45 PM](https://user-images.githubusercontent.com/511499/97091787-6a134b00-160c-11eb-9d8c-c2beb329c468.png)

**Comment by cdvv7788** [comment]
I will create a model and associate its instances with the `Snapshot` via foreign keys. Is that what you have in mind? @pirate

**Comment by cdvv7788** [comment]
@pirate can this be closed?
