### ISSUE TITLE
Webrecorder.io changed to Conifer by Rhizome

### ISSUE THREAD

**Issue by thethales** [ArchiveBox/ArchiveBox#514]
## Wiki Page URL
https://github.com/pirate/ArchiveBox/wiki/Web-Archiving-Community

## Suggested Edit
Greetings,

The page listed above needs some link/info corrections regarding the recent changes on  _Webrecorder.io_. Rhizome took over permanent stewardship of Webrecorder.iochanging the name to "[Conifer by Rhizome](https://conifer.rhizome.org/)" and making the Webrecorder.io  (now [Webrecorder.net](https://webrecorder.net/))  the oficial research and development project, so  the archive service now runs under the name _Conifer_ intead of _Webrecorder.io_

That being said, I'm unsure as to the policy for contributing to the Wiki Pages, and how to proceed.
I happen to have edited some of the text (as seen here [Revision 914529f](https://github.com/pirate/ArchiveBox/wiki/Web-Archiving-Community/914529fbf05632689d7f4123f116d4eb01067aab#from-the-rhizomeorgwebrecorderioconifer-team) ), errousnely assuming that I would make a pull request (wich seems no to exist on _Github Wikis_, as of yet) 
But, more changes are required on some of the headers and links.
I would like to contribute if permitted, but I require further instructions on how to proceed. 
Thank you very much

### References:

- Webrecorder.io is now Conifer.rhizome.org, [official post](https://blog.conifer.rhizome.org/2020/06/11/webrecorder-conifer.html) - [Archive.org Mirror] (http://web.archive.org/web/20201025154037/https://blog.conifer.rhizome.org/2020/06/11/webrecorder-conifer.html)

**Comment by pirate** [comment]
You can edit the wiki directly, no need for a PR. Thanks for double checking though!

I'll do another pass and rename any straggler webrecorder references myself in a bit.

**Comment by thethales** [comment]
Thank you for your reply,
I have taken this opportunity to further correct references, where applicable at the aforementioned article.

**Comment by pirate** [comment]
Looks good, thanks!
