### ISSUE TITLE
Raspberry Pi: "exec format error"

### ISSUE THREAD

**Issue by jackitsdotcom** [ArchiveBox/ArchiveBox#534]
#### Describe the bug

When I try and run the second command as provided in the Quickstart I get an error as below.
Let me know if there's anything I can do to help. Thankyou.

#### Steps to reproduce

```
$ docker run -v ~/archivebox:/data -it nikisweeting/archivebox manage createsuperuser
```

#### Screenshots or log output

`standard_init_linux.go:211: exec user process caused "exec format error"`
#### Software versions

 - OS:               Raspbian 10 (buster)
 - Python version:           3.7.3
 - Chrome version:          Chromium 84.0.4147.141 Built on Raspbian , running on Raspbian 10

**Comment by pirate** [comment]
You need to build the image on arm for it to work on arm.

```bash
git clone https://github.com/pirate/ArchiveBox
cd ArchiveBox

docker build . -t archivebox
docker run -v ~/archivebox:/data -it archivebox manage createsuperuser
docker run -v ~/archivebox:/data -it archivebox ...
...
```

**Comment by chrismeller** [comment]
@pirate You can actually use docker buildx to build images for different architectures. For instance, I use this to build for my Pi3 from my Windows desktop:

`docker buildx build --platform=linux/arm/v7 .`

**Comment by jackitsdotcom** [comment]
Thankyou for your help here.
The build completed successfully, but now upon running init I get this error:

`redacted@redacted:~/ArchiveBox $ docker run -v ~/archivebox:/data -it archivebox init
[i] [2020-11-16 10:55:20] ArchiveBox v0.4.21: archivebox init
    > /data

[+] Initializing a new ArchiveBox collection in this folder...
    /data
------------------------------------------------------------------

[+] Building archive folder structure...
Traceback (most recent call last):
  File "/usr/local/bin/archivebox", line 33, in <module>
    sys.exit(load_entry_point('archivebox', 'console_scripts', 'archivebox')())
  File "/app/archivebox/cli/__init__.py", line 123, in main
    run_subcommand(
  File "/app/archivebox/cli/__init__.py", line 63, in run_subcommand
    module.main(args=subcommand_args, stdin=stdin, pwd=pwd)    # type: ignore
  File "/app/archivebox/cli/archivebox_init.py", line 33, in main
    init(
  File "/app/archivebox/util.py", line 113, in typechecked_function
    return func(*args, **kwargs)
  File "/app/archivebox/main.py", line 295, in init
    Path(SOURCES_DIR).mkdir(exist_ok=True)
  File "/usr/local/lib/python3.8/pathlib.py", line 1287, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/data/sources'`

I did this as the init command led to this output:

`redacted@redacted:~/ArchiveBox $ docker run -v ~/archivebox:/data -it archivebox manage createsuperuser
[i] [2020-11-16 10:54:25] ArchiveBox v0.4.21: archivebox manage createsuperuser
    > /data

[X] No archivebox index found in the current directory.
    /data

    Hint: Are you running archivebox in the right folder?
        cd path/to/your/archive/folder
        archivebox [command]

    Hint: To create a new archive collection or import existing data in this folder, run:
        archivebox init`

**Comment by fdplacido** [comment]
@jackitsdotcom instead of using the volume (`-v`) with `~/archivebox:/data`, create some directory yourself and point to it (or change `~/archivebox` permissions: 
```
mkdir ~/mydocker/myarchivebox
docker run -v ~/mydocker/myarchivebox:/data -it archivebox init
```

Otherwise the folder can be only written by root, that's why it said Permission denied.

**Comment by pirate** [comment]
I'm going to close this because the docker builx workflow for ARM cpus is now merged. https://hub.docker.com/r/archivebox/archivebox

If you're still having permissions errors with the data folder @jackitsdotcom please open a separate issue and I'd be happy to help.
