### ISSUE TITLE
Less "open" public website

### ISSUE THREAD

**Issue by shepner** [ArchiveBox/ArchiveBox#554]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves

Occasionally I would like to share links to pages I have clipped.  However, the public ArchiveBox site is rather "open" (very easy for anyone to look at everything stored in there) and Id rather if that was not the case.  Im not asking for iron-clad security here but Id like to keep people (and bots) from snooping.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

Ideally: Implement granular access controls to the website which are tied to user accounts which can exist in an external system (ie Okta, Authelia, LDAP, etc).
Minimally: Make it so the directory structure is not publicly visible, provide an option to disable public access to the archive root, and an option to entirely disable public archive access.

## What hacks or alternative solutions have you tried to solve the problem?

Since I want to make ArchiveBox Internet accessible so I can archive sites from my mobile devices, the minimal solution above should provide a modicom of privacy and is better than expecting the user to somehow figure out how to do this via Nginx or the like.

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [x] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [ ] I'm willing to contribute dev time / money to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
Config options to manage which parts are public already exist:

![image](https://user-images.githubusercontent.com/511499/100522069-17323380-3176-11eb-9a06-7b3b7e3a42c0.png)
https://github.com/ArchiveBox/ArchiveBox/blob/e4d2ac432db2627cec7cfa5fb02e8b83bb4269bb/archivebox/config.py#L71

```bash
archivebox config --set PUBLIC_SNAPSHOTS=True
archivebox config --set PUBLIC_INDEX=False
archivebox config --set PUBLIC_ADD_VIEW=False
```

You can also manage the permissions on a per-user basis under http://127.0.0.1:8000/admin/core/user/

**Comment by shepner** [comment]
Ok, I think I figured out what those settings do.  Are they documented somewhere?  Similarly, is there some documentation for the various user account permissions?  I havnt found them in the wiki.

**Comment by pirate** [comment]
They are not documented yet because it's sort of a "beta" feature. We're planning on improving the permissions system in the future and this is just the bare minimum first version we implemented. I may add them to the Wiki but I haven't decided yet if we want to advertise these config options because they might change soon.

**Comment by shepner** [comment]
k.  In that case, Ill try to keep an eye out for that.  Thanks!

**Comment by cdvv7788** [comment]
@pirate we can close this one, right?
