### ISSUE TITLE
[Feature Request] Input An Archive Link, Get All Their Snapshots

### ISSUE THREAD

**Issue by grravity** [ArchiveBox/ArchiveBox#560]
Suggesting the ability to input a public archive link, lets use archive.is or waybackmachine for example, you input their lnk, then it goes through and grabs all the snapshots they have publicly viewable.

Optionally with the ability to set dates (xx date to xx date, 2004-2008, 2020 only, May 2020 only, etc)

Ideally just the site itself, not the whole archive web gui wrapping.

This is especially good for sites that already don't exist anymore.

**Comment by pirate** [comment]
You should follow this issue for progress on this: https://github.com/ArchiveBox/ArchiveBox/issues/160

Tangentially related:
- https://github.com/ArchiveBox/ArchiveBox/issues/179
- https://github.com/ArchiveBox/ArchiveBox/issues/146
- https://github.com/ArchiveBox/ArchiveBox/issues/439
