### ISSUE TITLE
Feature Request: Allow config of the "add archive" action from the web UI

### ISSUE THREAD

**Issue by BlipRanger** [ArchiveBox/ArchiveBox#579]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [X] Request modification of existing behavior or design

## What is the problem that your feature request solves

In some cases an end user may want to just grab the WARC or just the PDF to be archived from a given site. Similar to the CLI, it would be handy if you could override the current config values on the page where you add a URL for archival. 

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

Ideally this would just be a small dropdown/hidden menu to "advanced options" or something similar with checkboxes for each archival type or other config value that are then passed to the backend to override the default config values. 

## What hacks or alternative solutions have you tried to solve the problem?

Nothing so far as it seems like a pretty quick change. I'll look into working on the change myself.

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [X] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [X] I'm willing to contribute dev time / money to fix this issue
 - [X] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
Thanks again for this @BlipRanger! I added a credit to you in the release notes of v0.5.0 https://github.com/ArchiveBox/ArchiveBox/pull/552#issue-528926837

Don't hesitate to open a ticket for any other suggestions in the future!
