### ISSUE TITLE
Move all vendored code into git submodules to make upgrading easier

### ISSUE THREAD

**Issue by pirate** [ArchiveBox/ArchiveBox#581]
Currently in we have all vendored libraries as copy pasted python files under `archivebox/vendor/*.py`.

This makes it difficult to upgrade these libraries, instead we should move them into git submodules that are clones of their original sources on github.

E.g. instead of `vendor/base32_crockford.py` it should be `vendor/base32_crockford/.git` and `vendor/base32_crockford/base32_crockford.py`.

- base32-crockford: https://github.com/jbittel/base32-crockford
- pocket-api: https://github.com/tapanpandita/pocket
- taggit: https://github.com/jazzband/django-taggit

In the future to upgrade these vendored libs it should be as simple as `cd archivebox/vendor/base32_crockford; git pull` and then committing the updated submodule commit to the  main repo.

**Comment by mAAdhaTTah** [comment]
I would also be open to just using `requests` directly instead of the Pocket API package. Didn't realize dealing with dependencies for deb packages was going to be such a chore. That said, the Pocket API package hasn't changed in a long time so may not need to be submoduled either (and all my experience w/ submodules has been terrible lol).

**Comment by pirate** [comment]
Pocket is not the only vendored dependency, and we're likely to want others in the future. We already use submodules for many other parts of the ArchiveBox packaging process, so it's familiar to us (`git pull --recurse-submodules` fixes almost all submodules headaches btw). The main benefit is that updating a vendored dependency goes from being a manual copy-paste process to just `cd vendor/<submodule>; git pull`.
