### ISSUE TITLE
PyPI need update

### ISSUE THREAD

**Issue by imlonghao** [ArchiveBox/ArchiveBox#585]
Hello,

The latest version of ArchiveBox is 0.4.24.

But seems you forget to update PyPI? It is still 0.4.21 since Aug 19, 2020

https://pypi.org/project/archivebox/

**Comment by pirate** [comment]
Didn't forget, it's intentional. The PyPI version is more stable than the latest version.

**Comment by imlonghao** [comment]
Closing as 0.5.3 is on pypi
