### ISSUE TITLE
Running `archivebox init` via pip install on Windows 10 triggers "File not found" error

### ISSUE THREAD

**Issue by DUOLabs333** [ArchiveBox/ArchiveBox#594]
I'm on Windows 10. I tried to install archivebox from pip, but after I did "npm install --prefix . 'git+https://github.com/ArchiveBox/ArchiveBox.git'", and did archivebox init, it gave a "File Not Found" Error

**Comment by pirate** [comment]
The latest v0.5 release isn't really fully stable on Windows 10 yet, but it should work at least to init.

Can you post the output of running `archivebox version` on Windows 10

**Comment by DUOLabs333** [comment]
No, no, I already fixed it (I didn't have a dependency). However, every
time I try to archive something, it gives me a Server 500 error. I tried
everything to fix it.

**Comment by pirate** [comment]
> Can you post the output of running archivebox version on Windows 10

**Comment by DUOLabs333** [comment]
Oh, I uninstalled archivebox-- that's why I closed the issue.

**Comment by DUOLabs333** [comment]
@pirate However, I am reinstalling it now, so I'll give you the info when I get it.

**Comment by DUOLabs333** [comment]
Though just a request: could you make it so that on every run it opens two Chrome windows? After a while of debugging, it get's confusing.

**Comment by DUOLabs333** [comment]
Also, here's the output, as of now:
The system cannot find the path specified.
The system cannot find the path specified.
[X] Unable to find a working version of Chrome/Chromium, is it installed and in your $PATH?

ArchiveBox v0.4.21

[01;37m[i] Dependency versions:[00;00m
[01;32m √ [00;00m PYTHON_BINARY          C:\Users\School\Downloads\Python39\python.exe                                v3.9.0         [01;32m valid [00;00m
[01;32m √ [00;00m DJANGO_BINARY          C:\Users\School\Downloads\Python39\Lib\site-packages\django\bin\django-admin.py v3.0.8         [01;32m valid [00;00m
[01;32m √ [00;00m CURL_BINARY            C:\WINDOWS\SYSTEM32\curl.EXE                                                 v7.55.1        [01;32m valid [00;00m
[01;32m √ [00;00m WGET_BINARY            C:\Users\School\Downloads\wget-1.20.3-win64\wget.EXE                         v1.20.3        [01;32m valid [00;00m
[01;31m X [00;00m SINGLEFILE_BINARY      .\single-file.CMD                                                            ?              [01;31m invalid [00;00m
[01;31m X [00;00m READABILITY_BINARY     .\readability-extractor.CMD                                                  ?              [01;31m invalid [00;00m
[01;32m √ [00;00m GIT_BINARY             C:\Users\School\Downloads\Git\cmd\git.EXE                                    v2.30.0.       [01;32m valid [00;00m
[01;32m √ [00;00m YOUTUBEDL_BINARY       C:\Users\School\Downloads\Python39\Scripts\youtube-dl.EXE                    v2020.12.29    [01;32m valid [00;00m
[01;31m X [00;00m CHROME_BINARY                                                                                       ?              [01;31m invalid [00;00m

[01;37m[i] Code locations:[00;00m
[01;32m √ [00;00m REPO_DIR               c:\users\school\downloads\python39\lib\site-packages                         128 files      [01;32m valid [00;00m
[01;32m √ [00;00m PYTHON_DIR             c:\users\school\downloads\python39\lib\site-packages\archivebox              20 files       [01;32m valid [00;00m
[01;32m √ [00;00m TEMPLATES_DIR          c:\users\school\downloads\python39\lib\site-packages\archivebox\themes\legacy 6 files        [01;32m valid [00;00m

[01;37m[i] Secrets locations:[00;00m
[01;32m √ [00;00m CHROME_USER_DATA_DIR   "C:\Users\School\AppData\Local\Chromium\User Data"                           28 files       [01;32m valid [00;00m
[01;33m - [00;00m COOKIES_FILE                                                                                        -              [01;33m disabled [00;00m

[01;37m[i] Data locations:[00;00m
[01;32m √ [00;00m OUTPUT_DIR             C:\Users\School\Downloads\archivebox                                         24 files       [01;32m valid [00;00m
[01;32m √ [00;00m SOURCES_DIR            C:\Users\School\Downloads\archivebox\sources                                 0 files        [01;32m valid [00;00m
[01;32m √ [00;00m LOGS_DIR               C:\Users\School\Downloads\archivebox\logs                                    0 files        [01;32m valid [00;00m
[01;32m √ [00;00m ARCHIVE_DIR            C:\Users\School\Downloads\archivebox\archive                                 0 files        [01;32m valid [00;00m
[01;32m √ [00;00m CONFIG_FILE            C:\Users\School\Downloads\archivebox\ArchiveBox.conf                         84.0 Bytes     [01;32m valid [00;00m
[01;32m √ [00;00m SQL_INDEX              C:\Users\School\Downloads\archivebox\index.sqlite3                           164.0 KB       [01;32m valid [00;00m
[01;32m √ [00;00m JSON_INDEX             C:\Users\School\Downloads\archivebox\index.json                              3.4 KB         [01;32m valid [00;00m
[01;32m √ [00;00m HTML_INDEX             C:\Users\School\Downloads\archivebox\index.html                              7.9 KB         [01;32m valid [00;00m

[01;33m[!] Warning: Missing 3 recommended dependencies[00;00m
    ! SINGLEFILE_BINARY: .\single-file.CMD (unable to detect version)
      [01;35mHint:[00;00m npm install --prefix . "git+https://github.com/pirate/ArchiveBox.git"
            or archivebox config --set SAVE_SINGLEFILE=False to silence this warning

    ! READABILITY_BINARY: .\readability-extractor.CMD (unable to detect version)
      [01;35mHint:[00;00m npm install --prefix . "git+https://github.com/pirate/ArchiveBox.git"
            or archivebox config --set SAVE_READABILITY=False to silence this warning

    ! CHROME_BINARY: unable to find binary (unable to detect version)

**Comment by DUOLabs333** [comment]
You can ignore that last part now, as I added chrome.exe to my PATH.

**Comment by DUOLabs333** [comment]
Also, even when I added a website, nothing appears in my "Snapshots" page.

**Comment by pirate** [comment]
Can you post the exact error output for the charmap error

**Comment by DUOLabs333** [comment]
Here it is:
[01;30m[i] [2021-01-02 23:10:06] ArchiveBox v0.4.21: archivebox add http://example.com/[00;00m
[01;30m    > C:\Users\School\Downloads\archivebox[00;00m

[01;32m[+] [2021-01-02 23:10:09] Adding 1 links to index (crawl depth=0)...[00;00m
    > Saved verbatim input to sources/C:\Users\School\Downloads\archivebox\sources\1609629009-import.txt
                                                                                                                                                                                                                                                    > Parsed 1 URLs from input (Plain Text)
                                                                                                                            > Found 1 new URLs not already in index

[01;30m[*] [2021-01-02 23:10:09] Writing 2 links to main index...[00;00m
                                                                                                                            √ C:\Users\School\Downloads\archivebox\index.sqlite3
                                                                                                                            √ C:\Users\School\Downloads\archivebox\index.json
                                                                                                                        Traceback (most recent call last):
  File "c:\users\school\downloads\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\school\downloads\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\School\Downloads\Python39\Scripts\archivebox.exe\__main__.py", line 7, in <module>
    from .cli import main
  File "c:\users\school\downloads\python39\lib\site-packages\archivebox\cli\__init__.py", line 122, in main
    run_subcommand(
  File "c:\users\school\downloads\python39\lib\site-packages\archivebox\cli\__init__.py", line 62, in run_subcommand
    module.main(args=subcommand_args, stdin=stdin, pwd=pwd)    # type: ignore
  File "c:\users\school\downloads\python39\lib\site-packages\archivebox\cli\archivebox_add.py", line 78, in main
    add(
  File "c:\users\school\downloads\python39\lib\site-packages\archivebox\util.py", line 111, in typechecked_function
    return func(*args, **kwargs)
  File "c:\users\school\downloads\python39\lib\site-packages\archivebox\main.py", line 565, in add
    write_main_index(links=all_links, out_dir=out_dir, finished=not new_links)
  File "c:\users\school\downloads\python39\lib\site-packages\archivebox\util.py", line 111, in typechecked_function
    return func(*args, **kwargs)
  File "c:\users\school\downloads\python39\lib\site-packages\archivebox\index\__init__.py", line 253, in write_main_index
    write_html_main_index(links, out_dir=out_dir, finished=finished)
  File "c:\users\school\downloads\python39\lib\site-packages\archivebox\util.py", line 111, in typechecked_function
    return func(*args, **kwargs)
  File "c:\users\school\downloads\python39\lib\site-packages\archivebox\index\html.py", line 62, in write_html_main_index
    atomic_write(join(out_dir, HTML_INDEX_FILENAME), rendered_html)
  File "c:\users\school\downloads\python39\lib\site-packages\archivebox\util.py", line 111, in typechecked_function
    return func(*args, **kwargs)
  File "c:\users\school\downloads\python39\lib\site-packages\archivebox\system.py", line 46, in atomic_write
    f.write(contents)
  File "c:\users\school\downloads\python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4c4' in position 7893: character maps to <undefined>

**Comment by pirate** [comment]
Looks like you're running 0.4.21 in that output, can you try with the latest v0.5 build?

```bash
git clone https://github.com/ArchiveBox/ArchiveBox
cd ArchiveBox
git checkout v0.5.0
git pull

pip install .

cd C:\Users\School\Downloads\archivebox
archivebox version
archivebox init
```

**Comment by DUOLabs333** [comment]
The 'pip install .' didn't work:
C:\Users\School\Downloads\archivebox-v5.0>pip install .
Processing c:\users\school\downloads\archivebox-v5.0
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\school\downloads\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\School\\AppData\\Local\\Temp\\pip-req-build-8vy5yxed\\setup.py'"'"'; __file__='"'"'C:\\Users\\School\\AppData\\Local\\Temp\\pip-req-build-8vy5yxed\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\School\AppData\Local\Temp\pip-pip-egg-info-ako9xyfi'
         cwd: C:\Users\School\AppData\Local\Temp\pip-req-build-8vy5yxed\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\School\AppData\Local\Temp\pip-req-build-8vy5yxed\setup.py", line 27, in <module>
        VERSION = json.loads((PACKAGE_DIR / "package.json").read_text().strip())['version']
      File "c:\users\school\downloads\python39\lib\json\__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "c:\users\school\downloads\python39\lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "c:\users\school\downloads\python39\lib\json\decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by DUOLabs333** [comment]
Though I didn't used the CLI, I just downloaded the code as a ZIP.

**Comment by pirate** [comment]
You downloaded the v0.5.0 branch as a zip and got that error? Can you double check that `package.json` is present in the downloaded code and contains valid json?

**Comment by DUOLabs333** [comment]
Here's the package.json code:
{
  "name": "archivebox",
  "version": "0.5.1",
  "description": "ArchiveBox: The self-hosted internet archive",
  "author": "Nick Sweeting <archivebox-npm@sweeting.me>",
  "license": "MIT",
  "scripts": {
    "archivebox": "./bin/archive"
  },
  "bin": {
    "archivebox-node": "./bin/archive",
    "single-file": "./node_modules/.bin/single-file",
    "readability-extractor": "./node_modules/.bin/readability-extractor",
    "mercury-parser": "./node_modules/.bin/mercury-parser"
  },
  "dependencies": {
    "@postlight/mercury-parser": "^2.2.0",
    "readability-extractor": "git+https://github.com/pirate/readability-extractor.git",
    "single-file": "git+https://github.com/gildas-lormeau/SingleFile.git"
  }
}

**Comment by DUOLabs333** [comment]
@pirate And JSONLint says it's valid.

**Comment by pirate** [comment]
Please try the latest v0.5.4 release and report back if you're still having problems and I can reopen the issue.
