### ISSUE TITLE
Bugfix: Disable third party requests (stop leaking private URLs to archive.org)

### ISSUE THREAD

**Issue by idolux** [ArchiveBox/ArchiveBox#598]
#### Describe the bug
After setting SAVE_ARCHIVE_DOT_ORG to "False" as described [in the README](https://github.com/ArchiveBox/ArchiveBox#caveats) archive.org still gets contacted. Therefore ArchiveBox leaks private URLs to archive.org

I would suggest to either disable archive.org in the webfrontend completely if SAVE_ARCHIVE_DOT_ORG is disabled or to introduce another option which disables current and new third party requests altogether.

#### Steps to reproduce
1. archivebox config --set SUBMIT_ARCHIVE_DOT_ORG=False
2. Save https://example.com
3. Open archive in the web frontend

#### Screenshots or log output

You can clearly see requests to archive.org in your browsers network tab.
![Screenshot_20210103_203655](https://user-images.githubusercontent.com/73033178/103487139-6fa6c180-4e03-11eb-855e-8ceaa94067de.png)

#### Software versions
 - ArchiveBox version:        latest docker image `archivebox/archivebox                                              latest              3f9e2703d63d        4 weeks ago         1.14GB`

**Comment by pirate** [comment]
> Open archive in the web frontend

What page did you open in the ArchiveBox UI that fired these requests?

**Comment by idolux** [comment]
This one https://archivebox.zervice.io/archive/1602401954.435773/index.html (of course locally on my own archivbox)

**Comment by pirate** [comment]
This is done and out in the new `v0.5.4` release. It will now hide the Archive.org iframe / preview on the Snapshot detail page if it was archived while `SAVE_ARCHIVE_DOR_ORG=False` was set.
