### ISSUE TITLE
Feature Request: Add possibility to recreate single html/pdf/screen

### ISSUE THREAD

**Issue by bash-stack** [ArchiveBox/ArchiveBox#600]
is there a simpler way than using "force overwrite" from gui  (e.g. FORCE_REINDEX env )  to easily regenerate a speific thing like pdf ?
( sometimes the file is there , so the add/update loop thinks "ok", but the file has no content since e.g. chromium is stuck rendering )
if so then it should be documented

**Comment by pirate** [comment]
`archivebox add --overwrite --extract=pdf https://example.com/some/url`

New in v0.5

**Comment by bash-stack** [comment]
you could have  a look at [cabbot](https://cabotapp.com/use/services.html) , since its in python as well and has partially the same function ( get something from somewere later or now and analyze content or headers or status codes etc.)
