### ISSUE TITLE
Bugfix: use sandbox in ifrme on archive pages

### ISSUE THREAD

**Issue by bash-stack** [ArchiveBox/ArchiveBox#606]
when visiting an /index.html of a site using js trackers and ads, 
the iframe should be used like  [described here ](https://www.w3schools.com/tags/att_iframe_sandbox.asp )

e.g. ` <iframe src="demo_iframe_sandbox.htm" sandbox></iframe> `

**Comment by pirate** [comment]
I think this will break a lot of the content being iframed, as lots of content uses plugin features like media/embed/etc. Why not just keep your 
 browser-level adblocker on and let it do the blocking?
