### ISSUE TITLE
Question: getting "Error: ENDED authentication_failed doesn't contain protocol(NUMBER)" when performing backend search

### ISSUE THREAD

**Issue by bmscmoreira** [ArchiveBox/ArchiveBox#609]
After searching for a word in the backend, logged in as admin, I get the error: 
`"Error: ENDED authentication_failed doesn't contain protocol(NUMBER)"`

I am using docker and two containers - one for archivebox, other for sonic backend search. I have used the sample docker-compose file from https://github.com/ArchiveBox/ArchiveBox/blob/master/docker-compose.yml having changed "SEARCH_BACKEND_PASSWORD" to my custom password.
In sonic configuration file I have changed "auth_password" to that same custom password, and inet to "0.0.0.0:1491".

Can someone help me debug this? Thank you.

**Comment by pirate** [comment]
Thanks for reporting @bmscmoreira we'll take a look. @jdcaballerov do you have any ideas?

**Comment by jdcaballerov** [comment]
@bmscmoreira Are you setting the env var `SEARCH_BACKEND_PASDWORD` to pass the new password to the ArchiveBox container?

**Comment by bmscmoreira** [comment]
Thank you @pirate and @jdcaballerov for your quick help. I was indeed missing the SEARCH_BACKEND_PASSWORD env variable in the archivebox service in my yml file.
May I suggest you add that line to line 26 here? - https://github.com/ArchiveBox/ArchiveBox/blob/master/docker-compose.yml

Thanks!

**Comment by jdcaballerov** [comment]
@bmscmoreira great!, yes I think it's useful to have it there so it's explicit.
