### ISSUE TITLE
Non blocking error: dpkg-query not finding bluealsa

### ISSUE THREAD

**Issue by Aondy39** [ArchiveBox/ArchiveBox#616]
When using any archivebox command I get the message `dpkg-query: no package found matching bluealsa`, it's not blocking execution but it seems to slow it down at the beginning.

I installed archivebox by following the manual steps given in the doc, I am running it on a raspberry pi 4B 8GB running raspbian buster.
The message appears at the beginning of the output of `archivebox version`, `archivebox server`, `archivebox config ...` and probably others archivebox commands.
According to the `archivebox version` command I am missing only these dependencies : `NODE_BINARY`, `SINGLEFILE_BINARY`, `READABILITY_BINARY`, `MERCURY_BINARY` and `RIPGREP_BINARY`. (just in case that may be a problem).

As I said this isn't blocking execution but as it seems to make it slow I'd like to fix it. Thank you.

**Comment by pirate** [comment]
It's probably a side effect of running chrome or youtube-dl at init time when we get their versions.

Can you try running these commands manually `chromium-browser --version` and `youtube-dl --version`.

**Comment by Aondy39** [comment]
`chromium-browser --version` also show the message `dpkg-query: no package found matching bluealsa` (and version is `86.0.4240.197 Built on Raspbian , running on Raspbian 10` if that can help) so yeah I guess it comes from chrome.
Running that command isn't that long so I guess it isn't the reason that's making archivebox take quite a long time to run, I guess I'll live with it, it isn't that bad after all and I don't think it is blocking any functionality.
(Just in case you might still want to know that, the youtube-dl version is `2019.01.17` and it doesn't show the error)

Thank you !
