### ISSUE TITLE
Question: Limit entries per page below 100

### ISSUE THREAD

**Issue by mcrosson** [ArchiveBox/ArchiveBox#618]
Is there a way to limit the number of entries shown on the list pages to under 100? I've got 1158 snapshots in ArchiveBox and am seeing large CPU use spikes when browsing pages. I'd like to limit the pagination to be 25 or 50 snapshots per page but can't seem to find and option to allow this change.

Any help would be greatly appreciated.

**Comment by pirate** [comment]
I understand why you want this, but we are more likely going to focus our dev time into improving the performance than adding bandaid features like this.

If it's so slow that it's unable to even load 100 links per page then something is very wrong and we should work on fixing that first. I suspect you're using a slow disk, are you using ArchiveBox on an SSD/HDD/SDCard?

**Comment by mcrosson** [comment]
> If it's so slow that it's unable to even load 100 links per page then something is very wrong and we should work on fixing that first. I suspect you're using a slow disk, are you using ArchiveBox on an SSD/HDD/SDCard?

It loads, it just takes longer than I'd prefer and causes a major cpu/ram spike during the loading process.

If there is a plan to focus on performance improvements then this is likely going to become a non-issue when those changes are made. I'm currently using ArchiveBox with a dedicated volume (ssd) on a DigitalOcean VPS with 8Gb RAM and 4 cores inside a Docker container.

**Comment by pirate** [comment]
Hmm that should be plenty of horsepower, although in my experience smaller DigitalOcean volumes have very low IOPS performance, which could be a factor.

In the meantime you can try using the static HTML index instead of the server:
```bash
archivebox list --html --with-headers > index.html
archivebox list --json --with-headers > index.json

python3 -m python3 -m http.server --bind 0.0.0.0 8000
open http://127.0.0.1:8000/index.html
```

**Comment by mcrosson** [comment]
TY for the info on how to make it a static html. I'll use that as a work around if needed while the performance updates are worked on.
