### ISSUE TITLE
Question: index.html completly gone?

### ISSUE THREAD

**Issue by zapp-brannigan** [ArchiveBox/ArchiveBox#619]
Hi. I just upgraded my archivebox to 0.5.3 via pip.
I realized that the index.html is no longer present, so i have to run "archivebox server" to access my archive. Unfortunately this is painfully slow on my raspberry. Is there a way to get the index.html back?

**Comment by pirate** [comment]
You can still use it, you just have to generate it when you need it, we switched to using a SQL db as the main index because keeping the html/json files up to date as the primary index was very slow and unreliable.
```bash
archivebox list --html --with-headers > index.html
archivebox list --json --with-headers > index.json
```
