### ISSUE TITLE
Possible to add link from web UI without logging in?

### ISSUE THREAD

**Issue by sean-perryman** [ArchiveBox/ArchiveBox#622]
My apologies if I missed this in the docs somewhere, or if I am searching for the wrong thing. Is it possible to enable to adding of links without logging in? I am using this on an internal network for users to grab publicly available web pages for inclusion in financial documentation. The ArchiveBox site is not publicly accessible to the Internet, only on the internal network. 

A potential fix would be to just create a single user and let anyone using the site log into that, but if possible I'd like it to work without logging in. 

Another potential would be to create a simple python webpage that would just send the command through to ArchiveBox and return a URL, but perhaps there is already a page available like this?

**Comment by pirate** [comment]
Yup, you can set that up with `PUBLIC_ADD_VIEW=True`, these are the three permissions options you can toggle depending on your needs:
```bash
archivebox config --set PUBLIC_INDEX=True
archivebox config --set PUBLIC_SNAPSHOTS=True
archivebox config --set PUBLIC_ADD_VIEW=True
```
