### ISSUE TITLE
Browser plugin that submits all surfed URLs to my archivebox to automate archiving

### ISSUE THREAD

**Issue by CodingSpiderFox** [ArchiveBox/ArchiveBox#631]
## Type 

 - [ ] General question or discussion
 - [X] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves
I don't want to manually type the URLs in my shell or run the export script regularly because I tend to for get it and I also want to save my pages right away. Also, I want Archivebox running on my NAS and not on my local computer.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
I want to have a plugin for at least Firefox and Chrome where I can
* configure the URL of my archivebox on my local network and my credentials for my archivebox
* have two modes: 
* a) it logs **every** URL I visited automatically to my archivebox and archivebox saves it right away
* b) a button in the addons toolbar that I can click which submits the current open URL in the current tab (only the current tab) to my archivebox and archivebox saves it right away

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [X] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [X] I'm willing to contribute dev time / money to fix this issue
 - [X] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
Duplicate: https://github.com/ArchiveBox/ArchiveBox/issues/577
