### ISSUE TITLE
Feature Request: Ability to tag URLs on the Add page and bulk add/remove tags on the list page

### ISSUE THREAD

**Issue by Wanty5883** [ArchiveBox/ArchiveBox#634]
## Type 

 - [ ] General question or discussion
 - [x] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves

Being able to add / remove / edit tags of multiple snapshots at once.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

I think this feature should work in two different ways.
The first one from the add menus itself, so it is possible to add multiple URL at once with an option to give them tags (one or more). Thus beind able to add multiple URL based on the same subject / tag.
The second way by the snapshot page, selecting the pages to add / remove / edit one or more tag at once.

## What hacks or alternative solutions have you tried to solve the problem?

Adding tags one by one (snapshots)

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [x] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [ ] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
Definitely a good idea, we could have a field to add/remove multiple tags on the snapshot admin page (`/admin/core/snapshot/`) near the search bar.

**Comment by Wanty5883** [comment]
Wouldn't it be easier to do that from the snapshot page ? There is already selection boxes for pages.

What about from the add page as well ?  So it is possible to bulk add pages from the same topic ?
The ability of doing this later on is definitly great but being able to do that in a single step process would make it a lot easier as well. Basically adding a tag field on the add page. Maybe making this possible with specific permission only ?

**Comment by pirate** [comment]
Ah yes, definitely also possible to add a tag field to the `/add` page. That's an easy ticket that anyone can pick up, I'll add the `help wanted` tag to this issue.

**Comment by pirate** [comment]
Both feature requests here are done in v0.6 (see #660 for more):

- bulk editing of tags from Snapshot list is possible ![image](https://user-images.githubusercontent.com/511499/113671999-1873ef80-9685-11eb-98a2-7143f950fd19.png)
- tagging URLs directly from the add page and add CLI is possible <img width="45%" src="https://user-images.githubusercontent.com/511499/112715186-5a4aac00-8eb5-11eb-9b9d-8052db466188.png" align="top"/><img width="45%" src="https://user-images.githubusercontent.com/511499/112715241-967e0c80-8eb5-11eb-94b5-b5dfb915238b.png" align="top"/>

These will be out soon with the next release v0.6.
