### ISSUE TITLE
Feature Request: Tag management

### ISSUE THREAD

**Issue by Wanty5883** [ArchiveBox/ArchiveBox#641]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves

Not being able to sort the tags list in other than the tag page. Which is a significant problem as the tag list scale up

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

From the tag panel we able to sort the tags by name, ID or slug, this should change the way tags are sorted in the other pages of ArchiveBox.

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [x] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [ ] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by Wanty5883** [comment]
I'll use this ticket to ask a question so I don't have to open a second one.

I am using ArchiveBox in a docker container. It is really slow for me, not archiving a web page, but just the browsing of ArchiveBox itself, changing tags, going to another page, etc.
Did I miss something obvious ? How can I diagnose this issue so I can learn how to fix it ?

**Comment by pirate** [comment]
v0.5 is quite slow due to some architectural issues, we're going to improve the speed in v0.6 significantly hopefully.

Make sure you're running it on an SSD, it relies heavily on fast disk access more than CPU or RAM.

**Comment by Wanty5883** [comment]
The docker container runs on a VM but the snapshot content does store in a HDD. Basically only the `/data/sources` and `/data/archive` does point to the HDD.

What about the tag list in the webpage overall ? Planning to change that as well ? Having a lot of tags and not being able to sort them in different ways is kinda hard as it does scale up

**Comment by pirate** [comment]
Yeah, improving tagging + organization in general is definitely on the roadmap, but to be perfectly honest it's 2nd priority compared to performance and stability.

I think we have a long way to go with performance, and there's some deep refactoring needed to go from the old "run a bunch of bash commands sequentially and store the results in text files" approach to the new "manage a pool of async headless browser workers that read tasks off a message queue" design.

If people want to contribute tagging improvements to the UI or data model, I'm happy to discuss potential features + implementations, but in the meantime I recommend people use other curation/organization tools for their links, and use archivebox as the data storage layer. e.g. with a Pocket/Pinboard free account, or a self-hosted equivalent like Wallabag.

**Comment by pirate** [comment]
You can filter Snapshots by tag in the latest version using the panel on the right, does that cover your needs? You can also use the search box.

![image](https://user-images.githubusercontent.com/511499/113667421-caf48400-967e-11eb-8804-3fc2643505ae.png)

I don't quite understand the proposed feature as you described it, you want the tag sort order from the Tag admin to be sticky across all pages?
