### ISSUE TITLE
Feature Request: Remove CDN

### ISSUE THREAD

**Issue by idolux** [ArchiveBox/ArchiveBox#644]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves
The client requests javascript files from third party CDNs.

https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js
https://code.jquery.com/jquery-3.2.1.slim.min.js

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
Remove CDNs and serve the remote files locally instead

Alternative: Config option to toggle the CDN

## What hacks or alternative solutions have you tried to solve the problem?
Block CDN with browser addon

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [x] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

**Comment by pirate** [comment]
Hmm how do these CDN assets keep getting added back, this is like the 3rd time I've removed them...

**Comment by pirate** [comment]
Fixed in af6561b. It will be released in the next version v0.6 soon.
