### ISSUE TITLE
Feature Request: Disable original preview

### ISSUE THREAD

**Issue by idolux** [ArchiveBox/ArchiveBox#645]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves
The archive overview connects to the archived content and therefore leaks the users IP address. It would be good to completely avoid third party connections once archived.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
Add toggle to disable preview of "Original".

## What hacks or alternative solutions have you tried to solve the problem?
Block third party requests with browser addon

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [x] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

**Comment by pigmonkey** [comment]
I'd also prefer to not hit Archive.org until I actually choose to load the Archive.org snapshot, so I'd want the option of disabling that preview as well.

Personally I do not find much value in the previews. I'd be happy if that part of the header was just replaced by a list of the snapshot methods and the date they were last updated. That would avoid this problem entirely. A `USE_PREVIEWS = False` option would probably be pretty simple to implement.

**Comment by pirate** [comment]
`SAVE_ARCHIVE_DOT_ORG` already disables the Archive.org preview, but it's all or nothing and disables saving to Archive.org entirely, not just for the preview.

I can add a `USE_PREVIEWS = False` option in the next release, but beware the Snapshot index pages are static html, not dynamic django templates, so you'll have to trigger them to be rerendered manually to update them (either by clicking `Pull Title`, `Pull`, or running `archivebox update` on them).

**Comment by pirate** [comment]
I've added this option in v0.6.3 8ebf3e2]
