### ISSUE TITLE
Question: Resume pending snapshots? 

### ISSUE THREAD

**Issue by wonderingwombat** [ArchiveBox/ArchiveBox#646]
I loaded a large list of URLs into an ArchiveBox instance running on Docker. I had to restart the computer that ArchiveBox was running on. Now most of the snapshots show a status of Pending. From what I can see these snapshots haven't started downloading again after the restart. 
Is there a way of resuming these downloads in bulk for all snapshots that are pending?

**Comment by pirate** [comment]
Just go to the admin UI, check the ones you want to resume, and click the "Archive" button.

Or run the `archivebox update` command to do it via the CLI:
```bash
docker run -v $PWD:/data -it archivebox update
# or
docker-compose run archivebox update
```

**Comment by CookiePLMonster** [comment]
For anyone else stumbling upon this issue right now, like I did: At the time of writing this comment, v0.7.3 names this option **Pull**.
