### ISSUE TITLE
Documentation: document how to pull bookmarks from Firefox Sync

### ISSUE THREAD

**Issue by khimaros** [ArchiveBox/ArchiveBox#648]
## Wiki Page URL

https://github.com/ArchiveBox/ArchiveBox/wiki/Quickstart#2-get-your-list-of-urls-to-archive

## Suggested Edit

document how to pull bookmarks and/or history from the Firefox Sync server.

this enables the user to simply bookmark pages they want to archive on their desktop and mobile browser and they will automatically be archived by archivebox.

here's what worked for me.

determine your Firefox Sync client id:

```
$ python3 -m pip install PyFxA

$ fxa-client --bearer -u <YOUR EMAIL> \
    --account-server https://api.accounts.firefox.com/v1 \
    --oauth-server https://oauth.accounts.firefox.com/v1
# ---- BEARER TOKEN INFO ----
# User: <YOUR EMAIL>
# Scopes: profile
# Account: https://api.accounts.firefox.com/v1
# Oauth: https://oauth.accounts.firefox.com/v1
# Client ID: <YOUR CLIENT ID>
# ---------------------------
```

import all of your bookmarks into archivebox:

```
$ git clone https://github.com/eNote-GmbH/syncclient

$ cd syncclient

$ python3 -m pip install -e .

$ python3 syncclient/main.py -u <YOUR EMAIL> --client-id <YOUR CLIENT ID> \
    get_records bookmarks \
        | jq '.[].payload | fromjson | select(.type == "bookmark") | .bmkUri)' \
        | archivebox add
```

this also works with a self hosted Firefox Sync server by setting the env var `TOKENSERVER_URL="https://<YOUR SYNC SERVER>/token"`. you can configure this to run on a regular schedule eg. via cron.

with a bit of work, you could make this only archive bookmarks with a specific tag or folder.

**Comment by kominoshja** [comment]
Note: This requires disabling 2FA while setting it up

**Comment by kominoshja** [comment]
When I issue `python3 syncclient/main.py -u <YOUR EMAIL> --client-id <YOUR CLIENT ID> get_records bookmarks`, I get something like
```
"6J***********3Vk"
"3_***********Iw7"
"U1***********ah"
```
therefore, jq fails. Did something change in the new version of the repo/syncserver?

**Comment by pirate** [comment]
Going to close this for now, I'll add a link to this issue from the README in case it helps ppl in the future trying to set this up.
