### ISSUE TITLE
Bugfix: Error: Search Backend only searching default admin search fields

### ISSUE THREAD

**Issue by alsokpisz** [ArchiveBox/ArchiveBox#654]
#### Describe the bug

**Bug**:
The bug occurs when I attempt to search any query. An error message appears saying: `"Error from the search backend, only showing results from default admin search fields -Error:[Errno -3] Temporary failure in name resolution."`

If the search query is a word in the title of a website, it will return results with that word in it.
If it is only in the wget snapshot of the item, it will not return that item.

_Context_:
I am running ArchiveBox using on  Windows 10 with docker-compose and have launched the web UI which I am successfully accessing at `http://127.0.0.1:8000`. As far as I can tell, all the snapshots are functional and there are no pending links. The output directory is on an external hard drive, but there have been no issues reading/writing from this drive (except for speed, though I can't tell if that's just how the Django Web UI is or not).

_Relevant Info_:
Bug seems similar to @jdcaballerov comment when search enabled but backend failed in [his testing](https://github.com/ArchiveBox/ArchiveBox/pull/543#issuecomment-730849375) (see screenshot 4).

#### Steps to reproduce

`mkdir archivebox && cd archivebox`
`curl -O https://raw.githubusercontent.com/ArchiveBox/ArchiveBox/master/docker-compose.yml`

Edit the docker-compose yml's `volumes` section to read: 
```
volumes:
  - ./data:/data
  - D:\\archivebox:/mnt/d/archivebox
```
(unsure if external drive-specific setup needed to reproduce, so wanted to include)

Open a Windows Terminal in administrator mode, navigate to `D:/archivebox/`, open a Git Bash tab and run the following:

`> docker-compose up -d`
`> docker-compose run archivebox init`
`> docker-compose run archivebox manage createsuperuser`
`> docker-compose run archivebox add 'https://www.dailydot.com/parsec/fandom/dieselpunk-steampunk-beginners-guide/'`

Navigate to `http://127.0.0.1:8000` and search "beginners' (see screenshot 1). Because it is in the title, it will show up. The error message will also show up.

Search "biopunk" (see screenshot 2). Even though it is in the wget file, it will not show up (see screenshot 3). The error message will show up. I have not done extensive testing on whether different filetype snapshots will get searched or not, but I don't think it picks any of them up if they are not in title.

#### Screenshots or log output

**Screenshot 1:**
![image](https://user-images.githubusercontent.com/36479341/107894062-40e03880-6ee3-11eb-9720-2ee36c32cc9a.png)

**Screenshot 2:**
![image](https://user-images.githubusercontent.com/36479341/107894100-640ae800-6ee3-11eb-8e23-dea3c8034ec8.png)

**Screenshot 3:**
![image](https://user-images.githubusercontent.com/36479341/107894175-a0d6df00-6ee3-11eb-9bf9-36f49bcde6a0.png)

**Screenshot 4:**
![image](https://user-images.githubusercontent.com/36479341/107894343-2fe3f700-6ee4-11eb-90ea-29dd05301d99.png)

#### ArchiveBox version

```logs
ArchiveBox v0.5.6
Cpython Linux Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.28 x86_64 (in Docker)

[i] Dependency versions:
 √  ARCHIVEBOX_BINARY     v0.5.6          valid     /usr/local/bin/archivebox
 √  PYTHON_BINARY         v3.9.1          valid     /usr/local/bin/python3.9
 √  DJANGO_BINARY         v3.1.3          valid     /usr/local/lib/python3.9/site-packages/django/bin/django-admin.py
 √  CURL_BINARY           v7.64.0         valid     /usr/bin/curl
 √  WGET_BINARY           v1.20.1         valid     /usr/bin/wget
 √  NODE_BINARY           v15.8.0         valid     /usr/bin/node
 √  SINGLEFILE_BINARY     v0.1.14         valid     /node/node_modules/single-file/cli/single-file
 √  READABILITY_BINARY    v0.1.0          valid     /node/node_modules/readability-extractor/readability-extractor
 √  MERCURY_BINARY        v1.0.0          valid     /node/node_modules/@postlight/mercury-parser/cli.js
 √  GIT_BINARY            v2.20.1         valid     /usr/bin/git
 √  YOUTUBEDL_BINARY      v2021.02.04.1   valid     /usr/local/bin/youtube-dl
 √  CHROME_BINARY         v88.0.4324.146  valid     /usr/bin/chromium
 √  RIPGREP_BINARY        v0.10.0         valid     /usr/bin/rg

[i] Source-code locations:
 √  PACKAGE_DIR           22 files        valid     /app/archivebox
 √  TEMPLATES_DIR         3 files         valid     /app/archivebox/templates

[i] Secrets locations:
 -  CHROME_USER_DATA_DIR  -               disabled
 -  COOKIES_FILE          -               disabled
```

`>docker -version`
`Docker version 20.10.2, build 2291f61`

`>docker-compose --version`
`docker-compose version 1.27.4, build 40524192`

**Comment by jdcaballerov** [comment]
@alsokpisz The error message describes a mis configured dns in the docker compose setup. If the search backend can't be queried the search will only occur in the url and title, the admin fields.

**Comment by pirate** [comment]
@alsokpisz as @jdcaballerov mentioned this is likely a DNS resolving issue inside your docker-compose network. Docker on macOS is infamous for having container DNS issues, so I wouldn't be surprised if Docker on Windows is plagued by similar bugs.

To confirm that Sonic is up and running and accessible from the archivebox container, can you run these python commands manually and report back what output you get:

```bash
docker-compose run archivebox /usr/local/bin/python3
>>> import socket
>>> HOST = 'sonic'
>>> PORT = 1491
>>> with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
...     s.connect((HOST, PORT))
...     s.sendall(b'Hello, world')
...     data = s.recv(1024)
...
>>> print('Received', repr(data))
Received b'CONNECTED <sonic-server v1.3.0>\r\n'
>>>
```

**Comment by alsokpisz** [comment]
Two arrangements, one based on an empty sonic folder which was created by the docker-compose setup, and then I will also try your suggested arrangement.

**Arrangement 1:**
```
--archivebox
   | --docker-compose.yml
   | --data
        | -- archive, logs, sources, A...B.conf, A...B.conf.bak, index.sqlite3
   | --etc
        | -- sonic
              | -- config.cfg (folder)
                    | -- config.cfg (file)
```
**Results:**   
No selectable checkboxes on the left hand side of the UI. Everything is much much faster. Queries no longer produce the error message but produce the same functionality (still only searching title fields) (see screenshot 1). Missing buttons in top right (Archive, Re-archive, etc).

Observing the Docker containers currently running, despite the terminal saying that the Sonic container was started (screenshot 2), my Docker Desktop shows it has stopped (screenshot 3). This is confirmed by the `> docker ps` (screenshot 4). 

**Arrangement 2:**
```
--archivebox
   | -- docker-compose.yml
   | --data
        | -- archive, logs, sources, A...B.conf, A...B.conf.bak, index.sqlite3
   | --etc
        | -- sonic
              | -- config.cfg (file)
```
Several errors in the terminal (see screenshot 5). 
Is the tree I've set up above not correct?

**Screenshots**
**Screenshot 1.**
![image](https://user-images.githubusercontent.com/36479341/107990299-04671800-6f89-11eb-816c-0b05c696f354.png)
Screenshot 2.
![image](https://user-images.githubusercontent.com/36479341/107990450-5c058380-6f89-11eb-8ee8-8f59119a0788.png)

Screenshot 3.
![image](https://user-images.githubusercontent.com/36479341/107990482-69bb0900-6f89-11eb-9890-0372fd5c7799.png)

Screenshot 4.
![image](https://user-images.githubusercontent.com/36479341/107990517-77708e80-6f89-11eb-8dc1-b2eec6f17cff.png)

Screenshot 5.
![image](https://user-images.githubusercontent.com/36479341/107991052-a9362500-6f8a-11eb-8f8e-44ef3416abd0.png)

**Comment by pirate** [comment]
Inside of docker is always linux, so having a Windows path in this docker command doesn't make sense: `docker-compose run archivebox C:/Python37/python`

Run it verbatim as I posted above, and paste in the script line by line (don't make a file):
```bash
docker-compose run archivebox /usr/local/bin/python3

>>> ... paste in lines above here
```

**Comment by alsokpisz** [comment]
![image](https://user-images.githubusercontent.com/36479341/108021344-369d6780-6fd3-11eb-9d22-77e9a2f3686d.png)
Causes a subargument issue.

**Comment by pirate** [comment]
try `docker-compose run archivebox shell`

**Comment by alsokpisz** [comment]
**Result:**
`Received b'CONNECTED <sonic-server v1.3.0>\r\nENDED '`
I tried this when `docker ps` still shows both services running.

**Comment by pirate** [comment]
Great! That means both DNS and the TCP socket to the sonic container are working. Try this next in `docker-compose run archivebox shell`:

```python3
>>> from sonic import SearchClient
>>> from archivebox.config import SEARCH_BACKEND_HOST_NAME, SEARCH_BACKEND_PORT, SEARCH_BACKEND_PASSWORD, SONIC_BUCKET, SONIC_COLLECTION
>>> with SearchClient(SEARCH_BACKEND_HOST_NAME, SEARCH_BACKEND_PORT, SEARCH_BACKEND_PASSWORD) as querycl:
>>>    print(querycl.query(SONIC_COLLECTION, SONIC_BUCKET, 'test'))
```

**Comment by alsokpisz** [comment]
**Results:**
`['3ad870d4-82b5-4974-a6ce-ee8cc6a235fa', '5d6734a5-1b9d-418a-a215-8e1e1dbdb8e5', '74696c7d-4421-46b8-8f35-9f1c9537ee1b', 'fca5096f-13da-4d94-8afd-5d742d7b3fb4', '6f009e8d-947a-4fa7-94d7-f21a94c2b525']`

**Comment by alsokpisz** [comment]
Seems like any page which is a .pdf, or .jpg causes this error during the index command:
```
[*] <link.pdf>
[X] An Exception ocurred reading the indexable content='utf-8' codec can't decode byte 0xb5 in position 10: invalid start byte:
[*] <link>
[*] <link>
[X] The search backend threw an exception=ERR invalid_format(PUSH <collection> <bucket> <object> "<text>" [LANG(<locale>)]?)
:
[*] <link>
[*] <link>
```
And then it hangs. 

After removing all the .pdf links and .jpg which I suspected was causing some problems it kept causing the following error:
```[*] <link>
[X] The search backend threw an exception=ERR invalid_format(PUSH <collection> <bucket> <object> "<text>" [LANG(<locale>)]?)
:
[*] <link>
[*] <link>
*terminal hangs*
```
Now there are no errors when I run the re-index command, but it will still spend ages on random pages. Notably stuff with 'weirder' components like live webcam feeds or something. I removed those one by one until it managed to get through the 80ish bookmarks in less than 10 minutes. 

The returned results were the same as the admin search, but public index still didn't work.

**Comment by jdcaballerov** [comment]
@alsokpisz the public search view is not connected to the search backend for security and performance reasons.

**Comment by alsokpisz** [comment]
Well that's that then I suppose. 
Is there a way to set a "timeout" per link on the `docker-compose run archivebox update --index-only` command? So it will skip links it spends more than say, a minute trying to index?

**Comment by pirate** [comment]
Ok this should be somewhat improved in f67a5a2. It will be out with the next v0.6 release soon.
You can also try it early by adding this line to your docker-compose config: `build: https://github.com/ArchiveBox/ArchiveBox.git#dev`.

Comment back here if you're still having issues with indexing failures/hanging and I'll reopen the issue.

**Comment by jdqw210** [comment]
> ```python
> print('Received', repr(data))
> ```

This is what I get when I follow the troubleshooting: 
`>>> print('Received', repr(data))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'data' is not defined
`

Anyone know what I'm doing incorrectly?

**Comment by pirate** [comment]
Looks like you messed up the indentation, make sure to copy paste that whole block together above, or remove the extra newline before that print to be doubly sure. @jdqw210
