### ISSUE TITLE
Archiving inline images

### ISSUE THREAD

**Issue by bobberb** [ArchiveBox/ArchiveBox#661]
Dear ArchiveBox community,

I am attempting to migrate my archive from Wallabag to this platform. One feature I cannot seem to grasp is image saving.

 In Wallabag, I have the option to (by default) link to images or, as I prefer for achival purposes, save images on a page with modified readability output replacing the hot link with a local copy and automatically editting the output of readability to avoid linking outside my network. 

Does such a feature exist with ArchiveBox?

Thank you.

**Comment by pirate** [comment]
The Wget and Singlefile extractors in ArchiveBox both do as you describe, downloading all images locally and replacing the URLs to point to the local versions.

You can toggle this behavior for wget with the `archivebox config --set SAVE_WGET_REQUISITES=True`/`False` option.

**Comment by bobberb** [comment]
I see my error. When I long press on Android it was giving me the original
URL but I see now when I copy-link-location it presents the base encoding.

Sorry to bother.
