### ISSUE TITLE
Feature Request: ...

### ISSUE THREAD

**Issue by indahud** [ArchiveBox/ArchiveBox#665]
## Type 

 - [x] Propose a brand new feature

## What is the problem that your feature request solves
If this feature implemented then we can view keywords with the links and filter links according to the keywords.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
There should be option to add some category keywords with link and filter the links according to the keywords. For example if I am adding some Github repo in the ArchiveBox, I want to know what exactly it does when I see that link later. And filter the links with keywords. Adding some keywords with link will solve that problem.

## What hacks or alternative solutions have you tried to solve the problem?
This feature is available in Pocket. We can add different keywords to the articles. Keywords can also filter articles with specific keywords.

## How badly do you want this new feature?

 - [x] It's an urgent deal-breaker, I can't live without it

---

 - [x] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue

**Comment by pirate** [comment]
This is called tags and it already exists in ArchiveBox.

Related tickets:

- https://github.com/ArchiveBox/ArchiveBox/issues/641
- https://github.com/ArchiveBox/ArchiveBox/issues/634
