### ISSUE TITLE
Bug: Fresh Ubuntu 20.04 Install, Error: [X] The search backend threw an exception=[Errno -3] Temporary failure in name resolution:

### ISSUE THREAD

**Issue by dohlin** [ArchiveBox/ArchiveBox#667]
#### Describe the bug
Clean docker-compose install on Ubuntu 20.04, running

`docker-compose run archivebox add 'https://example.com'`

results in the following error:

`[X] The search backend threw an exception=[Errno -3] Temporary failure in name resolution:`

DNS works fine and no errors are reported in 'archivebox --version'.  Error occurs on all URL's; there is nothing 'temporary' about it.

#### Screenshots or log output

https://imgur.com/a/hAaCLBV

#### ArchiveBox version

Latest v0.5.6

Any ideas on what could be causing this?  Thank you!

**Comment by pirate** [comment]
Please post the full verbatim output of `'archivebox --version`.

Also run this command and report back any errors: `docker-compose run --rm archivebox update --index-only`.

**Comment by dohlin** [comment]
`docker-compose run --rm archivebox --version`:

```
dave@Bookmarks01:~/archivebox$ docker-compose run --rm archivebox --version
Starting archivebox_sonic_1 ... done
Creating archivebox_archivebox_run ... done
ArchiveBox v0.5.6
Cpython Linux Linux-5.8.0-45-generic-x86_64-with-glibc2.28 x86_64 (in Docker)

[i] Dependency versions:
 √  ARCHIVEBOX_BINARY     v0.5.6          valid     /usr/local/bin/archivebox                                                   
 √  PYTHON_BINARY         v3.9.1          valid     /usr/local/bin/python3.9                                                    
 √  DJANGO_BINARY         v3.1.3          valid     /usr/local/lib/python3.9/site-packages/django/bin/django-admin.py           
 √  CURL_BINARY           v7.64.0         valid     /usr/bin/curl                                                               
 √  WGET_BINARY           v1.20.1         valid     /usr/bin/wget                                                               
 √  NODE_BINARY           v15.8.0         valid     /usr/bin/node                                                               
 √  SINGLEFILE_BINARY     v0.1.14         valid     /node/node_modules/single-file/cli/single-file                              
 √  READABILITY_BINARY    v0.1.0          valid     /node/node_modules/readability-extractor/readability-extractor              
 √  MERCURY_BINARY        v1.0.0          valid     /node/node_modules/@postlight/mercury-parser/cli.js                         
 √  GIT_BINARY            v2.20.1         valid     /usr/bin/git                                                                
 √  YOUTUBEDL_BINARY      v2021.02.04.1   valid     /usr/local/bin/youtube-dl                                                   
 √  CHROME_BINARY         v88.0.4324.146  valid     /usr/bin/chromium                                                           
 √  RIPGREP_BINARY        v0.10.0         valid     /usr/bin/rg                                                                 

[i] Source-code locations:
 √  PACKAGE_DIR           22 files        valid     /app/archivebox                                                             
 √  TEMPLATES_DIR         3 files         valid     /app/archivebox/templates                                                   

[i] Secrets locations:
 -  CHROME_USER_DATA_DIR  -               disabled                                                                              
 -  COOKIES_FILE          -               disabled                                                                              

[i] Data locations:
 √  OUTPUT_DIR            6 files         valid     /data                                                                       
 √  SOURCES_DIR           4 files         valid     ./sources                                                                   
 √  LOGS_DIR              0 files         valid     ./logs                                                                      
 √  ARCHIVE_DIR           1 files         valid     ./archive                                                                   
 √  CONFIG_FILE           159.0 Bytes     valid     ./ArchiveBox.conf                                                           
 √  SQL_INDEX             204.0 KB        valid     ./index.sqlite3 
```

`docker-compose run --rm archivebox update --index-only`:

```
dave@Bookmarks01:~/archivebox$ docker-compose run --rm archivebox update --index-only
Starting archivebox_sonic_1 ... done
Creating archivebox_archivebox_run ... done
[i] [2021-03-20 05:12:14] ArchiveBox v0.5.6: archivebox update --index-only
    > /data

[*] Indexing url: https://example.com in the search index 


[X] The search backend threw an exception=[Errno -3] Temporary failure in name resolution:
```

**Comment by pirate** [comment]
Seems like your sonic container is failing for some reason, perhaps it's unable to write to the volume provided to it, or it's missing the config file?

Can you follow the troubleshooting steps we went through in this issue and report back: https://github.com/ArchiveBox/ArchiveBox/issues/654#issuecomment-779387819

**Comment by dohlin** [comment]
Seems like a similar issue, as I saw several of the same errors the other user did (particularly [screenshot1](https://user-images.githubusercontent.com/36479341/107991052-a9362500-6f8a-11eb-8f8e-44ef3416abd0.png)), but I'm getting a different result at the end.  I too had to hard-code the docker-compose.yml file sonic section, as /home/dave/archivebox/etc/sonic/config.cfg was just an empty folder.  I downloaded the config.cfg file to this folder, updated the docker-compose.yml sonic section, and archivebox was able to run again but still produces the same error.  Here is the output from the python commands requested, where I seem to get a different final result than the other bug report.

https://imgur.com/a/5rL8tdy

**Comment by pirate** [comment]
Cool, that narrows it down to an issue with the config file causing your sonic container to not able to start Can you post your docker compose file and a screenshot of the directory structure that you have the config file sitting in?

**Comment by dohlin** [comment]
/home/dave/archivebox/docker-compose.yml:

`# Usage:
#     docker-compose up -d
#     docker-compose run archivebox init
#     echo "https://example.com" | docker-compose run archivebox archivebox add
#     docker-compose run archivebox add --depth=1 https://example.com/some/feed.rss
#     docker-compose run archivebox config --set PUBLIC_INDEX=True
# Documentation:
#     https://github.com/ArchiveBox/ArchiveBox/wiki/Docker#docker-compose

version: '3.7'

services:
    archivebox:
        # build: .
        image: ${DOCKER_IMAGE:-archivebox/archivebox:latest} 
        command: server 0.0.0.0:8000
        stdin_open: true
        tty: true
        ports:
            - 8000:8000
        environment:
            - USE_COLOR=True
            - SHOW_PROGRESS=False
            - SEARCH_BACKEND_ENGINE=sonic
            - SEARCH_BACKEND_HOST_NAME=sonic
            - SEARCH_BACKEND_PASSWORD=SecretPassword
        volumes:
            - ./data:/data
        depends_on:
            - sonic
    
    # Run sonic search backend
    sonic:
        image: valeriansaliou/sonic:v1.3.0    
        ports:
            - 1491:1491
        environment:
            - SEARCH_BACKEND_PASSWORD=SecretPassword
        volumes:
            - ./etc/sonic/config.cfg/config.efg:/etc/sonic.cfg
            - ./data:/var/lib/sonic/store/

    # Optional Addons: tweak these examples as needed for your specific use case

    # Example: Run scheduled imports in a docker instead of using cron on the
    # host machine, add tasks and see more info with archivebox schedule --help
    # scheduler:
    #    image: archivebox/archivebox:latest
    #    command: schedule --foreground --every=day --depth=1 'https://getpocket.com/users/USERNAME/feed/all'
    #    environment:
    #        - USE_COLOR=True
    #        - SHOW_PROGRESS=False
    #    volumes:
    #        - ./data:/data
    
    # Example: Put Nginx in front of the ArchiveBox server for SSL termination
    # nginx:
    #     image: nginx:alpine
    #     ports:
    #         - 443:443
    #         - 80:80
    #     volumes:
    #         - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    #         - ./data:/var/www

    # Example: run all your ArchiveBox traffic through a WireGuard VPN tunnel
    # wireguard:
    #   image: linuxserver/wireguard
    #   network_mode: 'service:archivebox'
    #   cap_add:
    #     - NET_ADMIN
    #     - SYS_MODULE
    #   sysctls:
    #     - net.ipv4.conf.all.rp_filter=2
    #     - net.ipv4.conf.all.src_valid_mark=1
    #   volumes:
    #     - /lib/modules:/lib/modules
    #     - ./wireguard.conf:/config/wg0.conf:ro
    
    # Example: Run PYWB in parallel and auto-import WARCs from ArchiveBox
    # pywb:
    #     image: webrecorder/pywb:latest
    #     entrypoint: /bin/sh 'wb-manager add default /archivebox/archive/*/warc/*.warc.gz; wayback --proxy;'
    #     environment:
    #         - INIT_COLLECTION=archivebox
    #     ports:
    #         - 8080:8080
    #     volumes:
    #         ./data:/archivebox
    #         ./data/wayback:/webarchive
    `

Screenshot of the previously-empty /home/dave/archivebox/etc/sonic/config.cfg folder (that now contains the config.cfg _file_):

https://imgur.com/a/MMA6oaF

**Comment by pirate** [comment]
Delete the whole `etc` folder for simplicity, and start over with the config file just in your root folder next to `docker-compose.yml`:
```
curl https://raw.githubusercontent.com/ArchiveBox/ArchiveBox/master/etc/sonic/config.cfg > sonic.cfg
```

Then change the sonic volumes to this:
```
services:
    ...
    
    sonic:
        ...
        volumes:
            - ./sonic.cfg:/etc/sonic.cfg:ro
            - ./data/sonic:/var/lib/sonic/store
```
Make sure you have `:ro` on the end of the config file line, and make sure you're using `./data/sonic` for sonic's state, not `./data`.

**Comment by dohlin** [comment]
I followed those steps, created a folder called "sonic" inside the ./data folder, and it still didn't work...so then I removed the sonic docker container (docker rm xx) so it was recreated at next run and now it appears to be working.  Thanks!!

**Comment by dohlin** [comment]
@pirate This is an unrelated question, but while I have your attention is there any way to override the timestamps shown in the 'date added' field in the web UI?  i.e. set the 'default' timezone to CST or something like that rather than UTC.  No problem if not just couldn't find any docs related to it.  Thanks!

**Comment by pirate** [comment]
They will always be stored as UTC internally, but we're planning on implementing localization using your browser's timezone to display them in a future version. Just haven't gotten around to it yet.

**Comment by dohlin** [comment]
> They will always be stored as UTC internally, but we're planning on implementing localization using your browser's timezone to display them in a future version. Just haven't gotten around to it yet.

Awesome.  Thanks so much!
