### ISSUE TITLE
How to search for site URL?

### ISSUE THREAD

**Issue by voarsh2** [ArchiveBox/ArchiveBox#673]
I have various sites and urls for different parts of a site indexed, however, searching for URLs don't seem to work, at all.
The only thing what works with search using the UI is the website title, which isn't good enough for me.

Any work arounds?

**Comment by pirate** [comment]
URL search works but it has to be exact, this is a known issue fixed in v0.6 (coming soon).

**Comment by saywebsolutions** [comment]
you can also use filesystem tools like grep, fzf, etc. to search the archive html and text files directly which will get you full text search and a lot of flexibility

**Comment by voarsh2** [comment]
> URL search works but it has to be exact, this is a known issue fixed in v0.6 (coming soon). If you want you can try running archivebox from the pre-release v0.6 `debug-toolbar` branch to get this fix.

I eagerly await this fix then... because I'm typing almost exact URLs (base domain) with no results....


> you can also use filesystem tools like grep, fzf, etc. to search the archive html and text files directly which will get you full text search and a lot of flexibility

Uh, yeah, but I'd rather use the UI... especially for bulk update, tag, delete, etc.

**Comment by voarsh2** [comment]
Just thought I would add that [site]/public search performs much better than the native djanjo admin/site snapshot screens. How come?
I want to delete/rescan, etc but I can't search in admin area effectly to select 30+ records, but no problem on public version.

**Comment by pirate** [comment]
We implemented the public search ourselves, but the admin search is django's built-in search function that's really difficult to customize. Still trying to figure how we can override it to use our algo instead.

**Comment by voarsh2** [comment]
> We implemented the public search ourselves, but the admin search is django's built-in search function that's really difficult to customize. Still working out the best way to override it to use our algo instead.

I figured that. At least make /public/ have the ability to remove content? That would get around that issue. 
Because I can't manage content at /public/ and it's the only place I can actually search properly.

**Comment by pirate** [comment]
Cant do that, public is read-only, but what you can do is search on public to find the timestamp, then search using the timestamp on private until v0.6 is released.

**Comment by pirate** [comment]
This is officially fixed in v0.6 (which is on dev/master). I'll be pushing the Docker image, pip package, apt package, etc release versions soon.
