### ISSUE TITLE
Feature Request: User defined backend timeout

### ISSUE THREAD

**Issue by virtualadept** [ArchiveBox/ArchiveBox#698]
## Type 

 - [X] Request modification of existing behavior or design

## What is the problem that your feature request solves

When doing a huge search query (like to batch add tags) the following error is thrown

`Error from the search backend, only showing results from default admin search fields - Error: Command '['rg', '--type-add', 'ignore:*.{css,js,orig,svg}', '-ilTignore', '-e', 'BIGSEARCHSTRING', '/data/archive']' timed out after 60 seconds`

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
A config option to increase the timeout from 60 seconds to a user defined amount.

## How badly do you want this new feature?

 - [X] It would be nice to have eventually

**Comment by pirate** [comment]
Good idea, done: 3276434.

**Comment by virtualadept** [comment]
Current size of my archive is 3684 items.  My sqlite db is about 49 megs.  Its writing to a xcp-ng vhd on a 4 drive zfs pool with not-very-fast HDDs  Since I have all of my VM's on that pool, it has to compete with writes, so that has to be considered.

However, until a recent update, rendering the main page was super-super slow, like almost browser-timeout levels of slow.
Since the latest release the web interface has been really snappy and responsive. It was a pretty shocking change (like I thought something was broken on the backend after the update).

Tagging 1k+ item, with exception of the db timeout, with everything considered was pretty fast.

If you want any more data let me know.  I can also run benchmarking software if you write it for me (I'm not a coder) :)
