### ISSUE TITLE
Question: Performance Comparison docker based vs bare metal

### ISSUE THREAD

**Issue by asitemade4u** [ArchiveBox/ArchiveBox#702]
Hi,
Thank you for Archive Box, which is outstanding -- basically exactly what I was looking for.
My only concern is ArchiveBox performance when executed within a docker environment. Notably. it does not seem to be using all CPU available nor memory.
Is there a better track record with bare-metal installations? Can ArchiveBox take full advantage of all processing power available and work in parallel?
Best,
Stephen

**Comment by pirate** [comment]
Going to close this in favor of our existing issue about parallel archiving / performance: https://github.com/ArchiveBox/ArchiveBox/issues/91
Please subscribe to that one if you want updates.

The summary is: parallel archiving is semi-doable and safe already right now, but not perfect (you might encounter "database locked" errors if you try too many threads). Just run multiple `archivebox add` commands at once.
