### ISSUE TITLE
Feature Request: prioritize types of pages

### ISSUE THREAD

**Issue by dominictarr** [ArchiveBox/ArchiveBox#712]
## Type 

 - [ ] General question or discussion
 - [x] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves

Often static sites have thumbnail images in the article and a link to large image.
It would be great to get those images as soon as possible, before other html pages on the site.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
option to prioritize file types that can be known to be leaves - they won't add more links to the database

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [x] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [ ] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [ ] I like ArchiveBox so far / would recommend it to a friend
 - [x] I am evaluating ArchiveBox but havn't decided if it solves my problems
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
I think you're trying to use archivebox for something it's not designed primarily for. It's not built to archive entire domains recursively, there are better tools for that. You can use a scraper or spider to find the urls you want to archive in whatever order you like, then pipe them into archivebox once you have them in the order you want them archived.

**Comment by dominictarr** [comment]
thanks. I was recommended archivebox when I asked about a better `wget -kr 1` do you know something that might suit me better?

**Comment by pirate** [comment]
Maybe Photon? https://github.com/s0md3v/Photon

**Comment by pirate** [comment]
You can find many more alternatives here too: https://github.com/ArchiveBox/ArchiveBox/wiki/Web-Archiving-Community#other-archivebox-alternatives
