### ISSUE TITLE
Feature Request: URL Tree View 

### ISSUE THREAD

**Issue by dominictarr** [ArchiveBox/ArchiveBox#714]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves
Main view shows a list of all URLs known, which is likely pages from a single site.
for to use archivebox to get content for offline viewing, it would be better to have the top level show the sites have been indexed, and then click to see the urls inside of that. So that I can start browsing by looking at the sites available, instead of choosing from every URL

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
Tree like view of URLs downloaded

## What hacks or alternative solutions have you tried to solve the problem?
Just clicking next... but it's not a workable solution

## How badly do you want this new feature?

 - [x] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [ ] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
Probably not going to build this, archivebox's main use case is not archiving a single domain, you're better off using something like Sitesucker for that.

**Comment by dominictarr** [comment]
sitesucker appears to be osx only...
can you recommend anything that works on linux or windows? btw, in practice I'd want less than a single domain.
For example, wikipedia or wikitravel, but just topics I'm interested in or that are useful, getting everything would take too long.

**Comment by pirate** [comment]
Check out some of these: https://github.com/ArchiveBox/ArchiveBox/wiki/Web-Archiving-Community#other-archivebox-alternatives
