### ISSUE TITLE
Archiving web design

### ISSUE THREAD

**Issue by raphaelbastide** [ArchiveBox/ArchiveBox#715]
I am trying to archive websites for their design characteristics, my goal is to have a copy containing every asset in order to replicate exactly the graphic characteristics of a page (CSS, fonts, images…). I am wondering if ArchiveBox is the tool I need.

After a first tests, issues appear for fonts and ajax calls (or image lazy loading): When I try to archive this [web page](http://fondsinternational.com/) for instance with all archive methods selected, none of the result fits to my goal. The fonts seams to be downloaded for singlefile only and the images appears to be not downloaded at all, in fact, they keep their original URL. Do you have any tips for me to archive this kind of page?

Other website causing similar issues
- http://www.guydecointet.org
- http://edwardthomson.net/
- http://www.dougkoellmer.com/

**Comment by pirate** [comment]
Looks like the fonts are saved: https://demo.archivebox.io/archive/1618859543.748595/fondsinternational.com/wp-content/themes/Empire%20II/assets/fonts/

Wget gets them, so you'll find them in the wget output folder `./archive/<timestamp>/domainhere.com/.../fonts`.

You may prefer https://ArchiveWeb.page and https://ReplayWeb.page for higher fidelity archives though.

**Comment by raphaelbastide** [comment]
Thank you for your answer @pirate!
