### ISSUE TITLE
Question: Is there a way to retry a failed archive method on an existing snapshot?

### ISSUE THREAD

**Issue by Karunamon** [ArchiveBox/ArchiveBox#716]
Imagine archiving a website that discriminates against wget or curl as clients (sadly common). The usual fix for this is to change your user agent to omit any mention of those tools.

Once I've changed the user agent configuration setting, is there a way to retry only the failed archive method on an otherwise successful snapshot without rerunning the whole thing?

**Comment by pirate** [comment]
It will never re-archive with methods that have previously succeeded, it only retries ones that failed previously. Just click Pull in the UI, or run `archivebox update https://example.com/snapshot/url/here`.

![image](https://user-images.githubusercontent.com/511499/115290793-f321bf80-a121-11eb-97b0-9d2cde6bae04.png)

**Comment by Karunamon** [comment]
Aha, wasn't aware of that behavior. Thanks!
