### ISSUE TITLE
Question: privacy pop up

### ISSUE THREAD

**Issue by Wanty5883** [ArchiveBox/ArchiveBox#723]
Do you have a way to remove the privacy pop up ?
Can it is be done automatically. Having to do this manually sounds like too much time required.
Probably a redundant question, but I haven't been able to find what I am looking for.

Thanks !

**Comment by pirate** [comment]
Closing as duplicate of: https://github.com/ArchiveBox/ArchiveBox/issues/175 please follow that issue for updates.
