### ISSUE TITLE
Question: Using the CLI to reach the API of a hosted instance

### ISSUE THREAD

**Issue by vorpalhex** [ArchiveBox/ArchiveBox#743]
I host ArchiveBox on my homelab server, and it works great. I'd like to be able to easily push new links to it from the archivebox cli, but have the actual scraping/work done by the homelab server. 

I can't for the life of me find anything in the docs about how to configure this. I'm not sure if I'm missing something obvious or if this hasn't been added yet - but the ability to easily add links from remotes over API would be really appreciated.

**Comment by pirate** [comment]
Why not just use SSH?

**Comment by vorpalhex** [comment]
1. using docker so it's going to end up quite a bit longer
2. not all my remotes have ssh access to the homelab
3. different user pool on the web interface than ssh users

**Comment by pirate** [comment]
Ah well there's no way to do it at the moment aside from SSH.

You can use the REST API but it's not stable yet, (see `archivebox/core/views.py:Add`). There's a ticket here for tracking REST API progress: https://github.com/ArchiveBox/ArchiveBox/issues/496

**Comment by pirate** [comment]
Also keep in mind, Archivebox is primarily designed to *pull* links from sources periodically. So if you can expose the URLs you want to add as an RSS feed, as a file on a network share, as a URL, or anything else like that, you can configure the homelab server to poll those sources periodically with `archivebox schedule`.
