### ISSUE TITLE
Bug: Doesn't properly archive some websites.

### ISSUE THREAD

**Issue by ETechTechnologies** [ArchiveBox/ArchiveBox#751]
Some websites do not save correctly, meaning some parts don't work. Consider changing the archiving method to match the one used on archive.org (which works properly). The one you use now is good for static websites but isn't great for other sites.

**Comment by pirate** [comment]
AB uses a variety of methods but not all sites can be archived perfectly. If more than 10-15% of sites are failing with all methods then please post the specific urls and screenshots of any error output or broken layouts.


See here: https://github.com/ArchiveBox/ArchiveBox/issues/328

And feel free to check out alternative tools from our wiki, in particular https://archive web.page.
