### ISSUE TITLE
Feature Request: Delete some part of archiving

### ISSUE THREAD

**Issue by Dryusdan** [ArchiveBox/ArchiveBox#755]
## Type 

 - [ ] General question or discussion
 - [x] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves

Actually I archiving lot of website (~ 2455) but after lot of usage, I don't use PDF page, readibility, screenshot, mercury or headers.
I disable theses feature, but it don't remove already saved file. Found it and remove it on filesystem is easy, but the index page or json aren't updated to remove it.

For my case, just remove screenshot can save 4GB of disk space usage.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
I think the best way is open an update each index.json and index.html on snapshot and remove file / folder.

But it is very very long :/ 

## What hacks or alternative solutions have you tried to solve the problem?
I have not tried this change but 
```
find -name output.pdf - delete
for folder in $(ls ./)
do
    cat $folder/index.json | jq 'del(.history.pdf)' > $folder/index.json.tmp 
    mv $folder/index.json.tmp $folder/index.json
done
```
Look work without updating index.html

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [x] It would be nice to have eventually

---

 - [ ] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
Just click "Pull Title" in the UI and it will update the indexes of all the snapshots you checked. No need to do it manually.

**Comment by Dryusdan** [comment]
Thanks, I hadn't thought of that :) 

But it only pull title (and udpate index), not remove all of screenshot.png (for exemple)... 
And in UI, there keep the "screenshot.png" colorized 
![Capture d’écran 2021-05-26 à 17 41 32](https://user-images.githubusercontent.com/4410431/119690049-a54b5600-be49-11eb-98f1-6539c1f47a55.png)

**Comment by pirate** [comment]
You have to delete the ArchiveResult entries first, sorry I thought you already did that for some reason. Go to the `Log` page and filter by type for `Screenshot` then check and delete them. Then go back to the Snapshots list and pull title again.

**Comment by Dryusdan** [comment]
That good, it work

Thank :)

**Comment by bastidest** [comment]
Piggy-backing off this issue: Is there a way to delete an archive result from the filesystem + the index through the web interface?

**Comment by pirate** [comment]
No, at the moment to delete ArchiveResults and not whole Snapshots you need to do it separately though the filesystem and UI. We may add this in the future but it's not in the queue at the moment.

**Comment by bastidest** [comment]
Would you consider accepting a PR for this?

**Comment by pirate** [comment]
Definitely! You can take a look at how we implement the UI snapshot delete button for inspiration.
