### ISSUE TITLE
How can I use archive box as a service ?

### ISSUE THREAD

**Issue by PKUFlyingPig** [ArchiveBox/ArchiveBox#756]
I want to use Archivebox as a service of my app, and my app is deployed using docker-compose. So when how can I app in the docker to run something like "docker-compose run archivebox add xxxx' ?

**Comment by jrmgx** [comment]
I spent the day on a similar problematic and did not find anything conclusive,
if someone have an idea, let me know

**Comment by pirate** [comment]
There are REST endpoints you can use (see here for more: https://github.com/ArchiveBox/ArchiveBox/issues/496), or you can share the `/var/run/docker.sock` with your app to let it execute CLI commands inside the archivebox container using `docker-compose run --rm archivebox add ...`.
