### ISSUE TITLE
Question: properly save PDF from URLs without .pdf extension

### ISSUE THREAD

**Issue by philippemilink** [ArchiveBox/ArchiveBox#762]
(perhaps this is a feature request)

If I save a web page serving a PDF file (such as https://www.debian.org/doc/manuals/packaging-tutorial/packaging-tutorial), the "wget > HTML" preview displays the listing of the folder containing the save. I have to go through the "See all files..." and browse the folder tree to get the file. Moreover, since the file has no extension, the browser considers it as `application/octet-stream` file, and doesn't open it directly in the browser as it does normally. 

With URL including the `.pdf` extension, the preview works fine.

Is there a way to make it work for all URLs serving PDF files (with and without the extension) ?

If not, may I suggest a feature adding the `pdf` extension to the saved file (and the saved URL) if it appears the saved file is a PDF ? (it could be done by looking at the `Content-Type` header)

**Comment by pirate** [comment]
Likely not going to fix this, as we want to avoid rewriting the URLs to be different in the filesystem than how they are served (as much as possible).

Debian should serve .pdf on the end or redirect to a .pdf file instead of serving PDF mime content from a non-PDF extension.
