### ISSUE TITLE
Feature Request: Ability to merge multiple webpages into one snapshot

### ISSUE THREAD

**Issue by Victor239** [ArchiveBox/ArchiveBox#771]
## Type 

 - [ ] General question or discussion
 - [x] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves
I was viewing a XenForo forum thread and wanted to be able to archive all of it. 

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
I don't expect ArchiveBox to support identifying the next thread page and archiving it, and being able to do this for all forum software. 

Instead I'd like if I could manually supply all the thread page URLs I'm interested in, and for ArchiveBox to be able to merge these webpages into a single snapshot. If you're interested in doing a full thread download I'd be very happy with that too but I also don't want it to be a maintenance burden. The merge-all-webpages-into-a-single-snapshot functionality is sufficient for now. 

## What hacks or alternative solutions have you tried to solve the problem?
Archiving each webpage of a thread separately.

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [x] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

**Comment by pirate** [comment]
Probably not going to implement this as it would break a lot of the core assumptions in the data layer model. I'd recommend using tags to group related pages instead.

I the future we may include user scrips that can unroll many forum threads on a single page before archiving, which should also help solve this need.
