### ISSUE TITLE
Don't use -t in docker examples (other than init)

### ISSUE THREAD

**Issue by jgoerzen** [ArchiveBox/ArchiveBox#780]
## Wiki Page URL

https://github.com/ArchiveBox/ArchiveBox/wiki/Docker#usage-1

## Suggested Edit

Docker gives "not a TTY" when piping data into a command that uses -t.  Just use -i, instead of -it, on any command that's got data being piped in.

**Comment by pirate** [comment]
Ah yeah, I had already fixed this in the README a while back but forgot to fix the Wiki, thanks!
