### ISSUE TITLE
Feature Request: Support for Postgres

### ISSUE THREAD

**Issue by rain0r** [ArchiveBox/ArchiveBox#787]
## Type 

 - [X] Request modification of existing behavior or design

I - and assume some other users -  would really like to run archivebox with Postgresql as database backend. There is already a little discussion about it in #601. Whatever the pros and cons of postgres are or which database is better suited ... I don't think this should be up to debate. Django provides support for multiple backends and I think archivebox should use this feature. Additionally, I think it shouldn't be much work to get postgres (and maybe even mysql) up and running. Personally, I got it working with commenting some stuff out but that feels just hacky.

A tool / script to migrate from one db backend to another would be extra nice, but I could live without that.

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [X] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [ ] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [X] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
Not going to work on this. Limited time, and I don't think it's a good idea for the long-term retrievability of this project.

If you want to maintain a fork with PG support you're welcome to, but I'm not open to mainlining it for at least another year or two. (until we finish the message passing refactor).

**Comment by pirate** [comment]
I just want to add that I understand as a user this is a frustrating response, but as a maintainer with limited resources to spend on this project, this is a hard decision I have to make to remove some development cost, ease long-term support burden that additional DB support would incur, and keep the project moving in the right long-term direction.

*If* you manage to get PG support working really well in a fork (without breaking `archivebox oneshot` and other edge cases that rely on SQLite), then maybe I'd be open to reviewing it (but I suspect it's harder than you think given how much we rely on `index.sqlite3` existing in its current form).
