### ISSUE TITLE
SAVE_ARCHIVE_DOT_ORG=True by default, not mentioned early in the description of the software

### ISSUE THREAD

**Issue by mdarnold1** [ArchiveBox/ArchiveBox#789]
Thanks for writing this software.

However isn't the typical use case of this software for personal archives, not public ones (which can be achieved through other tools)?

As someone who's just started using this "self-hosting" software I would expect that this option is off by default, and the possibility that it can send data elsewhere would be mentioned prominently (i.e. near the top of the description).

**Comment by pirate** [comment]
Please see this thread here for an explanation: https://news.ycombinator.com/item?id=26859845

As mentioned in the thread, instructions on how to set `SAVE_ARCHIVE_DOT_ORG=False` are in the README in 3 places, most notably here, where it has an entire section: https://github.com/ArchiveBox/ArchiveBox#archiving-private-content
