### ISSUE TITLE
Could ArchiveBox be used to automatically download new Twitter posts?

### ISSUE THREAD

**Issue by holygamer** [ArchiveBox/ArchiveBox#806]
I would like to be able to enter a Twitter account URL and have the program automatically archive all new Tweets by that person as soon as the Tweets are made. Is that possible as is or could I mod the program to do that? What would the limitations be if monitoring thousands of Twitter accounts like that at once? If I bought a single server would it be able to handle it?

Would Twitter block the IP used by the server with the ArchiveBox software because of making too many requests to view pages at the same time as each other? If so, could I queue requests so many Tweets aren't backed up all at the same time as as each other.

**Comment by pirate** [comment]
`archivebox schedule --every=hour https://twitter.com/...`

You'll have to try it and see, I don't know the answers for that kind of scale.

**Comment by mhfowler** [comment]
I would also be curious to see this experiment with instagram. Although an instagram-specific archiver may be necessary.

**Comment by pirate** [comment]
Closing as stale.
