### ISSUE TITLE
Question: Change url of snapshot via CLI

### ISSUE THREAD

**Issue by TheAnachronism** [ArchiveBox/ArchiveBox#816]
In the admin page of a snapshot in the Web UI one can change the url this snapshot points to. I'm currently trying to automate some things and I need to do that from the CLI.
I guess I have to do something with the django shell but I'm very inexperienced in python, so I'm quite lost here.

**Comment by Jonirico11** [comment]
What are like pyton

Pada tanggal Sen, 2 Agu 2021 00:21, TheAnachronism ***@***.***>
menulis:

**Comment by pirate** [comment]
Hmmm why are you doing that? It don't think it should even be possible in the UI...

**Comment by TheAnachronism** [comment]
Well I'm archiving stuff from a restricted website which makes a huge mess if I try to do that with the custom browser settings (because I have archivebox running as a docker container on an ubuntu server).
So my current workaround is to save the page with the [singlefile](https://github.com/gildas-lormeau/SingleFile) browser extension, host that html on a temporary webserver and archive that webserver url. Then replace the url for that snapshot in the webui.
As you can see its a bit of work to do that, so I automated the entire process from uploading it to the web server to adding it to archivebox. Now I just want to replace the temporary webserver url with the original restricted website url.

![image](https://user-images.githubusercontent.com/32616088/127785092-d78941a4-5e00-44ae-9765-302af7bff479.png)

In the webui on the admin page of a snapshot you can change this here.

Previously I wanted to avoid the entire temp webserver thing by trying to import those downloaded html files. But because there currently is no actual import workflow and the browser setup was a bit too much for me, I went with this weird solution.

**Comment by pirate** [comment]
Hmm I would recommend archiving the original URLs to create the Snapshot entries, letting them fail, then just replacing the `singlefile.html` entries in the filesystem with your original singlefiles, instead of trying to re-archive the singlefile html through your rehosting server.

**Comment by TheAnachronism** [comment]
Mhh ok
The only problem now is, that I'd need the filepath, where that new "failed" archive is created, so that I can replace the files with my manual versions.
`archivebox add ...` has a huge output...

**Comment by pirate** [comment]
The path is just the timestamp of the snapshot, if you have the url you can get the timestamp easily with `archivebo list` or by looking in the `index.sqlite3` file directly.

**Comment by TheAnachronism** [comment]
I'll try that with `archivebox list --csv=timestamp <url here>`
