### ISSUE TITLE
Question: Is there a way to set configurations for youtube-dl?

### ISSUE THREAD

**Issue by mhfowler** [ArchiveBox/ArchiveBox#828]
Is there a way to set configurations for youtube-dl? That will be used by archivebox when it runs save_media on a link?

For example, I would like to change the "--max-filesize=750m". 

I also might like to get rid of "--write-subs"

Is there anyway I can manually set the arguments used by archivebox for youtube-dl commands?

**Comment by WantToLearnJapanese** [comment]
You can set arguments to pass by YOUTUBEDL_ARGS.
