### ISSUE TITLE
Youtube saves the media as mkv and thus cannot be played inside a browser

### ISSUE THREAD

**Issue by tio-trom** [ArchiveBox/ArchiveBox#844]
https://archive.trom.tf/archive/1631457418.479981/www.youtube.com/watch@v=8iTrm7Wnhas.html

This is an example. I wonder why it saves as mkv since that cannot play in the browser, thus making it difficult to use the link as a reference.

Also, as you can see, it doesn't save the youtube page properly.

Cheers!

**Comment by pirate** [comment]
You can change this by tweaking the archivebox config option `YOUTUBEDL_ARGS`. By default it saves in the highest quality format that's available directly so that it doesn't waste CPU re-encoding video.

**Comment by tio-trom** [comment]
How about the fact that it cannot save the youtube page properly?

**Comment by pirate** [comment]
Seems like you disabled singlefile, which has much better fidelity for youtube: https://archive.trom.tf/archive/1631457418.479981/index.html
