### ISSUE TITLE
Feature Request: version listing for the Docker Hub page

### ISSUE THREAD

**Issue by MPeti1** [ArchiveBox/ArchiveBox#845]
## Type 

 - [x] General question or discussion
 - [ ] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves

I usually run ArchiveBox in Docker or similar, and when there's a new version I always find it hard to find it on Docker Hub page among all the versions.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

Provide version summaries at the top of the Docker Hub page of the project, like other projects do.
An example is Alpine Linux's page on DH: https://hub.docker.com/_/alpine/
Here they provide a version summary, in which every row is like a channel, that shows which version codes point to the same container at the moment.

With ArchiveBox it could go such as this:
- a row for the latest stable release (where as of now `0.6`, `0.6.2` and `latest` would point to the same container)
- a row for the previous stable minor release (where there could be 0.6.1, and others if there are more which points to it and makes sense)
- a row for the previous stable major release (0.5 and 0.5.6)
- a row for the state of the dev branch
- a row for the latest version that's name starts with `sha-`, though I'm not sure what are these.
I don't know if and how this can be automated, but seeing how many big projects do this I would assume that it's possible.

## What hacks or alternative solutions have you tried to solve the problem?

I tried searching with ctrl+f on the tags listing for `sha-` and only look at those releases which weren't highlighted, and go to the next page until I find the latest stable version by number.

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [x] It would be nice to have eventually

---

 - [ ] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
It's painful because right now the Docker homepage is just the github readme verbatim, I don't really want to build a whole pipeline to generate a separate Docker readme.

I think this is mostly only a problem when we have a big gap in time between releases. For now I recommend using the Github releases page instead of Dockers to find the latest tag.

**Comment by MPeti1** [comment]
Thank you, but an other reason I wanted to recommend this is that this way it would be possible to set version 0.6 or just 0 in the docker-compose file, so the container could be upgraded somewhat easier (maybe automatically) when a new version comes out, but so that it only auto-updates to bugfix versions, and not to versions where there are bigger changes.

I think this does not actually need a Dockerhub page different from the Github one, but only that you use multiple tags when building the container (like one tag for all 3 parts of the version code).

**Comment by pirate** [comment]
It should already do that right now, we have a new autotag pipeline in 0.6 that tags with 0.6.3 and 0.6 (but not 0 on its own).

**Comment by MPeti1** [comment]
oh, that's good to know, thank you!
could you include this in the readme (or a wiki article)?
