### ISSUE TITLE
Feature Request: Support saving local webpages or PDFs

### ISSUE THREAD

**Issue by Victor239** [ArchiveBox/ArchiveBox#846]
## Type 

 - [ ] General question or discussion
 - [x] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves
Sometimes ArchiveBox fails to archive a URL, but in those instances I'm still able to use the SingleFile browser extension or save the webpage as a PDF. If I open the SingleFile or PDF in my browser, I'd like ArchiveBox to be able to archive these webpages via the local file instead and then I can manually edit the URL that is associated with these webpages later if desired.

Also in some cases there are PDFs I've obtained from emails, or webpages which are already offline, but I'm unable to import them into ArchiveBox. This leaves me having to maintain a separate archive for these files in Zotero, which is a headache and makes me want to just pair things down to one archive program. 

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
Instead of just HTTP URLs, ArchiveBox should also accept filenames such as `file:///home/user/Downloads/Rupert.html` and be able to archive these pages.

**Comment by pirate** [comment]
Not possible given the security model. ArchiveBox is essentially running in a separate virtual machine and does not have access to the local filesystem or `localhost:...` urls.
