### ISSUE TITLE
Question: How to run server in Docker on a Read-Only archive?

### ISSUE THREAD

**Issue by zblesk** [ArchiveBox/ArchiveBox#855]
I have a pretty big archive by now (several hundred gigabytes). 
I'm backing it up to a server which doesn't usually run apps, only hold data. 
However, since the data are already there, I'd like to be able to use that server as a mirror. 

I've tried simply starting up the server and designating the volume in the compose file as read-only; however, that throws errors immediately and quits. 

How can I do this? 

Edit: just in case my motivation isn't clear: since the primary function of the server is data backup, I can't have the mirror instance modifying the data. They should only be modified on the primary instance and synced.

**Comment by pirate** [comment]
I don't think this is possible currently, but if you set the permissions configs https://github.com/ArchiveBox/ArchiveBox#-web-ui-usage all to False + set a password it should prevent any modifications from being made via the web UI. The db lock file may still be changed, but those changes can be safely overwritten on the next backup.

**Comment by pirate** [comment]
I'm going to close this as it's not feasible in the current design. But might I suggest, *inception begins* statically archiving your ArchiveBox instance and hosing the HTML output of that? :wink:
