### ISSUE TITLE
The Demo is down

### ISSUE THREAD

**Issue by iaeiou** [ArchiveBox/ArchiveBox#869]
Hello there,

the Demo (https://demo.archivebox.io) is actually unavailable.

Here is the error message:

```
 Error 1016 Ray ID: 6979192b1a0e4a7a • 2021-10-01 22:23:56 UTC
Origin DNS error
What happened?

You've requested a page on a website (demo.archivebox.io) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (demo.archivebox.io). 
```

**Comment by iaeiou** [comment]
[Another demo](https://archive.sweeting.me/) is also down, which is evoked [in the doc](https://github.com/ArchiveBox/ArchiveBox/wiki/Usage#ui-usage)

**Comment by quinncomendant** [comment]
[Demo](https://demo.archivebox.io/) is [still down](https://ss.strco.de/SCR-20260220-uo6p.png).
