### ISSUE TITLE
Question: why does the webserver display a wget HTML page differently than the raw file.

### ISSUE THREAD

**Issue by cvsickle** [ArchiveBox/ArchiveBox#879]
I'm trying to use wget to store offline pages that frequently get updated so that I can access the old page after it's been updated. It seems to work as expected, grabbing all of the images and storing them locally, but the webserver isn't displaying the images (and other page elements) properly. When I open the index.html file directly, the browser displays the page correctly though.

For example, I'm saving: https://lexyslotd.com/guide/mod-installation-part-1/

And here is a comparison of the two methods (webserver on the left, raw file on the right): 

[Comparison 1](https://www.dropbox.com/s/br284c6wk82zxri/ArchiveBoxComparison1.png?dl=0)

[Comparison 2](https://www.dropbox.com/s/d9aj3okv9v2k31u/ArchiveBoxComparison2.png?dl=0)

Note especially the images and the navigation tools on the right side of the site. You can see from the URL that this is the same file from the same snapshot, and this behavior in consistent between browsers, so I'm left to assume something is up with how the webserver is serving the pages. Are there any config options I should be looking into to fix this? Having to locate the specific file to access is much more of a pain than using the ArchiveBox UI to serve the page.

For reference, I have ArchiveBox running in a Docker container on my Synology NAS. Using the current "dev" image tag. Any help or explanation would be greatly appreciated. This seems like a very useful project if I can just get these small things worked out.

**Comment by pirate** [comment]
Looks like it's refusing to run JS due to MIME type mismatches which makes sense. Probably not something thats going to change anytime soon, sorry. There is work in progress to add better header replaying, but for now if you need higher fidelity I recommend ArchiveWeb.page + ReplayWeb.page instead.
