### ISSUE TITLE
Question: Can you possibly merge the folders?

### ISSUE THREAD

**Issue by rmfkdehd** [ArchiveBox/ArchiveBox#887]
I have an archive1 folder on pc1 and an archive2 folder on pc2.  Can I just merge these two folders into the archive3 folder?  This is a pretty important issue for me because I'm running out of storage space.

**Comment by pirate** [comment]
Yes, you can merge them in one go assuming there are no conflicting timestamps in both. Just drag `archive/*` from one into `archive/` in the other, then run `archivebox init` and it will import all the new links automatically into the index.

**Comment by pirate** [comment]
closing this as answered but if you have any follow-up questions just comment back here, I'll still see them.
