### ISSUE TITLE
Question: ...Can't run command  "archivebox update -t timestamp..."

### ISSUE THREAD

**Issue by blogdemoi** [ArchiveBox/ArchiveBox#888]
Hello,

I installed Archivebox on my Manjaro laptop with 'Docker compose' and it is working fine, I did a few snapshots.

However a snapshot didn't complete successfully and in the web GUI I have this message:

> Snapshot [1636303242.308281] exists in DB, but resource 1636303242.308281/singlefile.html does not exist in snapshot dir yet.
> 
> Maybe this resource type is not availabe for this Snapshot,
> or the archiving process has not completed yet?
> 
>  run this cmd to finish archiving this Snapshot
> archivebox update -t timestamp 1636303242.308281

So I cd inside my archivebox folder and ran: `archivebox update -t timestamp 1636303242.308281` but received an error: 

>   ~/archivebox ❯ archivebox update -t timestamp 1636303242.308281
> zsh: command not found: archivebox

Am I missing something?

I start Archivebox with:

`sudo systemctl start docker.service` then from inside the archivebox folder run `docker-compose up -d` then open the web GUI to archive.

How can I run this command `archivebox update -t timestamp 1636303242.308281` from the CLI or GUI?

I am not sure opening an issue is the right place to ask for help but I couldn't find any IRC or Matrix room to ask for help...

Thank you.

**Comment by pirate** [comment]
When running with Docker Compose, you need to run the archivebox command inside your container like so:

```bash
cd /path/to/your/archivebox/dir
docker-compose run archivebox update -t timestamp 1636303242.308281
```
