### ISSUE TITLE
Support requested in setting up Archivebox 

### ISSUE THREAD

**Issue by sebastiaan6907** [ArchiveBox/ArchiveBox#892]
I am looking for someone who can assist me in configuring Archivebox in the proper way to support my project.
My project is about a list of priceplans

Currently my list of URL's looks like this:
![Schermafbeelding 2021-11-17 om 21 00 26](https://user-images.githubusercontent.com/41118270/142273563-e07395e8-eaab-40a3-9b84-ed29aa544544.jpg)

The list is being used as an import file for a dashboard and the user who retrieves a particular company will be guided to the url mentioned in this table. Every URL points to a single page with a price scheme of the company. At the end of December each of these urls will get updated with information for 2022 or will get deleted and replaced with some other url for 2022. 
I would like to store the information for the current year and keep it accessible.
Therefore I would like to replace every URL with a URL that refers to a specific domain that holds an archive of all these pages. I have no interest in storing additional pages that are linked to this URL, etc. It's only about the information on the given url.

I am not enough an expert in internet pages and ArchiveBox has just too many features for me to get this done save and sound before the year is coming to an end and these pages are being replaced.

Can someone assist me in setting up such a project with ArchiveBox?

Thanks

**Comment by pirate** [comment]
Just run this every few months:

```bash
cat list_of_urls.txt > archivebox add
```

Then to view your archive run:
```bash
archivebox setup
archivebox server 0.0.0.0:8000
```
and open http://127.0.0.1:8000

All the setup instructions are clearly laid out in the Quickstart: https://github.com/ArchiveBox/ArchiveBox#quickstart

**Comment by darkstar** [comment]
> Just run this every few months:
> 
> ```shell
> cat list_of_urls.txt > archivebox add
> ```

Did you mean `|` instead of `>`?
