### ISSUE TITLE
WayBackMachine backup toggle in web GUI

### ISSUE THREAD

**Issue by dianatura** [ArchiveBox/ArchiveBox#896]
## Type 

 - [ ] General question or discussion
 - [x] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves

Being able to quickly switch the ability to backup content with and without WBM enabled.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

An option in the add page of the web GUI to enable / disable WBM ?
If this is doable it would be nice to have another settings in the admin panel to enable / disable a confirmation while backing up links to WBM to prevent potential mistakes, having this setting would allow people to choose so no one would be annoyed from a confirmation before each time they archive.

## What hacks or alternative solutions have you tried to solve the problem?

Well, beside changing the configuration every times I don't see what else I could do.
Mainly looking for something more efficient than editing the conf each time I need to toggle WBM backups

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [x] It would be nice to have eventually

---

 - [ ] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
There is already an option on the add page to select the archive methods, just Ctrl + A to select them all then deselect the way back machine.

**Comment by dianatura** [comment]
Oh, I did not notice that.
Sorry for the useless issue then and thank you for maintaining the project !

**Comment by pirate** [comment]
No, I'm just on an extended vacation / travel for the last year+ and haven't been coding. This is still a main project for me long-term though, full intention to continue maintaining and improving it over the next 5+ years. 

The dev branch is also fairly active with contributor fixes (but I haven't rolled a master release in a while).
