### ISSUE TITLE
Question: Do we really need healthcheck?

### ISSUE THREAD

**Issue by upsuper** [ArchiveBox/ArchiveBox#897]
Today I noticed that my disk write rate increased over the past months, and when I investigated, I found Docker did a large amount of disk write, which was seemingly from regularly writing `config.v2.json` in the directory of ArchiveBox container. When I inspected that file, I found that there are logs for healthcheck, and the container has been in unhealthy state for a long time because I changed the service port of the container in `docker-compose.yml`. I tried bringing it back to healthy state by changing the port back, but the problem was still there, and the disk write rate I could see at that point was ~15MB per 30s. Eventually I disabled healthcheck in `docker-compose.yml` and this problem stops.

There are two observations:
* the unhealthy state had been there for a long time, and nothing ever brought that up to me
* the healthcheck may produce large disk write

So I wonder whether it's really meaningful to have the healthcheck at all. It doesn't seem to be useful that it can inform users if something goes wrong, and it seems to be wasting resources. Should we drop it? Or disable it by default in the provided `docker-compose.yml`?

**Comment by pirate** [comment]
huh I don't see any healthcheck enabled in https://github.com/ArchiveBox/ArchiveBox/blob/dev/docker-compose.yml, I explicitly don't add those and leave them to the user to configure if they need it.

**Comment by upsuper** [comment]
My guess would be that if the `Dockerfile` contains healthcheck, it's enabled by default, unless it's overridden in `docker-compose.yml`. If the intention is that it's left to user, maybe the compose file should have it disabled with a comment?

**Comment by mAAdhaTTah** [comment]
Healthcheck is configured [here](https://github.com/ArchiveBox/ArchiveBox/blob/dev/Dockerfile#L122-L123).

**Comment by pirate** [comment]
Commented it out: https://github.com/ArchiveBox/ArchiveBox/commit/b40a1e19d1a5c34f3c88e5b1e377fd93e6ef774a
