### ISSUE TITLE
standard_init_linux.go:207: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by Roki100** [ArchiveBox/ArchiveBox#900]
how can i fix this?
```
pi@raspberrypi:~/archivebox $ cat /proc/cpuinfo | grep Model
Model           : Raspberry Pi 4 Model B Rev 1.2
pi@raspberrypi:~/archivebox $ sudo docker run -v $PWD:/data -it archivebox/archivebox init --setup
standard_init_linux.go:207: exec user process caused "exec format error"
pi@raspberrypi:~/archivebox $
```
archivebox seems to be the project i really find useful but i cant manage to run it on my pi with docker

**Comment by pirate** [comment]
Use the `:dev` image instead of `:latest`:

`sudo docker run -v $PWD:/data -it archivebox/archivebox:dev init --setup`

**Comment by Roki100** [comment]
> Use the `:dev` image instead of `:latest`:
> 
> `sudo docker run -v $PWD:/data -it archivebox/archivebox:dev init --setup`

Thank you!
