### ISSUE TITLE
Singlefile not working in docker-compose on arm64 (M1 Macs, RPi 4, etc.)

### ISSUE THREAD

**Issue by jillisstada** [ArchiveBox/ArchiveBox#903]
Have archivebox running local on my mac which works fine with a local installed single-file.
Want to user docker-compose run archivebox  add .... with single-file
docker-compose run  archivebox  works but not single-file
```logs
      > singlefile
        Extractor failed:                                                                                                                                                                             
             SingleFile was not able to archive the page
            Got single-file response code: 0.
```
I added in Archivebox.conf 
```ini
[DEPENDENCY_CONFIG]
SINGLEFILE_BINARY = /opt/homebrew/lib/node_modules/single-file/cli/single-file  
```
Maybe this is more a docker question?

**Comment by jillisstada** [comment]
docker-compose archivebox --version gives:
 √  SINGLEFILE_BINARY     v0.3.16         valid     /node/node_modules/single-file/cli/single-file 
which is not on my mac
doesn't read my ArchiveBox.conf?

**Comment by pirate** [comment]
Docker uses a linux system and has all its dependencies bundled with it internally already, do not set ` SINGLEFILE_BINARY` or any other `_BINARY` configs when using docker.

**Comment by jillisstada** [comment]
Thanks for responding
I added the setting because it didn't work.
get this error 
      > singlefile
        Extractor failed:                                                                                                                                                                             
             SingleFile was not able to archive the page
            Got single-file response code: 0.
attached yml and conf as zip
[Archive.zip](https://github.com/ArchiveBox/ArchiveBox/files/7730660/Archive.zip)

**Comment by pirate** [comment]
You have `SAVE_SINGLEFILE = False` and `SINGLEFILE_BINARY = /opt/homebrew/lib/node_modules/single-file/cli/single-file` still set in your config, please remove those and try again.

**Comment by jillisstada** [comment]
before adding SINGLEFILE_BINARY  it didn't work, that's why I put it in, it should not be there  anymore.
SAVE_SINGLEFILE = False because I don't want single file all the time.
I wrote a program that sets SAVE_SINGLEFILE = True  occasionally : 
docker-compose run archivebox  config --set SAVE_SINGLEFILE=True
With the local installed archivebox without docker that works fine;
I'll try your suggestions tomorrow, latest version and always true.
I am in Amsterdam Holland and it's nearly midnight, watching Succession.
Thank You

**Comment by jillisstada** [comment]
[Terminal Saved Output.txt](https://github.com/ArchiveBox/ArchiveBox/files/7733821/Terminal.Saved.Output.txt)
I've tried docker-compose with and without default Archivebox.conf and with :dev, output in attachment.
I keep getting the error.
      > singlefile
        Extractor failed:                                                                                                                                                                             
             SingleFile was not able to archive the page
            Got single-file response code: 0.
I'm running on a mac M1 but that shouldn't be the problem.
archivebox and single-file installed on the mac works fine.
I will take a docker course

**Comment by jillisstada** [comment]
![Screenshot 2021-12-21 at 09 52 49](https://user-images.githubusercontent.com/48590240/146900603-d2181e09-b14d-4983-b310-be56c59fdf2d.png)

**Comment by jillisstada** [comment]
installed docker archivebox on a intel chip mac, no problem

**Comment by pirate** [comment]
Ah that makes sense, I was wondering why I've been unable to reproduce this on my Intel mac.

**Comment by tam481** [comment]
Hello, I recently started using ArchiveBox (Brilliant product. Well done). I am getting the same error on my Raspberry Pi 4 (arch64) running Debian Bullseye. Apologies if that is a different issue.

Whenever I try to archive a page I get:
singlefile Extractor failed: SingleFile was not able to archive the page Got single-file response code: 0.

**Comment by darkstar** [comment]
This is actually #905 the single-file error is a red herring. If you enter the container and execute the commands it tells you to, you see that it's not finding the correct chromium executable
