### ISSUE TITLE
Question: Merge two ArchiveBox collections

### ISSUE THREAD

**Issue by dbready** [ArchiveBox/ArchiveBox#915]
First of all -thanks for this great project. Gives me real peace of mind that I know I can easily reference back to a few articles forever.

I have two different machines that I use on a regular basis. Each of these have their own Archives I created with some collection of same/different urls archived at different times (theoretically, there would be no overlapping timestamps, but time is a funny thing).

Is there a built in mechanism I can use to merge Archivebox A into Archivebox B to get the union of content into a single repository? I was unable to find documentation describing this scenario, but it is possible I missed something obvious.

Thanks.

**Comment by pirate** [comment]
Added a wiki page: https://github.com/ArchiveBox/ArchiveBox/wiki/Upgrading---Merging-Archives
