### ISSUE TITLE
Question: How to set up `scheduler:` container in `docker-compose.yml`

### ISSUE THREAD

**Issue by akhilleusuggo** [ArchiveBox/ArchiveBox#917]
I'm not sure if it's bug or I'm missing something here.
Using docker-compose , rpi4

The singlefile is not working, I've seen that on other issue.
But the feature that pulls new links featured as example on the docker-compose.yml is not working.
https://github.com/ArchiveBox/ArchiveBox/blob/663918a37298d6b7617d1f36d346f95947c5bab2/docker-compose.yml#L48

```
docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.archivebox: 'scheduler'
```

Removing the `scheduler` doesn't work, since you end with multiple command sections. Tried this solution https://stackoverflow.com/questions/30063907/using-docker-compose-how-to-execute-multiple-commands but no luck.

PS: Maybe I'm just not catching the idea of it, since it seems that we're trying to run a separate container for the schedule feature.

**Comment by darkstar** [comment]
Your indenting is incorrect. The `scheduler` tag should not be under `archivebox` but at the same level with it

**Comment by akhilleusuggo** [comment]
Do you mind an example? I'm still not getting it.
Maybe the docker-compose should be updated with your solution. Because the way it is now is not working.

**Comment by darkstar** [comment]
Your file is not confirming to the required YAML schema. It even tells you that it reads the `scheduler` tag as config option for `services.archivebox`, when instead it should be a separate service. So you should write it like this:

```
services:
  archivebox:
    ...
  scheduler:
    ...
```
instead of this
```
services:
  archivebox:
    ...
    scheduler:
    ...
```

**Comment by akhilleusuggo** [comment]
Thank you!
