### ISSUE TITLE
Configure admin user on Synology NAS using Docker

### ISSUE THREAD

**Issue by tobivan** [ArchiveBox/ArchiveBox#928]
Hi there,

how do I setup an admin user on Synology Docker?
Where do I enter 'archivebox manage createsuperuser' or 'docker-compose run archive manage createsuperuser' ?

Thanks a lot.
Tobias

**Comment by tobivan** [comment]
Thanks, that would be possible. However, as all tables are empty so far, it is not sufficient to add a user only. What other entries do I have to create, e.g. in groups etc.?
Thanks!
![grafik](https://user-images.githubusercontent.com/25041087/159158045-565556c8-27b3-4b37-bfa0-3ecf5a7cca35.png)

**Comment by drdang2** [comment]
I came across this post https://github.com/ArchiveBox/ArchiveBox/issues/734 which the dev added the ability to use env variables to add admin and password but it doesn't seem to work for me

**Comment by pirate** [comment]
The environment variables to pre-set user/pass are not implemented yet, they're just an idea right now. Here's an example of how you could do it in SQLite3:

```bash
pip3 install django==3.1.3   # install django
python3                      # open any python shell with django available, doesn't have to be the archivebox shell
```
```python3
>>> from django.contrib.auth.hashers import make_password
>>> make_password('newpassword', 'someSaltHere', 'pbkdf2_sha256')         # choose a password and a salt (can be anything 12 chars long)
'pbkdf2_sha256$216000$someSaltHere$styW1Uoy8SHp3zbSwGRp20C9mPjOHVjP9rl5a8/UOVE='
```
Take that output, and use it to create the new User row in the SQLite3 database directly:
```bash
cd ~/archivebox       # path to your archivebox collection
sqlite3 index.sqlite3
```
```sql
INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined")
VALUES ('pbkdf2_sha256$216000$iXTfBzcCKXAP$+2beZufc3JUXnmn0tG+2peJEBh7MjxPYmT3YfIFzEl0=', NULL, 0, 'someUsername', '', '', 'someEmail@example.com', 0, 1, '2022-03-22 23:34:02.333042')
```
Replace the values above with the desired username, email, and password hash from python output^.

**Comment by jonaharagon** [comment]
All you do is open the container's details window, click the 'Terminal' tab, click 'Create' to create a bash terminal, and enter:
```
su archivebox
archivebox manage createsuperuser
```
<img width="934" alt="Screenshot 2022-08-24 at 23 30 13@2x" src="https://user-images.githubusercontent.com/3637842/186575300-4f6ea0ee-242b-4ca4-998c-c5108acb97d0.png">
