### ISSUE TITLE
New Logo, please

### ISSUE THREAD

**Issue by PLK2** [ArchiveBox/ArchiveBox#937]
Found this on the interweb and think it's a welcome improvement to the current logo.
<img width="640" alt="6ce4d400-6129-11e9-9898-707bd6d5df76" src="https://user-images.githubusercontent.com/20099374/155619113-4b1649c9-f683-4bfc-96c9-3fd7a94304ef.png">

**Comment by PLK2** [comment]
Also, "your", "own", and "personal" all imply the same thing. "Own" wouldn't be missed.

"YOUR PERSONAL INTERNET ARCHIVE"

**Comment by pirate** [comment]
This is a very old footer image I made in 30sec, I don't think we use it many places anymore. Going to close this as I don't plan on changing the logo right now.

**Comment by Jonirico11** [comment]
😣😣
