### ISSUE TITLE
Does ArchiveBox support archiving a single page and all its related assets?

### ISSUE THREAD

**Issue by zhiqiangxu** [ArchiveBox/ArchiveBox#939]
Sometimes we want to archive a single page with all related assets instead of the whole site, does archivebox support this feature?

**Comment by varenc** [comment]
That's literally exactly what ArchiveBox does. It saves individual URLs, and their associated assets. It does not try to crawl entire websites. What gave you the wrong impression?

**Comment by zhiqiangxu** [comment]
> related

I saw this command:

```
archivebox schedule --every=day --depth=1 https://example.com/rss.xml 
```

It looks like it's going to crawl entire websites, especially the word `schedule`, if it only crawls a single url, no need to `schedule`, right?

**Comment by akhilleusuggo** [comment]
schedule is for feed/rss webpages that changes every=day/hour/month etc.
archivebox will not re-download the same url
to redownload the same url you need to take a snapshot

> It looks like it's going to crawl the entire website
No, like the command line states, --depth=1. Only one hope away from the URL that you indicate. For example on RSS/Feed pages, you will be downloading the content of the URLs on that the rss does provide. Everyday will check if new URLs have been added and download them, old ones (already crawled) will be ignored.

**Comment by zhiqiangxu** [comment]
This command fails to install:
```
curl -sSL 'https://get.archivebox.io' | sh
```

The final output is this:

```
sudo: python3.7: command not found

Python 3.6.9
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
/usr/bin/python3: No module named django
```

My installed python version is 2.7, does archivebox only support python 3.x?

**Comment by pirate** [comment]
Yes, we dropped Python 2.7 support. @zhiqiangxu

**Comment by zhiqiangxu** [comment]
Do you have binary release then?

**Comment by pirate** [comment]
Docker
