### ISSUE TITLE
Feature Request: Add tag support to `archivebox schedule`

### ISSUE THREAD

**Issue by homelabhero** [ArchiveBox/ArchiveBox#941]
## Type 

 - [ ] General question or discussion
 - [X] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves
Adding tag support to scheduled imports (such as an rss feed) offers an easy way to search snapshots for bulk scheduled archives or filter out noise. 

## What hacks or alternative solutions have you tried to solve the problem?
archivebox add CLI supports tags, but not the archivebox schedule command

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [X] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [X] I'm willing to contribute [money](https://github.com/sponsors/pirate) to fix this issue
 - [ ] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
Done! 8ab17f0

Pull the latest `:dev` build to get this early, or wait for the 0.7.2 release.

https://github.com/ArchiveBox/ArchiveBox#install-and-run-a-specific-github-branch
