### ISSUE TITLE
Bug: Broken URLs block entire import when using `depth=1`

### ISSUE THREAD

**Issue by devsorice** [ArchiveBox/ArchiveBox#944]
#### Describe the bug
While using command "archivebox add", 
impossible to import a list of hundred, or thousands of good links, if there is just one broken link
Is there a way to ignore broken links?
I understand that devs might have intended this as a feature, however the cli is not usable, if you happen to 
have even one link that doesn't work, you cant' import anything.
See also https://github.com/ArchiveBox/ArchiveBox/issues/444

#### Steps to reproduce
Just put any broken link, or a link to a website that is currently not online in a txt file

#### Screenshots or log output
Command used
docker-compose run -e ONLY_NEW=true  archivebox add  --depth=1 --tag=barra-dei-preferiti < barra-dei-preferiti.txt

Output
[!] Failed to download https://www.wunderlist.com/webapp/#/tasks/859529680

HTTPSConnectionPool(host='www.wunderlist.com', port=443): Max retries exceeded with url: /webapp/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0adabe64c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
ERROR: 1

#### ArchiveBox version
docker   tag  :latest

**Comment by pirate** [comment]
This is specific to depth=1, for now I suggest adding in two passes. One with depth=1 and the next with depth=1.

**Comment by devsorice** [comment]
Sorry, 
my bad,
i didn't even want to archive links one hop away.
Only the ones in the list inside the txt file .
So without   depth=1, if the url doesn't resolve it shouldn't block the import?

**Comment by pirate** [comment]
Correct, it wont block import when using depth=0 @devsorice.

**Comment by devsorice** [comment]
Thank you!
(and sorry for the stupid question btw)

**Comment by pirate** [comment]
I actually want to leave this open to fix the depth=1 blocking issue. Not a stupid question at all it's a valid bug.

**Comment by pirate** [comment]
Fixed in 8cfe6f4
