### ISSUE TITLE
Bug: `archivebox init --setup` through `docker-compose` throws  "Permission denied" errors on `/data` folder

### ISSUE THREAD

**Issue by dlo** [ArchiveBox/ArchiveBox#948]
#### Describe the bug

Running most archivebox commands fail with "Permission denied" errors on the `/data` folder. I have followed the instructions exactly as they are in the README on macOS Monterey 12.2.1.

#### Steps to reproduce

```
mkdir ${ARCHIVEBOX_FOLDER}
cd ${ARCHIVEBOX_FOLDER}
mkdir ~/archivebox && cd ~/archivebox
curl -O 'https://raw.githubusercontent.com/ArchiveBox/ArchiveBox/master/docker-compose.yml'
docker-compose run archivebox init --setup
```

#### Screenshots or log output
![Screenshot 2022-03-18 at 10 56 48@2x](https://user-images.githubusercontent.com/38447/159038221-a77c7748-912b-4d32-8302-f4298d8bd781.png)

#### ArchiveBox version

```
ArchiveBox v0.6.2
Cpython Linux Linux-5.10.88-0-virt-x86_64-with-glibc2.28 x86_64
IN_DOCKER=True DEBUG=False IS_TTY=True TZ=UTC SEARCH_BACKEND_ENGINE=ripgrep

[i] Dependency versions:
 √  ARCHIVEBOX_BINARY     v0.6.2          valid     /usr/local/bin/archivebox
 √  PYTHON_BINARY         v3.9.5          valid     /usr/local/bin/python3.9
 √  DJANGO_BINARY         v3.1.10         valid     /usr/local/lib/python3.9/site-packages/django/bin/django-admin.py
 √  CURL_BINARY           v7.64.0         valid     /usr/bin/curl
 √  WGET_BINARY           v1.20.1         valid     /usr/bin/wget
 √  NODE_BINARY           v15.14.0        valid     /usr/bin/node
 √  SINGLEFILE_BINARY     v0.3.16         valid     /node/node_modules/single-file/cli/single-file
 √  READABILITY_BINARY    v0.0.2          valid     /node/node_modules/readability-extractor/readability-extractor
 √  MERCURY_BINARY        v1.0.0          valid     /node/node_modules/@postlight/mercury-parser/cli.js
 √  GIT_BINARY            v2.20.1         valid     /usr/bin/git
 √  YOUTUBEDL_BINARY      v2021.04.26     valid     /usr/local/bin/youtube-dl
 √  CHROME_BINARY         v90.0.4430.93   valid     /usr/bin/chromium
 √  RIPGREP_BINARY        v0.10.0         valid     /usr/bin/rg

[i] Source-code locations:
 √  PACKAGE_DIR           22 files        valid     /app/archivebox
 √  TEMPLATES_DIR         3 files         valid     /app/archivebox/templates
 -  CUSTOM_TEMPLATES_DIR  -               disabled

[i] Secrets locations:
 -  CHROME_USER_DATA_DIR  -               disabled
 -  COOKIES_FILE          -               disabled

[i] Data locations:
 √  OUTPUT_DIR            37 files        valid     /data
 √  SOURCES_DIR           0 files         valid     ./sources
 √  LOGS_DIR              1 files         valid     ./logs
 √  ARCHIVE_DIR           0 files         valid     ./archive
 √  CONFIG_FILE           81.0 Bytes      valid     ./ArchiveBox.conf
 √  SQL_INDEX             204.0 KB        valid     ./index.sqlite3
```

**Comment by akhilleusuggo** [comment]
It's not a bug, but a volumes permission issue.

**Comment by dlo** [comment]
I don’t think so. I didn’t create this folder. The only thing that set the incorrect permissions was Archivebox itself.

**Comment by akhilleusuggo** [comment]
Exactly, is docker creating it with the wrong permissions.

There are many ways on forums and topics to fix this issue. Problems coming from different OS or Linux flavors. I'm not an expert, can't give you a clear explanation.

But if your goal is to fix this, ( I don't believe it's a bug, since I'm not facing this issue, I tried to reproduce but work fine for me, except on my RPI4), you should change ownership of the folder /data to your user, and on the variable environment use the linuxserver.io convention (`PUID` and `PGID`). Something like this;

```
................
ports:
            - 8000:8000
        environment:
            - PUID=1000
            - PGID=1000
            - ALLOWED_HOSTS=*
..................
```


https://github.com/ArchiveBox/ArchiveBox/pull/635

**Comment by pirate** [comment]
@akhilleusuggo is correct, this is an underlying permissions issue with the volume, not something archivebox can control. Depending on the OS you may need to set PUID/PGID and make sure they are the owners of the folder on the host.

**Comment by dlo** [comment]
Appreciate the feedback, but I think the docs could be clearer about this. I followed the instructions in the README as instructed, so I think this is a bug with ArchiveBox's Docker configuration, but what do I know. :)

**Comment by snowshoes** [comment]
the problem persists, even after adding puid & pgid in docker-compose.yaml file
