### ISSUE TITLE
Question: Customize extractor options

### ISSUE THREAD

**Issue by akhilleusuggo** [ArchiveBox/ArchiveBox#953]
Is there a way to customize the extractor option ( the default ones ), and not an individual from snapshots?

I'm using pihole and I'm running into some issues with `wget`. It gets stuck when downloading some blocked DNS records. Keeps trying IPv6. I would like to add flag `-4` or `--inet4-only` to force skip those urls, and not keep looping or stuck trying IPv6 that I don't even have.

PS; I'm using docker-compose.

**Comment by pirate** [comment]
Yes, see the configuration wiki page. All the toggles are in there.

**Comment by akhilleusuggo** [comment]
I've been searching on the wiki before I wrote this post, I'm unable to find this on the wiki.

`WGET_ARGS` is not documented.

https://github.com/ArchiveBox/ArchiveBox/wiki/Configuration

**Comment by pirate** [comment]
WGET_ARGS expects a json formatted list, pass it like this: `WGET_ARGS="[\"--inet-only\"]"`. Also it overrides the default args, so if you want any of those you have to add them to the list too.

**Comment by akhilleusuggo** [comment]
Still getting issues. When you get some spare time, I hope you could document it on the wiki.

![image](https://user-images.githubusercontent.com/52116577/159890883-2168388a-9afa-494a-90f2-3658e0f8a2ce.png)

**Comment by pirate** [comment]
Please post the full verbatim content of `ArchiveBox.conf`.

**Comment by akhilleusuggo** [comment]
```
:/data# cat ArchiveBox.conf
[SERVER_CONFIG]
SECRET_KEY = xxxxxxxxxxxxxxxxxxxxx
```

I have no options here. All options are via compose file.

```
archivebox --version
ArchiveBox v0.6.2
Cpython Linux Linux-5.4.0-105-generic-x86_64-with-glibc2.28 x86_64
IN_DOCKER=True DEBUG=False IS_TTY=True TZ=UTC SEARCH_BACKEND_ENGINE=sonic

[i] Dependency versions:
 √  ARCHIVEBOX_BINARY     v0.6.2          valid     /usr/local/bin/archivebox
 √  PYTHON_BINARY         v3.9.5          valid     /usr/local/bin/python3.9
 √  DJANGO_BINARY         v3.1.10         valid     /usr/local/lib/python3.9/site-packages/django/bin/django-admin.py
 √  CURL_BINARY           v7.64.0         valid     /usr/bin/curl
 √  WGET_BINARY           v1.20.1         valid     /usr/bin/wget
 √  NODE_BINARY           v15.14.0        valid     /usr/bin/node
 √  SINGLEFILE_BINARY     v0.3.16         valid     /node/node_modules/single-file/cli/single-file
 √  READABILITY_BINARY    v0.0.2          valid     /node/node_modules/readability-extractor/readability-extractor
 √  MERCURY_BINARY        v1.0.0          valid     /node/node_modules/@postlight/mercury-parser/cli.js
 √  GIT_BINARY            v2.20.1         valid     /usr/bin/git
 -  YOUTUBEDL_BINARY      -               disabled  /usr/local/bin/youtube-dl
 √  CHROME_BINARY         v90.0.4430.93   valid     /usr/bin/chromium
 √  RIPGREP_BINARY        v0.10.0         valid     /usr/bin/rg

[i] Source-code locations:
 √  PACKAGE_DIR           22 files        valid     /app/archivebox
 √  TEMPLATES_DIR         3 files         valid     /app/archivebox/templates
 -  CUSTOM_TEMPLATES_DIR  -               disabled

[i] Secrets locations:
 -  CHROME_USER_DATA_DIR  -               disabled
 -  COOKIES_FILE          -               disabled

[i] Data locations:
 √  OUTPUT_DIR            17 files        valid     /data
 √  SOURCES_DIR           56731 files     valid     ./sources
 √  LOGS_DIR              1 files         valid     ./logs
 √  ARCHIVE_DIR           4591251 files   valid     ./archive
 √  CONFIG_FILE           81.0 Bytes      valid     ./ArchiveBox.conf
 √  SQL_INDEX             4.2 GB          valid     ./index.sqlite3
```

**Comment by pirate** [comment]
Ah ok for the compose file try separating the args with spaces or commas instead, I don't remember how that parser works but I can check later.

**Comment by akhilleusuggo** [comment]
I appreciate it. Thank you.

**Comment by akhilleusuggo** [comment]
@pirate I've found your own answer by luck looking into another problem. Thank you. I'm closing.

https://github.com/ArchiveBox/ArchiveBox/issues/865
