### ISSUE TITLE
Feature Request: ...

### ISSUE THREAD

**Issue by alexxroche** [ArchiveBox/ArchiveBox#954]
## Type 
 - [☑] Request modification of existing behaviour or design

## What is the problem that your feature request solves
Have the installer know that Raspbian is just a version of debian

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
Not have this:
```bash
$ curl -sSL 'https://get.archivebox.io' | sh
<snip>
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster
```
## What hacks or alternative solutions have you tried to solve the problem?
Nothing. (I don't currently have time to extend the installer.)

## How badly do you want this new feature?
 - [☑] It would be nice to have eventually

-- 
 - [☑] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
The installer supports neither Debian nor Raspbian natively, you should use the manual Apt instructions instead: https://github.com/ArchiveBox/ArchiveBox#-package-manager-setup
