### ISSUE TITLE
Documentation: Document how search works

### ISSUE THREAD

**Issue by bbkane** [ArchiveBox/ArchiveBox#956]
## Wiki Page URL

https://github.com/ArchiveBox/ArchiveBox/wiki/Usage#explanation-of-buttons-in-the-web-ui---admin-snapshots-list

## Suggested Edit

Document how search works in Archivebox. It looks like https://github.com/ArchiveBox/ArchiveBox/pull/721  and https://github.com/ArchiveBox/ArchiveBox/pull/543 add full text search using Sonic, but I can't find advanced usage details. Can it do boolean queries (`"rabbits" AND NOT "racoons"`) for example? Would someone more familiar with the project  add a few sentences describing what the capabilities of the search are and maybe some examples explaining how to use it?

**Comment by bbkane** [comment]
Does it search the body as well as the title? Can I order by fields in the query?

**Comment by rcarmo** [comment]
It would be great to have this documented. Right now it feels like I can't do full text search on page contents, and it is mostly because search is inscrutable.

**Comment by pirate** [comment]
I don't believe it can do Boolean queries but if you have Sonic you can do full-text search of the article bodies with fuzzy matching.

**Comment by rcarmo** [comment]
I’m using the container image (which I assume includes it). Yet the lack of documentation still applies.

**Comment by pirate** [comment]
I've added a line to the Usage docs and a screenshot explaining search slightly more here: https://github.com/ArchiveBox/ArchiveBox/wiki/Usage#explanation-of-buttons-in-the-web-ui---admin-snapshots-list

I still have to add instructions on how to set up Sonic/ripgrep and configure them later.

**Comment by diego898** [comment]
@pirate - I had to download the `sonic.cfg` the root directory not the `data` folder. 

Also, after `down; down; up` I tried `docker-compose run archivebox update --index-only`

and got:

```
~/archivebox
❯ docker-compose run archivebox update --index-only
[i] [2023-01-19 02:45:38] ArchiveBox v0.6.2: archivebox update --index-only
    > /data

[*] Indexing url: https://www.ecliptik.com/bookmarking-with-raindrop/ in the search index

[!] Sonic search backend threw an error while indexing: SonicServerError ERR invalid_meta_key(?["])
```

I've only indexed a single website so far

**Comment by pirate** [comment]
This is mostly done now! Check out our new documentation page here: https://github.com/ArchiveBox/ArchiveBox/wiki/Setting-up-Search

I still have to document the config options on the `Configuration` page but it's a start.

For improvements / suggestions you can comment back here or open a PR with changes for this file:
https://github.com/ArchiveBox/docs/blob/master/Setting-up-Search.md
