### ISSUE TITLE
Feature Request: Ability to Disable Authentication

### ISSUE THREAD

**Issue by vorpalhex** [ArchiveBox/ArchiveBox#957]
Having good secure authentication by default is the correct thing. However, many authentication situations such as reverse-proxy authentication or vpn based access means authentication is already occurring before we even get to Archivebox. Hopefully over time ArchiveBox will work with some of these (such as the WIP reverse proxy support) but in the meantime it would be tremendously useful to be able to disable authentication entirely and just dump users into a default profile with admin abilities. ArchiveBox is never going to be able to support ever auth pattern under the sun - and in many single user cases it doesn't need to.

This should come with the appropriate warnings and flags, the usual encouragement to not do such a thing and so on. However, it should be possible.

I'm a single user instance of archivebox. It's lan accessible, wrapped behind a reverse proxy and so on. Having a double login screen is really painful for me as a user, especially as much of my usage is on mobile.

**Comment by pirate** [comment]
Already in progress: https://github.com/ArchiveBox/ArchiveBox/pull/866 #773
