### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by ClandestineClout** [ArchiveBox/ArchiveBox#958]
(Windows alpha desktop electron client)

Here is the log:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.14.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electron-archivebox@0.6.2~prestart: electron-archivebox@0.6.2
6 info lifecycle electron-archivebox@0.6.2~start: electron-archivebox@0.6.2
7 verbose lifecycle electron-archivebox@0.6.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle electron-archivebox@0.6.2~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\John\Downloads\Programs\electron-archivebox-main\node_modules\.bin;C:\Program Files\Python310\Scripts\;C:\Program Files\Python310\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;E:\Encode etc tools\eac3to334;C:\Program Files\nodejs;C:\Windows\System32;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Process Lasso\;C:\Program Files\dotnet\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\ProgramData\chocolatey\bin;;C:\Program Files\Microsoft VS Code\bin;C:\Users\John\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\John\AppData\Local\Programs\Python\Python37\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;E:\Encoding etc  tools\eac3to334;C:\Program Files\Python38\Scripts;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps
9 verbose lifecycle electron-archivebox@0.6.2~start: CWD: C:\Users\John\Downloads\Programs\electron-archivebox-main
10 silly lifecycle electron-archivebox@0.6.2~start: Args: [ '/d /s /c', 'electron-forge start' ]
11 silly lifecycle electron-archivebox@0.6.2~start: Returned: code: 1  signal: null
12 info lifecycle electron-archivebox@0.6.2~start: Failed to exec start script
13 verbose stack Error: electron-archivebox@0.6.2 start: `electron-forge start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid electron-archivebox@0.6.2
15 verbose cwd C:\Users\John\Downloads\Programs\electron-archivebox-main
16 verbose Windows_NT 10.0.19044
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v13.14.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error electron-archivebox@0.6.2 start: `electron-forge start`
22 error Exit status 1
23 error Failed at the electron-archivebox@0.6.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by pirate** [comment]
Sorry, I don't have the bandwidth to provide support for direct Windows installations, especially for the alpha Desktop app.

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/511499/161353755-a225fad8-0069-4d58-87e7-d8bedb11fff1.png">

**Comment by ClandestineClout** [comment]
If you don't have the bandwidth why waste people's time by offering it? You just wasted a good few hours of my time trying to get this working only to find this out. Thanks.

**Comment by pirate** [comment]
There's a reason it says "alpha".
