### ISSUE TITLE
Bug: UTF 8 implemented wrong in readability mode

### ISSUE THREAD

**Issue by PovilasID** [ArchiveBox/ArchiveBox#980]
#### Describe the bug
Then a data is taken with UTF 8 chars on website in "readability" option next to warc UTF 8 chars are not supported 

#### Steps to reproduce
In an instance of archive box pull a website with UTF 8 chars ( https://www.lrt.lt/ )
In readability mode you instead of chars like "š" you will get "Å¡" or "ė" -> "Ä—" etc.

#### ArchiveBox version
v0.6.2

**Comment by pirate** [comment]
Is this still happening for you on `0.7.2`?

**Comment by PovilasID** [comment]
There is an update first time since 2021! Woohoo!
I updated and tested it looks like it is handling UTF8 charset symbols correctly
