### ISSUE TITLE
Enhancement: Add `SINGLEFILE_ARGS` to pass custom CLI args to singlefile

### ISSUE THREAD

**Issue by renaisun** [ArchiveBox/ArchiveBox#981]
I see there're `WGET_ARGS` and `CURL_ARGS` in config.py passed to corresponding binaries. But I don't find a way to customize the options passed to singlefile binary. Is there any way to do so?

**Comment by pirate** [comment]
Ah sorry looks like we still need to add `SINGLEFILE_ARGS` and make sure it plays nicely with `CHROME_ARGS`. This will be a TODO for the next release. Contributors welcome.

**Comment by notevenaperson** [comment]
@renaisun Looks commit good to me. You should make a pull request asap, it might just get accepted with a button press on @pirate's end.

**Comment by pirate** [comment]
Closing as done! https://github.com/ArchiveBox/ArchiveBox/pull/1021 thanks @notevenaperson
