### ISSUE TITLE
Yt-dlp support

### ISSUE THREAD

**Issue by torek01** [ArchiveBox/ArchiveBox#989]
## Type 
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves
Archivebox doesn't download videos from the nitter which bypass an age verification and is more privacy friendly. Yt-dlp downloads valid video for the link from the nitter but youtube-dl does not. Besides it I found yt-dlp to have higher downloading speeds.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
Some easy way to use yt-dlp instead of youtube-dl.

## What hacks or alternative solutions have you tried to solve the problem?
Replaced youtube-dl.exe and folder with yt-dlp equivalent.
I tried changing binaries in the .yml file.

## How badly do you want this new feature?
 - [x] It would be nice to have eventually

**Comment by pirate** [comment]
ArchiveBox in Docker already uses yt-dlp, not youtube-dl. You can also configure it with YOUTUBEDL_BINARY.

**Comment by torek01** [comment]
Well, I tried to download media from the nitter both using youtube-dl and yt-dlp and the former one is having some problem download right content while the latter downloads the right one. 
ArchiveBox using docker doesn't download media for nitter. I also tried configure it with YOUTUBEDL_BINARY in the .yml file but I get error [Errno 2] No such file or directory but I have intalled yt-dlp.

**Comment by pirate** [comment]
Post the output of `archivebox version` and your `docker-compose.yml` file.

**Comment by torek01** [comment]
Ok, I solved it by installing yt-dlp in docker CLI, editing .yml file 
(- YOUTUBEDL_BINARY=yt-dlp) and archivebox config --set YOUTUBEDL_BINARY=path to yt-dlp.exe.
