### ISSUE TITLE
How to create superuser from within a bash script

### ISSUE THREAD

**Issue by happening-primal** [ArchiveBox/ArchiveBox#992]
Can you provide a suggestion on how to run 'archivebox manage createsuperuser' directly from within a bash script without the need to start a docker shell first using 'sudo docker exec -it --user archivebox  archivebox /bin/bash' and also, if possible, how to just pass directly the userid, email, and password, so that the whole thing can just be managed from within said bash script?

**Comment by pirate** [comment]
Here are the instructions on how to script adding a user / modifying the DB directly: https://github.com/ArchiveBox/ArchiveBox/wiki/Upgrading-or-Merging-Archives#example-adding-a-new-user-with-a-hashed-password

We may add an `ADMIN_USER=xxx` `ADMIN_PASSWORD=xxx` environment variable in the future to automate setting those on initial setup, but those options don't exist yet. Follow this issue for progress: https://github.com/ArchiveBox/ArchiveBox/issues/734
